"""Render historie/{slug}.md amendment timelines to standalone HTML pages.

Reads `historie/*.md` (generated by historie.py from amendments.db) and
writes per-law amendment timeline pages to `_site/historie/*.html`, linked
from per-law pages via the historikk section.

The historie markdown lists every amendment to every paragraph of every law
since 2001, with the amendment instruction (e.g. "§ 3-1 første ledd skal lyde:")
and the new text as a blockquote. This makes it the most actionable view for
someone asking "what changed in this law lately?" without leaving the site.
"""
from __future__ import annotations

import re
from pathlib import Path

try:
    import markdown as md
except ImportError:
    md = None

SITE_BASE = "https://sondreskarsten.github.io/norwegian-laws"

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="nb">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Endringshistorikk: {title} — Norges Lover</title>
{feed_autodiscovery}
<style>
body {{ max-width: 960px; margin: 0 auto; padding: 1.5rem; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; line-height: 1.55; color: #212529; }}
nav.breadcrumb {{ background: #f8f9fa; padding: 0.5rem 1rem; border-radius: 4px; margin-bottom: 1rem; font-size: 0.9rem; }}
nav.breadcrumb a {{ color: #2780e3; text-decoration: none; }}
nav.breadcrumb a:hover {{ text-decoration: underline; }}
.intro {{ background: #fff3cd; border-left: 3px solid #ffc107; padding: 0.75rem 1rem; margin: 1rem 0; font-size: 0.95rem; }}
h1 {{ font-size: 1.75rem; border-bottom: 2px solid #dee2e6; padding-bottom: 0.3rem; }}
h2 {{ font-size: 1.3rem; margin-top: 2rem; color: #495057; padding: 0.4rem 0.6rem; background: #f8f9fa; border-radius: 4px; }}
h3 {{ font-size: 1.05rem; margin-top: 1.25rem; color: #6c757d; font-weight: 600; }}
blockquote {{ border-left: 3px solid #2780e3; padding: 0.4rem 0.8rem; margin: 0.5rem 0; background: #f8f9fa; color: #495057; font-size: 0.95rem; }}
em {{ color: #6c757d; }}
.toc {{ background: #f8f9fa; padding: 0.75rem 1rem; border-radius: 4px; margin: 1rem 0; }}
.toc ul {{ margin: 0; padding-left: 1.2rem; columns: 3; column-gap: 1rem; }}
footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #dee2e6; color: #6c757d; font-size: 0.85rem; }}
</style>
</head>
<body>
<nav class="breadcrumb">
<a href="../index.html">Norges Lover</a> &raquo;
<a href="{law_url}">{short}</a> &raquo;
<span>Endringshistorikk</span>
</nav>

<h1>Endringshistorikk: {short}</h1>

<div class="intro">
Hver endring som er kunngjort i <a href="https://lovdata.no/register/lovtidend" target="_blank">Norsk Lovtidend</a>
siden 2001, gruppert per paragraf. Endringer fra før 2001 finnes ikke i denne oversikten.
<p style="margin: 0.5rem 0 0 0;">
📡 {feed_line} ·
🔍 Se gjeldende tekst: <a href="{law_url}">{short}</a> ·
📜 {archive_link}
</p>
</div>

{body}

<footer>
Datakilde: <a href="https://lovdata.no/" target="_blank">Lovdata</a> under
<a href="https://data.norge.no/nlod/no/2.0" target="_blank">NLOD 2.0</a>.
Ikke autoritativ — se Lovdata for autoritativ tekst.
</footer>
</body>
</html>
"""


def _parse_frontmatter(filepath: Path) -> tuple[dict, str]:
    text = filepath.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}, text
    try:
        end = text.index("\n---", 4)
    except ValueError:
        return {}, text
    fm_block = text[4:end]
    body = text[end + 4:].lstrip("\n")
    meta = {}
    for line in fm_block.splitlines():
        m = re.match(r'(\S+?):\s*"(.+?)"\s*$', line)
        if m:
            meta[m.group(1)] = m.group(2)
    return meta, body


def _build_toc(body_html: str) -> str:
    """Extract H2 headings (paragraph numbers) and build a TOC.

    The H2 may contain a trailing per-paragraph history link (added by
    _add_heading_anchors); strip that before generating the anchor.
    """
    headings = re.findall(r'<h2\s+id="([^"]+)">(.+?)</h2>', body_html, re.DOTALL)
    if not headings:
        return ""
    lines = ['<div class="toc"><strong>Paragrafer med endringer:</strong>', '<ul>']
    for anchor, raw_text in headings:
        # raw_text might be 'X-Y <a ...>...</a>'; keep only text before <a>
        clean = re.sub(r'\s*<a\s.*$', '', raw_text, flags=re.DOTALL).strip()
        if not clean:
            continue
        lines.append(f'  <li><a href="#{anchor}">{clean}</a></li>')
    lines.append('</ul></div>')
    return "\n".join(lines)


def _add_heading_anchors(body_html: str, refid: str | None = None, site_index=None) -> str:
    """Add id= attributes to H2 headings so TOC links resolve. When a
    paragraph H2 corresponds to a page paragraph_history actually generated
    (resolved through the site index), append a '⧉ paragraf' link to it;
    paragraphs outside the generated set stay plain text instead of linking
    into a 404."""
    def repl(match):
        text = match.group(1)
        anchor = re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')
        link = ""
        if refid and site_index is not None:
            m = re.match(r'§\s*(\d+[-–]\d+[a-z]?)', text.strip())
            if m:
                para_norm = m.group(1).replace("–", "-")
                target = site_index.para_page(refid, para_norm)
                if target:
                    link = (
                        f' <a class="para-history-link" '
                        f'href="../{target}" '
                        f'title="Detaljert endringshistorikk for § {para_norm}" '
                        f'style="font-size:0.65em;font-weight:normal;color:#2780e3;'
                        f'text-decoration:none;padding-left:0.5em;">⧉ paragraf</a>'
                    )
        return f'<h2 id="{anchor}">{text}{link}</h2>'
    return re.sub(r'<h2[^>]*>(§\s*[^<]+?)</h2>', repl, body_html)


def _render_body(body_md: str) -> str:
    if md is None:
        # Fallback: minimal escaping
        import html
        return f"<pre>{html.escape(body_md)}</pre>"
    return md.markdown(body_md, extensions=["fenced_code", "tables", "nl2br"])


def _feed_stem_for(refid: str) -> str:
    if refid.startswith("forskrift/"):
        return "forskrift-" + refid.split("/", 1)[1]
    return "lov-" + refid.split("/", 1)[1]


def _law_url_for(refid: str, index=None) -> str:
    """Root-relative-from-historie URL for a document, gated on existence.

    Repealed documents fall back to Lovdata's archived NLO/SFO copy."""
    if index is not None:
        doc = index.doc_page(refid)
        return f"../{doc}" if doc else index.lovdata_archive_url(refid)
    if refid.startswith("forskrift/"):
        return f"../forskrifter/forskrift-{refid.split('/', 1)[1]}.html"
    return f"../lover/lov-{refid.split('/', 1)[1]}.html"


def _law_path_for(refid: str) -> str:
    if refid.startswith("forskrift/"):
        return f"forskrifter/forskrift-{refid.split('/', 1)[1]}.md"
    return f"lover/lov-{refid.split('/', 1)[1]}.md"


def scan_historie_slugs(historie_dir: str = "historie") -> dict[str, str]:
    """refid -> site-root-relative historie page path, derivable before any
    rendering. Paragraph pages need this map earlier in the pipeline than the
    historie renderer runs; both must agree, so the renderer builds its
    manifest from the same scan."""
    src = Path(historie_dir)
    if not src.is_dir():
        return {}
    slugs: dict[str, str] = {}
    for md_file in sorted(src.glob("*.md")):
        meta, _ = _parse_frontmatter(md_file)
        refid = meta.get("refid", "")
        if refid:
            slugs[refid] = f"historie/{md_file.stem}.html"
    return slugs


def generate_historie_pages(
    historie_dir: str = "historie",
    site_dir: str = "_site",
    site_index=None,
) -> dict[str, str]:
    """Render every historie/*.md file to _site/historie/*.html.

    Returns a manifest of refid → output relative path for cross-linking.
    """
    src = Path(historie_dir)
    out = Path(site_dir) / "historie"
    if not src.is_dir():
        print(f"  {src} not found, skipping historie HTML generation")
        return {}

    out.mkdir(parents=True, exist_ok=True)
    manifest = {}
    count = 0

    for md_file in sorted(src.glob("*.md")):
        meta, body_md = _parse_frontmatter(md_file)
        refid = meta.get("refid", "")
        title = meta.get("tittel", md_file.stem)
        short = re.sub(r"\s*–\s*.*$", "", title).strip() or title
        if not refid:
            continue

        body_html = _render_body(body_md)
        body_html = _add_heading_anchors(body_html, refid=refid, site_index=site_index)
        toc_html = _build_toc(body_html)
        body_html = toc_html + body_html

        if site_index is None or refid in site_index.corpus:
            archive_link = (
                f'Full git-historikk: <a href="https://github.com/sondreskarsten/'
                f'norwegian-laws/commits/law-history/{_law_path_for(refid)}">git log</a>'
            )
        else:
            from .site_index import SiteIndex as _SI
            archive_link = (
                f'Opphevet \u2014 arkivert tekst: '
                f'<a href="{_SI.lovdata_archive_url(refid)}">Lovdata</a>'
            )
        feed_path = site_index.feed(refid) if site_index is not None else f"feeds/{_feed_stem_for(refid)}.xml"
        if feed_path:
            feed_autodiscovery = (
                f'<link rel="alternate" type="application/atom+xml" '
                f'title="Endringer i {short}" href="../{feed_path}">'
            )
            feed_line = f'Abonner p\u00e5 fremtidige endringer: <a href="../{feed_path}">Atom-feed</a>'
        else:
            feed_autodiscovery = (
                f'<link rel="alternate" type="application/atom+xml" '
                f'title="Norges Lover \u2014 alle endringer" href="../feed.xml">'
            )
            feed_line = 'Abonner p\u00e5 alle endringer: <a href="../feed.xml">Atom-feed</a>'
        page = PAGE_TEMPLATE.format(
            title=title,
            short=short,
            feed_autodiscovery=feed_autodiscovery,
            feed_line=feed_line,
            law_url=_law_url_for(refid, site_index),
            archive_link=archive_link,
            body=body_html,
        )
        out_file = out / f"{md_file.stem}.html"
        out_file.write_text(page, encoding="utf-8")
        manifest[refid] = f"historie/{md_file.stem}.html"
        count += 1

    print(f"  Generated {count} historie HTML pages at {out}")
    return manifest


if __name__ == "__main__":
    import sys
    h_dir = sys.argv[1] if len(sys.argv) > 1 else "historie"
    s_dir = sys.argv[2] if len(sys.argv) > 2 else "_site"
    generate_historie_pages(h_dir, s_dir)
