"""Build lightweight navigation search and a compact law catalog.

Run after `quarto render` and before deploying to gh-pages.
The public laws.json export stays unchanged. Body search is a separate,
explicitly downloaded index generated by per_law_pages after rendering.
"""
from __future__ import annotations
import json
import re
import sys
from pathlib import Path

GITHUB_BASE = "https://github.com/sondreskarsten/norwegian-laws"

CATALOG_COLUMNS = [
    "refid", "tittel", "korttittel", "aliases", "departement", "path",
    "tags", "amendments", "historie",
]


def write_search_catalog(laws: list[dict], path: Path, *, full_text: dict | None = None):
    """Write an internal versioned catalog without repeated URLs or field names.

    Rows follow columns; departement values index departments, and tags indexes
    tagSets. Consumers expand these dictionaries after loading. laws.json remains
    the supported full metadata export.
    """
    departments = sorted({dept for law in laws for dept in law.get("departement", [])})
    dept_ids = {dept: i for i, dept in enumerate(departments)}
    tag_sets = sorted({tuple(law.get("tags", [])) for law in laws})
    tag_ids = {tags: i for i, tags in enumerate(tag_sets)}
    rows = []
    for law in laws:
        rows.append([
            law["refid"], law["tittel"], law.get("korttittel", ""),
            law.get("aliases", []), [dept_ids[d] for d in law.get("departement", [])],
            law.get("path", "lover/" + law["file"]),
            tag_ids[tuple(law.get("tags", []))], law.get("amendments", 0),
            law.get("historie"),
        ])
    payload = {
        "version": 1, "columns": CATALOG_COLUMNS, "departments": departments,
        "tagSets": tag_sets, "documents": rows,
    }
    if full_text is not None:
        payload["fullText"] = full_text
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")


def dept_to_page(dept: str, kind: str = "lov") -> str:
    safe = re.sub(r"[^\w\s-]", "", dept).strip().replace(" ", "-").lower()
    prefix = "forskrift-dept" if kind == "forskrift" else "dept"
    return f"book/{prefix}-{safe}.html"


def merge_laws_into_search(site_dir: str = "_site", laws_json: str = "laws.json"):
    search_path = Path(site_dir) / "search.json"
    laws_path = Path(laws_json)

    if not laws_path.exists():
        print(f"  {laws_path} not found, skipping search index merge")
        return

    search_entries = json.loads(search_path.read_text(encoding="utf-8")) if search_path.exists() else []
    with open(laws_path, encoding="utf-8") as f:
        laws = json.load(f)

    # Replace prior generated law entries on repeat runs. Quarto's chapter text
    # is navigation context only; full legal text is available through opt-in search.
    retained = {}
    for entry in search_entries:
        if str(entry.get("objectID", "")).startswith(("lov:", "law:", "forskrift:")):
            continue
        retained[entry.get("objectID", entry.get("href", ""))] = {
            **entry, "text": entry.get("text", "")[:240],
        }
    search_entries = list(retained.values())
    existing_count = len(search_entries)

    for law in laws:
        kind = law.get("kind", "lov")
        href = law.get("path", "lover/" + law["file"]).removesuffix(".md") + ".html"
        text_parts = [
            law.get("korttittel", ""),
            law.get("refid", ""),
            " ".join(law.get("aliases", [])),
        ]
        text = " ".join(p for p in text_parts if p)
        search_entries.append({
            "objectID": f"{kind}:{law['file']}",
            "href": href,
            "title": law.get("tittel", ""),
            "section": "",
            "text": text,
        })

    search_path.parent.mkdir(parents=True, exist_ok=True)
    with open(search_path, "w", encoding="utf-8") as f:
        json.dump(search_entries, f, ensure_ascii=False, separators=(",", ":"))

    write_search_catalog(laws, Path(site_dir) / "search-catalog.json")

    print(f"  Search index: {existing_count} -> {len(search_entries)} entries (+{len(laws)} laws)")


if __name__ == "__main__":
    site = sys.argv[1] if len(sys.argv) > 1 else "_site"
    laws = sys.argv[2] if len(sys.argv) > 2 else "laws.json"
    merge_laws_into_search(site, laws)
