# Energidepartementet

*17 lover*

| Lov | Korttittel | Lovdata | Historikk |
|-----|-----------|---------|-----------|
| [Lov i henhold til konvensjonen mellem Norge og Sverige om visse spørsmål vedrøre](../lover/lov-1931-06-12-1.html) | Vassdragslov i h.t. konvensjon Norge/Sverige | [lovdata.no](https://lovdata.no/dokument/NL/lov/1931-06-12-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-1931-06-12-1.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-1931-06-12-1.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-1931-06-12-1.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-1931-06-12-1.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-1931-06-12-1.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-1931-06-12-1.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-1931-06-12-1.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-1931-06-12-1.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-1931-06-12-1.md) |
| [Lov om Norgespris og strømstønad til husholdninger](../lover/lov-2025-06-20-44.html) | Lov om Norgespris og strømstønad til husholdninger | [lovdata.no](https://lovdata.no/dokument/NL/lov/2025-06-20-44) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-2025-06-20-44.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-2025-06-20-44.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-2025-06-20-44.md) |
| [Lov om elsertifikater](../lover/lov-2011-06-24-39.html) | Elsertifikatloven | [lovdata.no](https://lovdata.no/dokument/NL/lov/2011-06-24-39) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-2011-06-24-39.md) · [v2011](https://github.com/sondreskarsten/norwegian-laws/blob/69eefdb106a4b7a379ab0ecd9e6f490ad852526d/lover/lov-2011-06-24-39.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-2011-06-24-39.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-2011-06-24-39.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-2011-06-24-39.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-2011-06-24-39.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-2011-06-24-39.md) |
| [Lov om endringer i energiloven (utnyttelse av overskuddsvarme og krav til automa](../lover/lov-2026-06-19-38.html) | Endringslov til energiloven | [lovdata.no](https://lovdata.no/dokument/NL/lov/2026-06-19-38) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-2026-06-19-38.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-2026-06-19-38.md) |
| [Lov om felles regler for det indre marked for naturgass (naturgassloven)](../lover/lov-2002-06-28-61.html) | Naturgassloven | [lovdata.no](https://lovdata.no/dokument/NL/lov/2002-06-28-61) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-2002-06-28-61.md) · [v2002](https://github.com/sondreskarsten/norwegian-laws/blob/46b02a1967fa3cf728590262511c89c938f0ff7d/lover/lov-2002-06-28-61.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-2002-06-28-61.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-2002-06-28-61.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-2002-06-28-61.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-2002-06-28-61.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-2002-06-28-61.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-2002-06-28-61.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-2002-06-28-61.md) |
| [Lov om fornybar energiproduksjon til havs (havenergilova)](../lover/lov-2010-06-04-21.html) | Havenergilova – havenl | [lovdata.no](https://lovdata.no/dokument/NL/lov/2010-06-04-21) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-2010-06-04-21.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-2010-06-04-21.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-2010-06-04-21.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-2010-06-04-21.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-2010-06-04-21.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-2010-06-04-21.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-2010-06-04-21.md) |
| [Lov om garantistillelse fra Statoil ASA ved emisjon og salg av statens aksjer](../lover/lov-2001-05-18-22.html) | Lov om garanti fra Statoil ASA ved aksjesalg | [lovdata.no](https://lovdata.no/dokument/NL/lov/2001-05-18-22) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-2001-05-18-22.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-2001-05-18-22.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-2001-05-18-22.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-2001-05-18-22.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-2001-05-18-22.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-2001-05-18-22.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-2001-05-18-22.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-2001-05-18-22.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-2001-05-18-22.md) |
| [Lov om konsesjon for rettigheter til vannfall mv. (vannfallrettighetsloven)](../lover/lov-1917-12-14-16.html) | Vannfallrettighetsloven | [lovdata.no](https://lovdata.no/dokument/NL/lov/1917-12-14-16) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-1917-12-14-16.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-1917-12-14-16.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-1917-12-14-16.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-1917-12-14-16.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-1917-12-14-16.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-1917-12-14-16.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-1917-12-14-16.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-1917-12-14-16.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-1917-12-14-16.md) |
| [Lov om mineralvirksomhet på kontinentalsokkelen (havbunnsmineralloven)](../lover/lov-2019-03-22-7.html) | Havbunnsmineralloven | [lovdata.no](https://lovdata.no/dokument/NL/lov/2019-03-22-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-2019-03-22-7.md) · [v2019](https://github.com/sondreskarsten/norwegian-laws/blob/da5aa7d485eb33be2a319426343ddbb86ce71318/lover/lov-2019-03-22-7.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-2019-03-22-7.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-2019-03-22-7.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-2019-03-22-7.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-2019-03-22-7.md) |
| [Lov om petroleumsvirksomhet [petroleumsloven]](../lover/lov-1996-11-29-72.html) | Petroleumsloven – petrl | [lovdata.no](https://lovdata.no/dokument/NL/lov/1996-11-29-72) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-1996-11-29-72.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-1996-11-29-72.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-1996-11-29-72.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-1996-11-29-72.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-1996-11-29-72.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-1996-11-29-72.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-1996-11-29-72.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-1996-11-29-72.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-1996-11-29-72.md) |
| [Lov om produksjon, omforming, overføring, omsetning, fordeling og bruk av energi](../lover/lov-1990-06-29-50.html) | Energiloven – enl | [lovdata.no](https://lovdata.no/dokument/NL/lov/1990-06-29-50) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-1990-06-29-50.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-1990-06-29-50.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-1990-06-29-50.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-1990-06-29-50.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-1990-06-29-50.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-1990-06-29-50.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-1990-06-29-50.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-1990-06-29-50.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-1990-06-29-50.md) |
| [Lov om registrering av import og leveranser av råolje i Det europeiske økonomisk](../lover/lov-1999-06-25-54.html) | Lov om registrering av råoljehandel – råolregl | [lovdata.no](https://lovdata.no/dokument/NL/lov/1999-06-25-54) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-1999-06-25-54.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-1999-06-25-54.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-1999-06-25-54.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-1999-06-25-54.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-1999-06-25-54.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-1999-06-25-54.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-1999-06-25-54.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-1999-06-25-54.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-1999-06-25-54.md) |
| [Lov om regulering og kraftutbygging i vassdrag (vassdragsreguleringsloven)](../lover/lov-1917-12-14-17.html) | Vassdragsreguleringsloven – vregl | [lovdata.no](https://lovdata.no/dokument/NL/lov/1917-12-14-17) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-1917-12-14-17.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-1917-12-14-17.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-1917-12-14-17.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-1917-12-14-17.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-1917-12-14-17.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-1917-12-14-17.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-1917-12-14-17.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-1917-12-14-17.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-1917-12-14-17.md) |
| [Lov om sikring mot naturskader](../lover/lov-1994-03-25-7.html) | Naturskadeloven | [lovdata.no](https://lovdata.no/dokument/NL/lov/1994-03-25-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-1994-03-25-7.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-1994-03-25-7.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-1994-03-25-7.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-1994-03-25-7.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-1994-03-25-7.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-1994-03-25-7.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-1994-03-25-7.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-1994-03-25-7.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-1994-03-25-7.md) |
| [Lov om undersøkelser etter og utvinning av petroleum i grunnen under norsk lando](../lover/lov-1973-05-04-21.html) | Lov om utvinning av petroleum under land | [lovdata.no](https://lovdata.no/dokument/NL/lov/1973-05-04-21) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-1973-05-04-21.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-1973-05-04-21.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-1973-05-04-21.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-1973-05-04-21.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-1973-05-04-21.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-1973-05-04-21.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-1973-05-04-21.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-1973-05-04-21.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-1973-05-04-21.md) |
| [Lov om vassdrag og grunnvann (vannressursloven)](../lover/lov-2000-11-24-82.html) | Vannressursloven – vrl | [lovdata.no](https://lovdata.no/dokument/NL/lov/2000-11-24-82) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-2000-11-24-82.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-2000-11-24-82.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-2000-11-24-82.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-2000-11-24-82.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-2000-11-24-82.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-2000-11-24-82.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-2000-11-24-82.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-2000-11-24-82.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-2000-11-24-82.md) |
| [Lov om vassdragene [vassdragsloven]](../lover/lov-1940-03-15-3.html) | Vassdragsloven – vdrl | [lovdata.no](https://lovdata.no/dokument/NL/lov/1940-03-15-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/lover/lov-1940-03-15-3.md) · [v2001](https://github.com/sondreskarsten/norwegian-laws/blob/5c8fbd29c7d0ebd23685bd13d9d3af79dc5c3c5e/lover/lov-1940-03-15-3.md) · [v2005](https://github.com/sondreskarsten/norwegian-laws/blob/40ccca141661ecd747ce48987ec3e3361b2a8844/lover/lov-1940-03-15-3.md) · [v2010](https://github.com/sondreskarsten/norwegian-laws/blob/2acff3bc134462defaacd1433d9cd363b58aa3d7/lover/lov-1940-03-15-3.md) · [v2015](https://github.com/sondreskarsten/norwegian-laws/blob/f327ae8f6c6e7575fe02cc142554bb26b774c6b8/lover/lov-1940-03-15-3.md) · [v2020](https://github.com/sondreskarsten/norwegian-laws/blob/861fc8232103bb96b4855c936998e5081d823622/lover/lov-1940-03-15-3.md) · [v2024](https://github.com/sondreskarsten/norwegian-laws/blob/5375454b5a95be70a3742a3eefb819d75cb1f5be/lover/lov-1940-03-15-3.md) · [v2025](https://github.com/sondreskarsten/norwegian-laws/blob/e594d138414d3d561ece67e1626f72210919cafb/lover/lov-1940-03-15-3.md) · [v2026](https://github.com/sondreskarsten/norwegian-laws/blob/096496cd477308d5df2a6573a31ef3ab3a021af6/lover/lov-1940-03-15-3.md) |
