# Justis- og beredskapsdepartementet

*611 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Alminnelig tjenesteinstruks for politiet (politiinstruksen)](../forskrifter/forskrift-1990-06-22-3963.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-06-22-3963) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-06-22-3963.md) |
| [Anerkjennelse av visse typer legitimasjonsdokumenter ved reise til Svalbard, jf.](../forskrifter/forskrift-2025-01-07-8.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-07-8) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-07-8.md) |
| [Anvendelse av lov om kommunal beredskapsplikt, sivile beskyttelsestiltak og Sivi](../forskrifter/forskrift-2012-12-07-1186.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-07-1186) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-07-1186.md) |
| [Bestemmelser for gjennomføring av nye tjenestetidsbestemmelser for mannskap som ](../forskrifter/forskrift-2006-06-19-648.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-19-648) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-19-648.md) |
| [Bestemmelser om delegasjon m.v. i forbindelse med Forvaltningslovens ikraftsette](../forskrifter/forskrift-1969-12-05-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1969-12-05-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1969-12-05-2.md) |
| [Byggeforskrift for Longyearbyen](../forskrifter/forskrift-2016-11-15-1329.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-11-15-1329) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-11-15-1329.md) |
| [Delegering av Justis- og beredskapsdepartementets forskriftskompetanse etter siv](../forskrifter/forskrift-2021-04-16-1175.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-04-16-1175) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-04-16-1175.md) |
| [Delegering av Justis- og beredskapsdepartementets myndighet etter barnebortførin](../forskrifter/forskrift-2020-01-28-89.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-28-89) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-28-89.md) |
| [Delegering av Justis- og beredskapsdepartementets myndighet etter domstolloven §](../forskrifter/forskrift-2022-10-31-1972.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-10-31-1972) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-10-31-1972.md) |
| [Delegering av Justis- og beredskapsdepartementets myndighet etter lov 17. juni 2](../forskrifter/forskrift-2019-03-07-192.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-07-192) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-07-192.md) |
| [Delegering av Justis- og beredskapsdepartementets myndighet etter lov 17. juni 2](../forskrifter/forskrift-2020-10-01-2027.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-01-2027) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-01-2027.md) |
| [Delegering av Justis- og beredskapsdepartementets myndighet etter lov 17. juni 2](../forskrifter/forskrift-2019-03-07-193.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-07-193) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-07-193.md) |
| [Delegering av Justis- og beredskapsdepartementets myndighet etter lov 22. mai 19](../forskrifter/forskrift-2019-03-07-190.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-07-190) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-07-190.md) |
| [Delegering av Justis- og beredskapsdepartementets myndighet etter lov 22. mai 19](../forskrifter/forskrift-2020-10-01-2026.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-01-2026) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-01-2026.md) |
| [Delegering av Justis- og beredskapsdepartementets myndighet etter lov 22. mai 19](../forskrifter/forskrift-2019-03-07-191.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-07-191) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-07-191.md) |
| [Delegering av Justis- og beredskapsdepartementets myndighet til å utøve statens ](../forskrifter/forskrift-2020-02-10-116.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-10-116) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-10-116.md) |
| [Delegering av Kongens forskriftskompetanse etter domstolloven § 163a og § 197a t](../forskrifter/forskrift-2012-02-03-119.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-02-03-119) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-02-03-119.md) |
| [Delegering av Kongens myndigheit til Kulturdepartementet og Kommunal- og moderni](../forskrifter/forskrift-2015-06-19-667.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-667) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-667.md) |
| [Delegering av Kongens myndighet etter advokatloven § 43 og § 53, lov 17. juni 20](../forskrifter/forskrift-2024-10-11-2460.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-11-2460) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-11-2460.md) |
| [Delegering av Kongens myndighet etter aksjeloven § 10-2 tredje ledd tredje punkt](../forskrifter/forskrift-2013-10-04-1179.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-10-04-1179) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-10-04-1179.md) |
| [Delegering av Kongens myndighet etter aksjeloven § 2-6 fjerde ledd, § 8-10 femte](../forskrifter/forskrift-2013-06-14-636.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-14-636) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-14-636.md) |
| [Delegering av Kongens myndighet etter finansavtaleloven](../forskrifter/forskrift-2022-09-02-1529.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-02-1529) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-02-1529.md) |
| [Delegering av Kongens myndighet etter forvaltningsloven § 13g til Justis- og ber](../forskrifter/forskrift-2025-05-15-804.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-15-804) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-15-804.md) |
| [Delegering av Kongens myndighet etter lov 10. februar 1967 (forvaltningsloven) §](../forskrifter/forskrift-2024-11-15-2785.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-15-2785) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-15-2785.md) |
| [Delegering av Kongens myndighet etter lov 13. august 1915 nr. 5 om domstolene (d](../forskrifter/forskrift-2024-01-26-114.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-26-114) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-26-114.md) |
| [Delegering av Kongens myndighet etter lov 13. august 1915 nr. 5 om domstolene § ](../forskrifter/forskrift-2023-11-17-1856.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-17-1856) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-17-1856.md) |
| [Delegering av Kongens myndighet etter lov 16. juli 1999 nr. 66 om Schengen infor](../forskrifter/forskrift-2020-12-11-2706.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2706) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2706.md) |
| [Delegering av Kongens myndighet etter lov 17. juli 1925 nr. 11 om Svalbard § 5 f](../forskrifter/forskrift-2023-11-10-1816.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-10-1816) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-10-1816.md) |
| [Delegering av Kongens myndighet etter lov 17. juni 2022 nr. 57 om erstatning fra](../forskrifter/forskrift-2023-09-01-1386.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-01-1386) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-01-1386.md) |
| [Delegering av Kongens myndighet etter lov 18. mai 2001 nr. 21 om gjennomføring a](../forskrifter/forskrift-2024-05-24-825.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-24-825) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-24-825.md) |
| [Delegering av Kongens myndighet etter lov 20. april 2018 nr. 4 om grensetilsyn o](../forskrifter/forskrift-2020-12-11-2705.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2705) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2705.md) |
| [Delegering av Kongens myndighet etter lov 20. april 2018 nr. 7 om våpen, skytevå](../forskrifter/forskrift-2020-12-11-2704.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2704) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2704.md) |
| [Delegering av Kongens myndighet etter lov 20. juli 1991 nr. 67 om overføring av ](../forskrifter/forskrift-2020-06-23-1284.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-23-1284) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-23-1284.md) |
| [Delegering av Kongens myndighet etter lov 22. mai 1981 nr. 25 om rettergangsmåte](../forskrifter/forskrift-2022-09-02-1530.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-02-1530) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-02-1530.md) |
| [Delegering av Kongens myndighet etter lov 22. mai 1981 nr. 25 om rettergangsmåte](../forskrifter/forskrift-2026-01-23-77.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-23-77) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-23-77.md) |
| [Delegering av Kongens myndighet etter lov 24. juni 1994 nr. 39 om sjøfarten § 46](../forskrifter/forskrift-2023-11-03-1767.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-03-1767) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-03-1767.md) |
| [Delegering av Kongens myndighet etter lov 26. april 2002 nr. 12 om notarius publ](../forskrifter/forskrift-2022-01-07-26.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-07-26) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-07-26.md) |
| [Delegering av Kongens myndighet etter lov 26. juni 1998 nr. 47 om fritids- og sm](../forskrifter/forskrift-2020-12-11-2707.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2707) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2707.md) |
| [Delegering av Kongens myndighet etter lov 29. mai 1953 nr. 3 om hittegods § 3 sj](../forskrifter/forskrift-2023-05-11-684.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-05-11-684) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-05-11-684.md) |
| [Delegering av Kongens myndighet etter lov 4. august 1995 nr. 53 om politiet § 17](../forskrifter/forskrift-2020-12-11-2708.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2708) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2708.md) |
| [Delegering av Kongens myndighet etter midlertidig lov om innreiserestriksjoner f](../forskrifter/forskrift-2020-06-19-1244.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-19-1244) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-19-1244.md) |
| [Delegering av Kongens myndighet etter passloven § 1, § 2, § 8 og § 12 og ID-kort](../forskrifter/forskrift-2020-10-09-2009.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-09-2009) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-09-2009.md) |
| [Delegering av Kongens myndighet etter patentloven § 68 og § 69, designloven § 52](../forskrifter/forskrift-2019-06-21-799.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-21-799) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-21-799.md) |
| [Delegering av Kongens myndighet etter politiloven § 16 annet ledd](../forskrifter/forskrift-2016-02-05-102.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-05-102) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-05-102.md) |
| [Delegering av Kongens myndighet etter politiloven § 17 første ledd](../forskrifter/forskrift-2017-09-01-1350.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-01-1350) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-01-1350.md) |
| [Delegering av Kongens myndighet etter rekonstruksjonsloven § 61 tredje ledd og o](../forskrifter/forskrift-2020-05-07-948.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-05-07-948) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-05-07-948.md) |
| [Delegering av Kongens myndighet etter sivilbeskyttelsesloven § 2 til å gi bestem](../forskrifter/forskrift-2022-05-20-875.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-20-875) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-20-875.md) |
| [Delegering av Kongens myndighet etter straffeloven § 38 til Justis- og beredskap](../forskrifter/forskrift-2016-02-12-153.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-12-153) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-12-153.md) |
| [Delegering av Kongens myndighet etter straffeloven § 38 til Justis- og beredskap](../forskrifter/forskrift-2017-10-20-1651.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-20-1651) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-20-1651.md) |
| [Delegering av Kongens myndighet etter straffeprosessloven § 142a og ny § 165a ti](../forskrifter/forskrift-2020-09-21-1789.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-09-21-1789) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-09-21-1789.md) |
| [Delegering av Kongens myndighet etter straffeprosessloven § 184b tredje ledd til](../forskrifter/forskrift-2025-05-15-803.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-15-803) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-15-803.md) |
| [Delegering av Kongens myndighet etter voldserstatningsloven](../forskrifter/forskrift-2022-06-17-1050.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-17-1050) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-17-1050.md) |
| [Delegering av Kongens myndighet til å unnlate å gjøre gjeldende innsigelse om at](../forskrifter/forskrift-2017-03-03-287.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-03-03-287) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-03-03-287.md) |
| [Delegering av Politidirektoratets myndighet til å utøve statens partsstilling et](../forskrifter/forskrift-2022-03-25-468.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-25-468) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-25-468.md) |
| [Delegering av avgjørelsesmyndighet i enkeltsaker etter lov 20. juli 1991 nr. 67 ](../forskrifter/forskrift-2013-11-25-1413.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-25-1413) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-25-1413.md) |
| [Delegering av avgjørelsesmyndighet i enkeltsaker etter lov om fullbyrding av nor](../forskrifter/forskrift-2004-07-21-1132.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-07-21-1132) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-07-21-1132.md) |
| [Delegering av departementets myndighet til Direktoratet for samfunnssikkerhet og](../forskrifter/forskrift-2025-11-15-2281.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-15-2281) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-15-2281.md) |
| [Delegering av departementets myndighet til Direktoratet for samfunnssikkerhet og](../forskrifter/forskrift-2024-05-22-806.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-22-806) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-22-806.md) |
| [Delegering av departementets myndighet til Direktoratet for samfunnssikkerhet og](../forskrifter/forskrift-2024-05-22-807.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-22-807) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-22-807.md) |
| [Delegering av departementets myndighet til å gi forskrift etter lov 14. juni 200](../forskrifter/forskrift-2023-01-27-101.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-27-101) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-27-101.md) |
| [Delegering av departementets myndighet til å gi forskrifter etter lov om kommuna](../forskrifter/forskrift-2010-06-25-943.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-25-943) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-25-943.md) |
| [Delegering av forskriftsmyndighet til Direktoratet for samfunnssikkerhet og bere](../forskrifter/forskrift-2015-06-01-580.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-01-580) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-01-580.md) |
| [Delegering av kompetanse etter straffeprosessloven til å samtykke til fritak for](../forskrifter/forskrift-2021-03-29-1042.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-29-1042) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-29-1042.md) |
| [Delegering av kompetanse til Justis- og politidepartementet til å kunne forlenge](../forskrifter/forskrift-2008-12-12-1343.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-12-1343) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-12-1343.md) |
| [Delegering av kompetanse til Justissekretariatene til stadfestelse av testament ](../forskrifter/forskrift-2006-12-21-1524.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-21-1524) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-21-1524.md) |
| [Delegering av kompetanse til å gi forskrifter etter utlendingsloven](../forskrifter/forskrift-2009-10-09-1260.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-10-09-1260) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-10-09-1260.md) |
| [Delegering av kompetanse til å samtykke til fritak for taushetsplikt i saker på ](../forskrifter/forskrift-2019-06-18-1118.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-18-1118) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-18-1118.md) |
| [Delegering av mynde etter forbrukarkjøpslova § 61a andre ledd.](../forskrifter/forskrift-2007-03-30-377.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-03-30-377) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-03-30-377.md) |
| [Delegering av mynde etter samvirkelova](../forskrifter/forskrift-2007-11-23-1288.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-11-23-1288) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-11-23-1288.md) |
| [Delegering av mynde til Justis- og politidepartementet etter inkassoloven § 22.](../forskrifter/forskrift-2003-03-07-286.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-03-07-286) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-03-07-286.md) |
| [Delegering av myndigheit etter arveloven § 41, § 55 og § 72 til Justis- og bered](../forskrifter/forskrift-2020-02-28-201.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-28-201) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-28-201.md) |
| [Delegering av myndigheit etter forsinkelsesrenteloven § 3a andre ledd til Finans](../forskrifter/forskrift-2013-02-15-174.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-02-15-174) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-02-15-174.md) |
| [Delegering av myndigheit etter lov 27. mai 2016 nr. 16 om endringar i sjøloven (](../forskrifter/forskrift-2016-05-27-535.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-05-27-535) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-05-27-535.md) |
| [Delegering av myndigheit etter sjøloven § 418a andre og tredje ledd, § 418b fjer](../forskrifter/forskrift-2016-05-27-534.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-05-27-534) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-05-27-534.md) |
| [Delegering av myndighet etter Svalbardloven § 4 til Justis- og beredskapsdeparte](../forskrifter/forskrift-2020-06-19-1290.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-19-1290) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-19-1290.md) |
| [Delegering av myndighet etter barneloven § 10.](../forskrifter/forskrift-1994-10-14-930.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-10-14-930) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-10-14-930.md) |
| [Delegering av myndighet etter forskrift om lokalstyrevalg i Longyearbyen § 13-1](../forskrifter/forskrift-2015-03-20-841.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-03-20-841) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-03-20-841.md) |
| [Delegering av myndighet etter forvaltningsloven § 13d første ledd til Domstoladm](../forskrifter/forskrift-2026-03-03-333.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-03-333) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-03-333.md) |
| [Delegering av myndighet etter forvaltningsloven § 13d første ledd til Sekretaria](../forskrifter/forskrift-2023-10-11-1609.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-11-1609) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-11-1609.md) |
| [Delegering av myndighet etter lov 13. juni 1997 nr. 44 om aksjeselskaper (aksjel](../forskrifter/forskrift-1998-07-17-619.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-07-17-619) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-07-17-619.md) |
| [Delegering av myndighet etter lov 15. juni 1990 nr. 27 om vern av kretsmønstre f](../forskrifter/forskrift-1993-12-17-1142.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-12-17-1142) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-12-17-1142.md) |
| [Delegering av myndighet etter lov 26. juni 1992 nr. 86 om tvangsfullbyrdelse og ](../forskrifter/forskrift-1992-12-18-1076.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-18-1076) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-18-1076.md) |
| [Delegering av myndighet etter lov av 26. juni 1998 nr. 47 om fritids- og småbåte](../forskrifter/forskrift-1998-11-27-1095.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-11-27-1095) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-11-27-1095.md) |
| [Delegering av myndighet etter lov av 4. juli 1991 nr. 47 om ekteskap § 70 annet ](../forskrifter/forskrift-1992-12-18-1077.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-18-1077) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-18-1077.md) |
| [Delegering av myndighet etter lov om tekniske kontrollorgan](../forskrifter/forskrift-2018-04-25-633.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-04-25-633) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-04-25-633.md) |
| [Delegering av myndighet etter lov om vergemål (vergemålsloven)](../forskrifter/forskrift-2012-10-26-999.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-26-999) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-26-999.md) |
| [Delegering av myndighet etter overføringsloven § 13 om soningsoverføring av domf](../forskrifter/forskrift-2024-09-20-2261.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-20-2261) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-20-2261.md) |
| [Delegering av myndighet etter politiloven](../forskrifter/forskrift-2017-09-14-2483.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-14-2483) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-14-2483.md) |
| [Delegering av myndighet etter politiloven § 20](../forskrifter/forskrift-2021-11-04-4011.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-04-4011) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-04-4011.md) |
| [Delegering av myndighet etter politiloven § 20 tredje ledd](../forskrifter/forskrift-2023-10-26-1703.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-26-1703) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-26-1703.md) |
| [Delegering av myndighet etter sjøloven § 202 tredje ledd til Nærings- og fiskeri](../forskrifter/forskrift-2015-12-18-1580.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-18-1580) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-18-1580.md) |
| [Delegering av myndighet etter skifteloven § 65 tredje ledd.](../forskrifter/forskrift-1993-12-10-1120.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-12-10-1120) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-12-10-1120.md) |
| [Delegering av myndighet etter tomtefesteloven](../forskrifter/forskrift-1988-05-20-361.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-05-20-361) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-05-20-361.md) |
| [Delegering av myndighet etter tvangsfullbyrdelsesloven og dekningsloven som følg](../forskrifter/forskrift-2025-06-20-1130.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1130) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1130.md) |
| [Delegering av myndighet etter tvangsfullbyrdelsesloven § 11-56 første ledd annet](../forskrifter/forskrift-1992-12-04-883.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-883) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-883.md) |
| [Delegering av myndighet etter tvangsfullbyrdelsesloven § 13-8 femte ledd.](../forskrifter/forskrift-1993-06-11-524.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-06-11-524) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-06-11-524.md) |
| [Delegering av myndighet etter tvangsfullbyrdelsesloven § 7-3](../forskrifter/forskrift-2025-10-08-2002.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-08-2002) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-08-2002.md) |
| [Delegering av myndighet etter tvisteloven til å samtykke til fritak for taushets](../forskrifter/forskrift-2021-03-29-1043.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-29-1043) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-29-1043.md) |
| [Delegering av myndighet etter tvisteloven § 2-5](../forskrifter/forskrift-2020-02-14-3387.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-14-3387) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-14-3387.md) |
| [Delegering av myndighet etter vergemålsloven § 51 og § 54 og finansavtaleloven §](../forskrifter/forskrift-2013-04-05-339.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-04-05-339) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-04-05-339.md) |
| [Delegering av myndighet etter voldsoffererstatningsloven § 14 sjette ledd](../forskrifter/forskrift-2012-03-30-264.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-03-30-264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-03-30-264.md) |
| [Delegering av myndighet etter § 3-4 tredje ledd i lov 23. desember 1988 nr. 104 ](../forskrifter/forskrift-1994-07-01-535.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-07-01-535) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-07-01-535.md) |
| [Delegering av myndighet for Justisdepartementet til å bestemme hvem som skal utf](../forskrifter/forskrift-1965-12-10-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1965-12-10-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1965-12-10-2.md) |
| [Delegering av myndighet fra Justis- og beredskapsdepartementet til Politidirekto](../forskrifter/forskrift-2022-03-09-383.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-09-383) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-09-383.md) |
| [Delegering av myndighet som eksamensadministrator for sikkerhetsrådgivere etter ](../forskrifter/forskrift-2010-03-02-353.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-03-02-353) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-03-02-353.md) |
| [Delegering av myndighet til Arbeids- og administrasjonsdepartementet etter lov o](../forskrifter/forskrift-2002-10-18-1131.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-10-18-1131) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-10-18-1131.md) |
| [Delegering av myndighet til Arbeids- og administrasjonsdepartementet etter lov o](../forskrifter/forskrift-2003-04-30-518.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-04-30-518) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-04-30-518.md) |
| [Delegering av myndighet til Arbeids- og inkluderingsdepartementet etter allmenna](../forskrifter/forskrift-2007-12-21-1578.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1578) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1578.md) |
| [Delegering av myndighet til Barne- og familiedepartementet etter bustadoppføring](../forskrifter/forskrift-1997-10-03-1073.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-10-03-1073) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-10-03-1073.md) |
| [Delegering av myndighet til Direktoratet for brann- og eksplosjonsvern etter for](../forskrifter/forskrift-1997-03-05-239.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-05-239) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-05-239.md) |
| [Delegering av myndighet til Direktoratet for brann- og eksplosjonsvern etter lov](../forskrifter/forskrift-1996-08-20-811.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-08-20-811) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-08-20-811.md) |
| [Delegering av myndighet til Direktoratet for brann- og eksplosjonsvern til å fas](../forskrifter/forskrift-2001-05-08-471.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-05-08-471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-05-08-471.md) |
| [Delegering av myndighet til Direktoratet for brann- og elsikkerhet etter lov om ](../forskrifter/forskrift-2003-06-26-868.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-26-868) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-26-868.md) |
| [Delegering av myndighet til Direktoratet for samfunnssikkerhet og beredskap ette](../forskrifter/forskrift-2003-09-12-1135.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-12-1135) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-12-1135.md) |
| [Delegering av myndighet til Direktoratet for samfunnssikkerhet og beredskap ette](../forskrifter/forskrift-2023-03-23-426.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-03-23-426) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-03-23-426.md) |
| [Delegering av myndighet til Direktoratet for samfunnssikkerhet og beredskap ette](../forskrifter/forskrift-2022-05-20-876.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-20-876) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-20-876.md) |
| [Delegering av myndighet til Direktoratet for samfunnssikkerhet og beredskap ette](../forskrifter/forskrift-2007-06-29-737.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-737) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-737.md) |
| [Delegering av myndighet til Direktoratet for samfunnssikkerhet og beredskap ette](../forskrifter/forskrift-2003-09-01-1161.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-01-1161) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-01-1161.md) |
| [Delegering av myndighet til Direktoratet for samfunnssikkerhet og beredskap ette](../forskrifter/forskrift-2012-12-13-1262.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-13-1262) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-13-1262.md) |
| [Delegering av myndighet til Finans- og tolldepartementet etter lov om naturskade](../forskrifter/forskrift-1997-11-28-1245.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-11-28-1245) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-11-28-1245.md) |
| [Delegering av myndighet til Finansdepartementet etter aksjeloven § 2-8 annet led](../forskrifter/forskrift-2002-01-25-66.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-01-25-66) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-01-25-66.md) |
| [Delegering av myndighet til Finansdepartementet etter lov om renter ved forsinke](../forskrifter/forskrift-2003-12-12-1509.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-12-1509) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-12-1509.md) |
| [Delegering av myndighet til Justis- og beredskapsdepartementet etter lov 20. apr](../forskrifter/forskrift-2012-05-25-463.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-25-463) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-25-463.md) |
| [Delegering av myndighet til Justis- og beredskapsdepartementet etter straffepros](../forskrifter/forskrift-2015-09-04-1031.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-04-1031) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-04-1031.md) |
| [Delegering av myndighet til Justis- og beredskapsdepartementet etter straffepros](../forskrifter/forskrift-2016-09-30-1138.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-30-1138) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-30-1138.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter allmennaksjelov](../forskrifter/forskrift-2009-06-26-877.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-26-877) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-26-877.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter lov av 12. sept](../forskrifter/forskrift-2003-09-12-1137.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-12-1137) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-12-1137.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter lov av 18. febr](../forskrifter/forskrift-1999-06-04-569.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-06-04-569) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-06-04-569.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter lov om heleide ](../forskrifter/forskrift-2004-06-11-836.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-11-836) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-11-836.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter lov om kommunal](../forskrifter/forskrift-2009-06-26-879.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-26-879) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-26-879.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter lov om skytevåp](../forskrifter/forskrift-1998-06-05-572.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-06-05-572) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-06-05-572.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter lov om tilsyn m](../forskrifter/forskrift-2007-06-29-736.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-736) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-736.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter navneloven § 15](../forskrifter/forskrift-2002-06-07-527.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-07-527) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-07-527.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter passloven.](../forskrifter/forskrift-1997-06-19-615.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-06-19-615) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-06-19-615.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter straffeloven § ](../forskrifter/forskrift-2004-03-05-480.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-03-05-480) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-03-05-480.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter straffeloven § ](../forskrifter/forskrift-2005-12-16-1519.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1519) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1519.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter straffeprosessl](../forskrifter/forskrift-2010-03-19-409.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-03-19-409) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-03-19-409.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter straffeprosessl](../forskrifter/forskrift-2004-12-17-1668.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-17-1668) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-17-1668.md) |
| [Delegering av myndighet til Justis- og politidepartementet og Arbeids- og inklud](../forskrifter/forskrift-2006-06-30-779.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-779) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-779.md) |
| [Delegering av myndighet til Justis- og politidepartementet og Arbeids- og sosial](../forskrifter/forskrift-2004-11-19-1490.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-11-19-1490) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-11-19-1490.md) |
| [Delegering av myndighet til Justis- og politidepartementet til å gi overgangsbes](../forskrifter/forskrift-2006-06-16-628.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-16-628) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-16-628.md) |
| [Delegering av myndighet til Justis- og politidepartementet, Finansdepartementet ](../forskrifter/forskrift-2005-04-01-270.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-04-01-270) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-04-01-270.md) |
| [Delegering av myndighet til Justisdepartementet etter endringslov til utlendings](../forskrifter/forskrift-2000-07-28-794.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-07-28-794) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-07-28-794.md) |
| [Delegering av myndighet til Justisdepartementet etter vegtrafikkloven – bøtelegg](../forskrifter/forskrift-1990-06-08-443.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-06-08-443) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-06-08-443.md) |
| [Delegering av myndighet til Kriminalomsorgsdirektoratet etter forvaltningslovens](../forskrifter/forskrift-2023-03-23-425.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-03-23-425) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-03-23-425.md) |
| [Delegering av myndighet til Longyearbyen lokalstyre etter forskrift om alkoholor](../forskrifter/forskrift-2001-12-12-1406.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-12-1406) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-12-1406.md) |
| [Delegering av myndighet til Longyearbyen lokalstyre etter lov om Svalbard § 4.](../forskrifter/forskrift-2002-10-07-1145.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-10-07-1145) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-10-07-1145.md) |
| [Delegering av myndighet til Miljøverndepartementet etter lov om fritids- og småb](../forskrifter/forskrift-2007-06-29-848.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-848) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-848.md) |
| [Delegering av myndighet til Nordisk Emballasje Testing (NET) vedrørende kontroll](../forskrifter/forskrift-2007-01-03-238.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-01-03-238) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-01-03-238.md) |
| [Delegering av myndighet til Nærings- og handelsdepartementet etter aksjeloven § ](../forskrifter/forskrift-2007-02-09-155.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-02-09-155) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-02-09-155.md) |
| [Delegering av myndighet til Nærings- og handelsdepartementet etter sjøloven § 47](../forskrifter/forskrift-2008-01-11-29.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-01-11-29) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-01-11-29.md) |
| [Delegering av myndighet til Politidirektoratet etter forvaltningsloven § 13d før](../forskrifter/forskrift-2003-01-14-81.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-14-81) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-14-81.md) |
| [Delegering av myndighet til Politidirektoratet etter lov om Schengen informasjon](../forskrifter/forskrift-2005-12-21-1765.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-21-1765) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-21-1765.md) |
| [Delegering av myndighet til Politidirektoratet etter lov om hittegods § 11 annet](../forskrifter/forskrift-2000-11-16-1149.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-16-1149) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-16-1149.md) |
| [Delegering av myndighet til Politidirektoratet etter lov om lensmenn § 4 tredje ](../forskrifter/forskrift-2000-11-16-1152.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-16-1152) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-16-1152.md) |
| [Delegering av myndighet til Politidirektoratet etter lov om strafferegistrering ](../forskrifter/forskrift-2000-11-16-1153.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-16-1153) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-16-1153.md) |
| [Delegering av myndighet til Politidirektoratet etter passloven § 2 tredje ledd.](../forskrifter/forskrift-2000-11-16-1148.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-16-1148) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-16-1148.md) |
| [Delegering av myndighet til Politidirektoratet etter politiinstruksen § 3-2 tred](../forskrifter/forskrift-2000-11-16-1154.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-16-1154) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-16-1154.md) |
| [Delegering av myndighet til Politidirektoratet etter politiloven § 14, § 16 tred](../forskrifter/forskrift-2000-11-16-1151.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-16-1151) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-16-1151.md) |
| [Delegering av myndighet til Politidirektoratet etter politiloven § 20 sjette led](../forskrifter/forskrift-2015-05-20-522.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-20-522) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-20-522.md) |
| [Delegering av myndighet til Politidirektoratet etter politiloven § 24c femte led](../forskrifter/forskrift-2019-11-25-1866.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-25-1866) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-25-1866.md) |
| [Delegering av myndighet til Politidirektoratet etter vegtrafikkloven § 39 annet ](../forskrifter/forskrift-2000-11-16-1150.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-16-1150) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-16-1150.md) |
| [Delegering av myndighet til Politidirektoratet til å fastsette at søknader om gj](../forskrifter/forskrift-2014-11-04-1430.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-04-1430) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-04-1430.md) |
| [Delegering av myndighet til Samferdselsdepartementet etter lov om kontroll med p](../forskrifter/forskrift-2016-06-17-698.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-17-698) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-17-698.md) |
| [Delegering av myndighet til Samferdselsdepartementet etter luftfartsloven § 10-3](../forskrifter/forskrift-2004-06-25-989.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-25-989) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-25-989.md) |
| [Delegering av myndighet til Statens sivilrettsforvaltning etter forvaltningslove](../forskrifter/forskrift-2023-03-23-424.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-03-23-424) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-03-23-424.md) |
| [Delegering av myndighet til Utlendingsdirektoratet etter forvaltningsloven § 13d](../forskrifter/forskrift-2011-12-08-1238.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-08-1238) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-08-1238.md) |
| [Delegering av myndighet til Utlendingsdirektoratet etter utlendingsforskriften](../forskrifter/forskrift-2009-12-16-1586.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-16-1586) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-16-1586.md) |
| [Delegering av myndighet til domstolene etter domstolloven § 48.](../forskrifter/forskrift-2006-06-30-872.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-872) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-872.md) |
| [Delegering av myndighet til å ettergi erstatningskrav, sakskostnader og inndragn](../forskrifter/forskrift-2010-09-03-1244.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-09-03-1244) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-09-03-1244.md) |
| [Delegering av myndighet til å fastsette endringer i politiets lokale struktur](../forskrifter/forskrift-2016-02-18-1905.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-18-1905) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-18-1905.md) |
| [Delegering av myndighet til å gi godkjenning etter finansavtaleloven § 4 annet l](../forskrifter/forskrift-2000-05-19-441.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-05-19-441) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-05-19-441.md) |
| [Delegering av myndighet til å gi tillatelse til midlertidig oppbevaring av brann](../forskrifter/forskrift-1998-01-19-38.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-01-19-38) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-01-19-38.md) |
| [Delegering av myndighet til å gi tillatelse til midlertidig oppbevaring av brann](../forskrifter/forskrift-1998-05-29-564.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-05-29-564) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-05-29-564.md) |
| [Delegering av myndighet til å godkjenne og kontrollere fyrverkeri etter brann- o](../forskrifter/forskrift-2003-12-19-1847.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-19-1847) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-19-1847.md) |
| [Delegering av myndighet til å samtykke til å føre hemmelig bevis i sikkerhetssak](../forskrifter/forskrift-2025-10-17-2055.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-17-2055) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-17-2055.md) |
| [Delegering av myndighet til å tildele vedtakskompetanse](../forskrifter/forskrift-2020-07-01-1489.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-01-1489) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-01-1489.md) |
| [Delegering av myndighet til å utpeke namsmann i saker der skyldneren har adresse](../forskrifter/forskrift-2019-09-23-1223.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-23-1223) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-23-1223.md) |
| [Delegering av myndighet – utpeking av namsmyndighet etter tvangsfullbyrdelseslov](../forskrifter/forskrift-2025-11-12-3047.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-12-3047) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-12-3047.md) |
| [Delegering av politimyndighet etter politiloven § 20 annet ledd](../forskrifter/forskrift-2024-06-03-936.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-03-936) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-03-936.md) |
| [Delegering til Justis- og politidepartementet av Kongens myndighet til å gi fors](../forskrifter/forskrift-2008-05-09-448.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-09-448) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-09-448.md) |
| [Delt ikraftsetting av lov 21. juni 2019 nr. 48 om endringer i straffeloven og st](../forskrifter/forskrift-2020-09-21-1788.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-09-21-1788) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-09-21-1788.md) |
| [Delvis ikraftsetjing av lov 21. desember 2005 nr. 131 om oppheving av lausgjenga](../forskrifter/forskrift-2005-12-21-1580.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-21-1580) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-21-1580.md) |
| [Delvis ikraftsetting av lov 17. juni 2005 nr. 89 om endringar i lov 26. juni 199](../forskrifter/forskrift-2008-02-15-136.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-02-15-136) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-02-15-136.md) |
| [Delvis ikraftsetting av lov 17. juni 2016 nr. 58 om endringer i utlendingsloven ](../forskrifter/forskrift-2016-08-26-1005.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-08-26-1005) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-08-26-1005.md) |
| [Delvis ikrafttredelse av lov 11. juni 1993 nr. 83 om endringer i rettergangslovg](../forskrifter/forskrift-1993-11-19-1034.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-11-19-1034) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-11-19-1034.md) |
| [Delvis ikrafttredelse av lov 11. juni 1993 nr. 83 om endringer i rettergangslovg](../forskrifter/forskrift-1993-07-23-764.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-07-23-764) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-07-23-764.md) |
| [Delvis ikrafttredelse av lov 15. mars 1991 nr. 3 om megling i konfliktråd og lov](../forskrifter/forskrift-1992-08-13-619.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-08-13-619) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-08-13-619.md) |
| [Delvis ikrafttredelse av lov 2. august 1996 nr. 61 om endringer i sjøloven mm (b](../forskrifter/forskrift-1996-08-02-744.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-08-02-744) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-08-02-744.md) |
| [Delvis ikrafttredelse av lov 22. desember 1995 nr. 82 om endringer i lovgivninge](../forskrifter/forskrift-1996-03-29-307.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-03-29-307) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-03-29-307.md) |
| [Delvis ikrafttredelse av lov 22. desember 1995 nr. 82 om endringer i lovgivninge](../forskrifter/forskrift-1996-12-20-1153.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-12-20-1153) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-12-20-1153.md) |
| [Delvis ikrafttredelse av lov av 14. juni 2002 nr. 20 om vern mot brann, eksplosj](../forskrifter/forskrift-2002-06-14-536.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-14-536) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-14-536.md) |
| [Delvis ikrafttredelse av lov av 18. mai 2001 nr. 21 om gjennomføring av straff m](../forskrifter/forskrift-2002-02-22-181.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-02-22-181) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-02-22-181.md) |
| [Delvis ikrafttredelse av lov av 2. august 1996 nr. 61 om endringer i sjøloven m.](../forskrifter/forskrift-1997-09-05-958.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-09-05-958) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-09-05-958.md) |
| [Delvis ikrafttredelse av lov av 23. desember 1988 nr. 104 om produktansvar. Dele](../forskrifter/forskrift-1988-12-23-1065.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-12-23-1065) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-12-23-1065.md) |
| [Endringer i distriktsinndelingen mv. i politi- og lensmannsetaten](../forskrifter/forskrift-2015-11-20-1331.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-11-20-1331) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-11-20-1331.md) |
| [Fastsettelse av Sivilt beredskapssystem (SBS) og delegering av fullmakter](../forskrifter/forskrift-2025-09-12-1841.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-12-1841) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-12-1841.md) |
| [Fastsetting av undersøkelsesmyndighet etter sjøloven § 473](../forskrifter/forskrift-2008-01-11-30.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-01-11-30) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-01-11-30.md) |
| [Fordeling av myndigheit etter lov 14. juni 2019 nr. 21 om arv og dødsboskifte](../forskrifter/forskrift-2020-02-28-202.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-28-202) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-28-202.md) |
| [Forskrift (disiplinærregler) for tjenestepliktige etter lov om fritaking for mil](../forskrifter/forskrift-1968-02-01-3641.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1968-02-01-3641) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1968-02-01-3641.md) |
| [Forskrift etter rettsgebyrloven m.m. (rettsgebyrforskriften)](../forskrifter/forskrift-1983-02-15-86.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-02-15-86) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-02-15-86.md) |
| [Forskrift for bruk av skytevåpen i Longyearbyen og omegn, Pyramiden, Barentsburg](../forskrifter/forskrift-1966-02-11-3449.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-02-11-3449) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-02-11-3449.md) |
| [Forskrift for oppnevnelse av stedfortredere for en del embets- og tjenestemenn v](../forskrifter/forskrift-1954-07-08-3.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1954-07-08-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1954-07-08-3.md) |
| [Forskrift om Bouvet-øya.](../forskrifter/forskrift-1930-09-19-3663.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1930-09-19-3663) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1930-09-19-3663.md) |
| [Forskrift om Den rettsmedisinske kommisjon](../forskrifter/forskrift-2018-02-13-240.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-02-13-240) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-02-13-240.md) |
| [Forskrift om Finnmarkskommisjonen og Utmarksdomstolen for Finnmark](../forskrifter/forskrift-2007-03-16-277.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-03-16-277) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-03-16-277.md) |
| [Forskrift om Lovdatas lov- og forskriftsdatabaser.](../forskrifter/forskrift-1994-06-21-644.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-06-21-644) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-06-21-644.md) |
| [Forskrift om Politiets utlendingsinternat (Utlendingsinternatforskriften)](../forskrifter/forskrift-2009-12-23-1890.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-23-1890) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-23-1890.md) |
| [Forskrift om Politihøgskolens styre, oppgaver og virksomhet.](../forskrifter/forskrift-2005-11-25-1330.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-25-1330) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-25-1330.md) |
| [Forskrift om Schengen informasjonssystem (SIS-forskriften)](../forskrifter/forskrift-2022-06-26-1194.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-26-1194) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-26-1194.md) |
| [Forskrift om York–Antwerpen-reglene 2016 som fravikelige regler for felleshavari](../forskrifter/forskrift-2018-06-01-785.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-01-785) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-01-785.md) |
| [Forskrift om administrasjon av Jan Mayen](../forskrifter/forskrift-1980-11-21-12.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-11-21-12) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-11-21-12.md) |
| [Forskrift om administrativ tilhørighet for sysselmannen på Svalbard.](../forskrifter/forskrift-1953-03-20-3454.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1953-03-20-3454) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1953-03-20-3454.md) |
| [Forskrift om advokater og andre som yter rettslig bistand (advokatforskriften)](../forskrifter/forskrift-2024-10-22-2546.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-22-2546) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-22-2546.md) |
| [Forskrift om advokatlovens anvendelse for Svalbard](../forskrifter/forskrift-2024-10-11-2451.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-11-2451) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-11-2451.md) |
| [Forskrift om aerosolbeholdere](../forskrifter/forskrift-1996-03-01-229.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-03-01-229) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-03-01-229.md) |
| [Forskrift om antennelighet av madrasser og stoppede møbler.](../forskrifter/forskrift-1999-04-16-525.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-04-16-525) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-04-16-525.md) |
| [Forskrift om anvendelse av lov 15. desember 1950 nr. 7 om særlige rådgjerder und](../forskrifter/forskrift-2023-12-01-1943.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-01-1943) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-01-1943.md) |
| [Forskrift om anvendelse av straffeloven § 155 på lovbrudd mot annet lands offent](../forskrifter/forskrift-1997-10-03-1077.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-10-03-1077) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-10-03-1077.md) |
| [Forskrift om aspiranter i kriminalomsorgen](../forskrifter/forskrift-2025-04-05-619.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-05-619) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-05-619.md) |
| [Forskrift om at passlovens § 6 annet ledd og § 6a også skal omfatte diplomatpass](../forskrifter/forskrift-2005-09-30-1113.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-09-30-1113) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-09-30-1113.md) |
| [Forskrift om autorisasjon av verksteder for reparasjon/ombygging m.v. av eksplos](../forskrifter/forskrift-1987-11-20-1080.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-11-20-1080) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-11-20-1080.md) |
| [Forskrift om avgift på enkelte farlige stoffer, anlegg og innretninger som omfat](../forskrifter/forskrift-1995-07-10-684.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-07-10-684) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-07-10-684.md) |
| [Forskrift om avhør av barn og andre særlig sårbare fornærmede og vitner (tilrett](../forskrifter/forskrift-2015-09-24-1098.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-24-1098) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-24-1098.md) |
| [Forskrift om barnesikring av lightere og om forbud mot lightere med forvekslings](../forskrifter/forskrift-2007-06-21-687.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-21-687) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-21-687.md) |
| [Forskrift om behandling av opplysninger i politiet og påtalemyndigheten (politir](../forskrifter/forskrift-2013-09-20-1097.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-09-20-1097) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-09-20-1097.md) |
| [Forskrift om behandling av opplysninger om natur- og vannskader i Kunnskapsbanke](../forskrifter/forskrift-2022-06-01-954.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-01-954) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-01-954.md) |
| [Forskrift om behandling av personopplysninger](../forskrifter/forskrift-2018-06-15-876.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-15-876) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-15-876.md) |
| [Forskrift om behandling av personopplysninger i kriminalomsorgen](../forskrifter/forskrift-2013-09-20-1099.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-09-20-1099) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-09-20-1099.md) |
| [Forskrift om behandling av saker om straff for personer mistenkt for piratvirkso](../forskrifter/forskrift-2013-06-14-622.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-14-622) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-14-622.md) |
| [Forskrift om behandling av straffesaker når norske skip deltar i en Frontex-oper](../forskrifter/forskrift-2015-06-05-582.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-05-582) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-05-582.md) |
| [Forskrift om bekreftelse av underskrift på eksigible gjeldsbrev.](../forskrifter/forskrift-1973-10-26-4.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1973-10-26-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1973-10-26-4.md) |
| [Forskrift om bekreftelse av underskrift på eksigible gjeldsbrev.](../forskrifter/forskrift-1992-12-04-896.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-896) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-896.md) |
| [Forskrift om bemyndigelse av funksjonærer etter tvangsfullbyrdelsesloven.](../forskrifter/forskrift-1992-12-04-893.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-893) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-893.md) |
| [Forskrift om bevisopptak i sivile saker i utlandet](../forskrifter/forskrift-1950-04-28-3419.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1950-04-28-3419) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1950-04-28-3419.md) |
| [Forskrift om bortvisning og utvisning av personer fra Svalbard](../forskrifter/forskrift-1995-02-03-96.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-02-03-96) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-02-03-96.md) |
| [Forskrift om bostyrerens sikkerhetsstillelse.](../forskrifter/forskrift-1985-09-20-1871.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-09-20-1871) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-09-20-1871.md) |
| [Forskrift om brannforebygging](../forskrifter/forskrift-2015-12-17-1710.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-17-1710) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-17-1710.md) |
| [Forskrift om brannvern på Svalbard.](../forskrifter/forskrift-1993-08-20-815.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-20-815) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-20-815.md) |
| [Forskrift om bruk av politiarrest](../forskrifter/forskrift-2006-06-30-749.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-749) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-749.md) |
| [Forskrift om bruk av sikringsmidler](../forskrifter/forskrift-1961-12-01-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1961-12-01-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1961-12-01-2.md) |
| [Forskrift om cybersikkerhetssertifisering](../forskrifter/forskrift-2026-06-23-1250.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-23-1250) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-23-1250.md) |
| [Forskrift om deklarering av kjemikalier til produktregisteret (deklareringsforsk](../forskrifter/forskrift-2015-05-19-541.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-19-541) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-19-541.md) |
| [Forskrift om delegasjon av myndighet til Justisdep. etter Grunnlovens § 20– søkn](../forskrifter/forskrift-1981-06-05-8703.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-06-05-8703) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-06-05-8703.md) |
| [Forskrift om delegering av myndighet etter straffeprosessloven §§ 78, 107 og 107](../forskrifter/forskrift-1985-12-13-2095.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-12-13-2095) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-12-13-2095.md) |
| [Forskrift om delegering av myndighet til Justisdepartementet til å gi salærinstr](../forskrifter/forskrift-1982-10-08-1445.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-10-08-1445) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-10-08-1445.md) |
| [Forskrift om delegering av myndighet til å gi regler om innretning av rettsbøker](../forskrifter/forskrift-1985-12-13-2094.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-12-13-2094) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-12-13-2094.md) |
| [Forskrift om deling av Høiesterett i to avdelinger.](../forskrifter/forskrift-1927-10-21-3216.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1927-10-21-3216) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1927-10-21-3216.md) |
| [Forskrift om deling av taushetsbelagte opplysninger og behandling av personopply](../forskrifter/forskrift-2022-06-17-1045.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-17-1045) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-17-1045.md) |
| [Forskrift om delvis ikrafttredelse av lov 8. feb. 1980 nr. 3 om endr. i lov 7. j](../forskrifter/forskrift-1980-11-21-6.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-11-21-6) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-11-21-6.md) |
| [Forskrift om den sentrale administrasjonsordning for Svalbard-saker og om oppret](../forskrifter/forskrift-1965-01-06-3451.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1965-01-06-3451) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1965-01-06-3451.md) |
| [Forskrift om det lokale elektrisitetstilsyn og sakkyndige som utfører oppgaver f](../forskrifter/forskrift-2007-06-29-830.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-830) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-830.md) |
| [Forskrift om digital sikkerhet (digitalsikkerhetsforskriften)](../forskrifter/forskrift-2025-06-20-1131.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1131) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1131.md) |
| [Forskrift om disiplinærreglement for politireserven.](../forskrifter/forskrift-1953-07-31-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1953-07-31-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1953-07-31-1.md) |
| [Forskrift om dispasjører](../forskrifter/forskrift-2024-02-03-172.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-03-172) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-03-172.md) |
| [Forskrift om dommeres sidegjøremål.](../forskrifter/forskrift-2002-10-18-1133.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-10-18-1133) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-10-18-1133.md) |
| [Forskrift om domsmyndighet på Svalbard](../forskrifter/forskrift-1985-03-08-532.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-03-08-532) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-03-08-532.md) |
| [Forskrift om driftsstøttetjenester til Nødnettutstyret ved brannvesenets nødalar](../forskrifter/forskrift-2012-06-14-530.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-14-530) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-14-530.md) |
| [Forskrift om eksamen ved fengselsbetjentutdanningen](../forskrifter/forskrift-2011-06-23-854.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-06-23-854) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-06-23-854.md) |
| [Forskrift om elektrisk utstyr](../forskrifter/forskrift-2017-10-10-1598.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-10-1598) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-10-1598.md) |
| [Forskrift om elektriske forsyningsanlegg.](../forskrifter/forskrift-2005-12-20-1626.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-20-1626) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-20-1626.md) |
| [Forskrift om elektriske lavspenningsanlegg](../forskrifter/forskrift-1998-11-06-1060.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-11-06-1060) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-11-06-1060.md) |
| [Forskrift om elektroforetak og kvalifikasjonskrav for arbeid knyttet til elektri](../forskrifter/forskrift-2013-06-19-739.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-19-739) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-19-739.md) |
| [Forskrift om elektromagnetisk kompatibilitet](../forskrifter/forskrift-2017-10-10-1597.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-10-1597) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-10-1597.md) |
| [Forskrift om elektronisk kommunikasjon med alminnelig namsmann og Innkrevingsmyn](../forskrifter/forskrift-2025-07-09-1509.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-09-1509) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-09-1509.md) |
| [Forskrift om elektronisk kommunikasjon med domstolene](../forskrifter/forskrift-2016-10-28-1258.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-28-1258) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-28-1258.md) |
| [Forskrift om en særskilt klagenemnd for behandling av klager over vedtak om erkj](../forskrifter/forskrift-1999-08-06-885.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-08-06-885) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-08-06-885.md) |
| [Forskrift om endring i forskrift om fastsetting av inndeling i lensmanns- og pol](../forskrifter/forskrift-2020-06-04-1135.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-04-1135) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-04-1135.md) |
| [Forskrift om endring i forskrift om fastsetting av inndeling i lensmanns- og pol](../forskrifter/forskrift-2021-06-02-1774.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-02-1774) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-02-1774.md) |
| [Forskrift om endring i forskrift om fastsetting av inndeling i lensmanns- og pol](../forskrifter/forskrift-2021-06-02-1789.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-02-1789) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-02-1789.md) |
| [Forskrift om endring i forskrift om håndtering av brannfarlig, reaksjonsfarlig o](../forskrifter/forskrift-2026-02-04-140.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-04-140) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-04-140.md) |
| [Forskrift om endring i rettsgebyrforskriften](../forskrifter/forskrift-2025-12-17-2649.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-17-2649) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-17-2649.md) |
| [Forskrift om endring i utlendingsforskriften (forenkling av fireårskravet og mel](../forskrifter/forskrift-2026-06-15-1087.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-15-1087) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-15-1087.md) |
| [Forskrift om endring i vareførselsforskriften](../forskrifter/forskrift-2026-08-21-1661.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-08-21-1661) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-08-21-1661.md) |
| [Forskrift om endringer i utlendingsforskriften (avvikling av au pair-ordningen)](../forskrifter/forskrift-2024-02-14-257.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-14-257) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-14-257.md) |
| [Forskrift om enkelte spørsmål knyttet til saksbehandlingen hos namsmannen](../forskrifter/forskrift-2025-07-09-1510.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-09-1510) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-09-1510.md) |
| [Forskrift om enkle trykkbeholdere](../forskrifter/forskrift-2017-02-10-171.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-02-10-171) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-02-10-171.md) |
| [Forskrift om erstatning etter politiloven § 23a](../forskrifter/forskrift-2022-06-30-1279.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-30-1279) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-30-1279.md) |
| [Forskrift om erstatning ved atomulykker.](../forskrifter/forskrift-2001-12-14-1498.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-14-1498) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-14-1498.md) |
| [Forskrift om etablering av Direktoratet for brann og eksplosjonsvern og Statens ](../forskrifter/forskrift-1984-12-14-2044.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-12-14-2044) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-12-14-2044.md) |
| [Forskrift om farlige næringsmiddelimitasjoner.](../forskrifter/forskrift-1992-05-26-420.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-05-26-420) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-05-26-420.md) |
| [Forskrift om faste forsvarere og bistandsadvokater](../forskrifter/forskrift-2011-03-04-251.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-04-251) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-04-251.md) |
| [Forskrift om fastsettelse av utleggstrekk og fordeling av trekkbeløp](../forskrifter/forskrift-2025-07-09-1507.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-09-1507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-09-1507.md) |
| [Forskrift om fastsetting av inndeling i politistasjonsdistrikter og tjenestested](../forskrifter/forskrift-2017-05-24-2480.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-24-2480) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-24-2480.md) |
| [Forskrift om felles faste dommerstillinger](../forskrifter/forskrift-2015-09-28-1202.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-28-1202) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-28-1202.md) |
| [Forskrift om finansavtaler (finansavtaleforskriften)](../forskrifter/forskrift-2022-09-19-1612.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-19-1612) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-19-1612.md) |
| [Forskrift om fiske etter røye på Svalbard i 2026](../forskrifter/forskrift-2026-01-07-12.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-07-12) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-07-12.md) |
| [Forskrift om fjernmøter og fjernavhør i straffesaker](../forskrifter/forskrift-2011-08-12-835.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-08-12-835) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-08-12-835.md) |
| [Forskrift om flytting av det sentrale ektepaktregister fra Oslo byskriverembete,](../forskrifter/forskrift-1980-06-27-7.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-06-27-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-06-27-7.md) |
| [Forskrift om forbud mot fallskjermhopping m.v. i Trolltindene.](../forskrifter/forskrift-1987-06-12-495.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-06-12-495) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-06-12-495.md) |
| [Forskrift om forbud mot svært brennbare tekstiler](../forskrifter/forskrift-1984-02-13-427.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-02-13-427) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-02-13-427.md) |
| [Forskrift om fordelingen av sakene i domstolene](../forskrifter/forskrift-2021-03-19-762.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-19-762) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-19-762.md) |
| [Forskrift om forenklet forelegg i fritids- og småbåtsaker](../forskrifter/forskrift-2001-06-15-634.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-06-15-634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-06-15-634.md) |
| [Forskrift om forsikringsavtaler (forsikringsavtaleforskriften)](../forskrifter/forskrift-2022-03-04-323.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-04-323) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-04-323.md) |
| [Forskrift om forsøksprosjekt om kartlegging av domfeltes behov for tiltak med si](../forskrifter/forskrift-2011-09-30-978.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-09-30-978) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-09-30-978.md) |
| [Forskrift om fortegnelser over meddommere](../forskrifter/forskrift-2018-09-25-1474.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-25-1474) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-25-1474.md) |
| [Forskrift om fortsatt anvendelse av Luganokonvensjonen 1988](../forskrifter/forskrift-2009-10-16-1280.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-10-16-1280) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-10-16-1280.md) |
| [Forskrift om fotografering, filmopptak og opptak for radio eller fjernsyn under ](../forskrifter/forskrift-1985-11-15-1910.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-11-15-1910) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-11-15-1910.md) |
| [Forskrift om fraktførerens ansvar for skade ved lufttransport av passasjerer, re](../forskrifter/forskrift-2011-01-06-9.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-01-06-9) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-01-06-9.md) |
| [Forskrift om framgangsmåten ved tinglysing av melding om konkursåpning på grunnl](../forskrifter/forskrift-1985-09-20-1872.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-09-20-1872) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-09-20-1872.md) |
| [Forskrift om fri rettshjelp (rettshjelpsforskriften)](../forskrifter/forskrift-2025-09-26-1961.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-26-1961) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-26-1961.md) |
| [Forskrift om fritak fra plikten til å sende inn regnskaper til Fylkesmannen for ](../forskrifter/forskrift-1998-05-07-468.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-05-07-468) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-05-07-468.md) |
| [Forskrift om fullbyrding av nordiske dommer på straff m.v.](../forskrifter/forskrift-1963-12-12-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-12-12-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-12-12-1.md) |
| [Forskrift om fullmakt til å regulere inndeling i lensmannsdistrikter.](../forskrifter/forskrift-1965-10-22-9743.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1965-10-22-9743) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1965-10-22-9743.md) |
| [Forskrift om føring av Løsøreregisteret og Regnskapsregisteret](../forskrifter/forskrift-1987-12-18-985.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-12-18-985) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-12-18-985.md) |
| [Forskrift om gassapparater](../forskrifter/forskrift-2018-06-26-1025.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-26-1025) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-26-1025.md) |
| [Forskrift om gjennomføring av særreaksjonen forvaring.](../forskrifter/forskrift-2004-03-05-481.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-03-05-481) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-03-05-481.md) |
| [Forskrift om gjennomføring av særreaksjonen tvungen omsorg](../forskrifter/forskrift-2001-12-21-1523.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-21-1523) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-21-1523.md) |
| [Forskrift om gjennomføring i norsk rett av nordisk konvensjon 6. februar 1931 nr](../forskrifter/forskrift-2008-05-26-507.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-26-507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-26-507.md) |
| [Forskrift om godtgjøring til mannskaper som er tatt ut til tjeneste i politiet.](../forskrifter/forskrift-1953-06-26-9512.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1953-06-26-9512) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1953-06-26-9512.md) |
| [Forskrift om godtgjøring under oppøving og senere tjeneste for politireserven.](../forskrifter/forskrift-1953-06-26-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1953-06-26-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1953-06-26-5.md) |
| [Forskrift om grensetilsyn og grensekontroll av personer (grenseforskriften)](../forskrifter/forskrift-2022-04-29-665.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-29-665) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-29-665.md) |
| [Forskrift om gruppesøksmål](../forskrifter/forskrift-2007-11-26-1325.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-11-26-1325) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-11-26-1325.md) |
| [Forskrift om hvilke domstoler forskrift om opptak i retten § 6 gjelder for](../forskrifter/forskrift-2018-10-17-1577.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-10-17-1577) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-10-17-1577.md) |
| [Forskrift om håndtering av brannfarlig, reaksjonsfarlig og trykksatt stoff samt ](../forskrifter/forskrift-2009-06-08-602.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-08-602) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-08-602.md) |
| [Forskrift om håndtering av eksplosjonsfarlig stoff](../forskrifter/forskrift-2002-06-26-922.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-26-922) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-26-922.md) |
| [Forskrift om håndtering av medisinsk utstyr](../forskrifter/forskrift-2013-11-29-1373.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-29-1373) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-29-1373.md) |
| [Forskrift om ikraftsetting av lov 17. juni 2005 nr. 90 om mekling og rettergang ](../forskrifter/forskrift-2007-01-26-88.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-01-26-88) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-01-26-88.md) |
| [Forskrift om ikrafttredelse av lov 7. juni 1985 nr. 51 om utmarkskommisjon for N](../forskrifter/forskrift-1986-01-17-37.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-01-17-37) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-01-17-37.md) |
| [Forskrift om ikrafttreden av og delegering etter endringslov 23. juni 1978 nr. 6](../forskrifter/forskrift-1980-03-14-8941.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-03-14-8941) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-03-14-8941.md) |
| [Forskrift om industrielt rettsvern på Svalbard og Jan Mayen](../forskrifter/forskrift-2019-06-21-801.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-21-801) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-21-801.md) |
| [Forskrift om industrivern](../forskrifter/forskrift-2011-12-20-1434.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-20-1434) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-20-1434.md) |
| [Forskrift om inndelingen av rettskretser og lagdømmer](../forskrifter/forskrift-2021-01-22-163.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-22-163) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-22-163.md) |
| [Forskrift om innkalling og utsettelse ved fullbyrding av straff](../forskrifter/forskrift-2010-03-19-408.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-03-19-408) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-03-19-408.md) |
| [Forskrift om internasjonalt samarbeid i straffesaker](../forskrifter/forskrift-2012-12-14-1227.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-14-1227) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-14-1227.md) |
| [Forskrift om jordskiftedommerfullmektigers myndighet](../forskrifter/forskrift-2015-12-07-1431.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-07-1431) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-07-1431.md) |
| [Forskrift om justering av årlige vederlag fastsatt i medhold av lov om rettshøve](../forskrifter/forskrift-1984-12-07-1958.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-12-07-1958) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-12-07-1958.md) |
| [Forskrift om kapitaliseringsrente etter skadeserstatningsloven](../forskrifter/forskrift-2022-08-26-1482.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-26-1482) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-26-1482.md) |
| [Forskrift om kirkegårder i Longyearbyen og askespredning på Svalbard](../forskrifter/forskrift-2008-02-15-153.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-02-15-153) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-02-15-153.md) |
| [Forskrift om kjøpers renteplikt ved betaling etter oppgjørsdagen, jf. tvangsfull](../forskrifter/forskrift-2000-04-28-368.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-04-28-368) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-04-28-368.md) |
| [Forskrift om klageordning for kommuner som berøres av ny tjenestestedsstruktur i](../forskrifter/forskrift-2016-06-22-815.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-22-815) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-22-815.md) |
| [Forskrift om klassifisering, merking og emballering av stoffer og stoffblandinge](../forskrifter/forskrift-2012-06-16-622.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-16-622) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-16-622.md) |
| [Forskrift om kommunal beredskapsplikt](../forskrifter/forskrift-2011-08-22-894.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-08-22-894) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-08-22-894.md) |
| [Forskrift om kommunal håndheving av politivedtekter](../forskrifter/forskrift-2012-06-19-600.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-19-600) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-19-600.md) |
| [Forskrift om kommunikasjonskontroll, romavlytting og dataavlesing (kommunikasjon](../forskrifter/forskrift-2016-09-09-1047.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-09-1047) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-09-1047.md) |
| [Forskrift om konfliktrådsbehandling](../forskrifter/forskrift-2014-06-30-923.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-30-923) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-30-923.md) |
| [Forskrift om konkursregisteret og om kunngjøringer etter konkursloven](../forskrifter/forskrift-1993-08-23-824.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-23-824) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-23-824.md) |
| [Forskrift om konstruksjon, utforming og produksjon av personlig verneutstyr (PVU](../forskrifter/forskrift-2018-06-22-1019.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-1019) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-1019.md) |
| [Forskrift om kontroll av reisende til og fra Svalbard](../forskrifter/forskrift-2022-04-29-643.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-29-643) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-29-643.md) |
| [Forskrift om kontroll med post- og telegramforsendelser.](../forskrifter/forskrift-1960-08-19-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1960-08-19-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1960-08-19-2.md) |
| [Forskrift om landtransport av farlig gods](../forskrifter/forskrift-2009-04-01-384.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-04-01-384) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-04-01-384.md) |
| [Forskrift om lokal regulering av jakt på svalbardrype og svalbardrein på Svalbar](../forskrifter/forskrift-2003-08-04-1005.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-04-1005) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-04-1005.md) |
| [Forskrift om lokalstyrevalg i Longyearbyen](../forskrifter/forskrift-2007-05-14-506.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-05-14-506) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-05-14-506.md) |
| [Forskrift om maritime elektriske anlegg](../forskrifter/forskrift-2001-12-04-1450.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-04-1450) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-04-1450.md) |
| [Forskrift om maskiner](../forskrifter/forskrift-2009-05-20-544.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-05-20-544) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-05-20-544.md) |
| [Forskrift om mortifikasjon av skuldbrev](../forskrifter/forskrift-2008-06-20-620.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-20-620) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-20-620.md) |
| [Forskrift om målingsmåten i lov om rettshøve mellom grannar 16. juni 1961 nr. 15](../forskrifter/forskrift-1961-12-22-4.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1961-12-22-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1961-12-22-4.md) |
| [Forskrift om narkotikaprogram med domstolskontroll](../forskrifter/forskrift-2017-10-20-1650.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-20-1650) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-20-1650.md) |
| [Forskrift om nasjonalt register for vaktvirksomhet](../forskrifter/forskrift-2022-01-25-120.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-25-120) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-25-120.md) |
| [Forskrift om naturskadeforsikring (naturskadeforsikringsforskriften)](../forskrifter/forskrift-2024-01-26-111.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-26-111) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-26-111.md) |
| [Forskrift om notarius publicus](../forskrifter/forskrift-2002-05-03-418.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-05-03-418) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-05-03-418.md) |
| [Forskrift om offentlighet i rettspleien.](../forskrifter/forskrift-2001-07-06-757.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-07-06-757) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-07-06-757.md) |
| [Forskrift om omsorgen for enslige mindreårige som bor i asylmottak](../forskrifter/forskrift-2021-05-12-1520.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-12-1520) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-12-1520.md) |
| [Forskrift om oppbevaring ved domstolene av dokumenter i saker med anonym vitnefø](../forskrifter/forskrift-2001-07-06-759.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-07-06-759) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-07-06-759.md) |
| [Forskrift om opphevelse av importøransvaret etter produktansvarsloven for import](../forskrifter/forskrift-1993-11-12-1028.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-11-12-1028) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-11-12-1028.md) |
| [Forskrift om oppheving av bestemmelsen om kunngjøring i Norsk Lysningsblad av fo](../forskrifter/forskrift-1963-09-19-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-09-19-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-09-19-1.md) |
| [Forskrift om opprettelse av en ny Moss byrett m.v.](../forskrifter/forskrift-1981-01-23-8985.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-01-23-8985) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-01-23-8985.md) |
| [Forskrift om opprettelse av en ny Tønsberg byrett m.v.](../forskrifter/forskrift-1981-01-23-8984.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-01-23-8984) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-01-23-8984.md) |
| [Forskrift om opptak i retten](../forskrifter/forskrift-2018-09-28-1471.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-28-1471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-28-1471.md) |
| [Forskrift om opptak til bachelorutdanningen ved Politihøgskolen](../forskrifter/forskrift-2017-08-29-1592.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-08-29-1592) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-08-29-1592.md) |
| [Forskrift om opptak til masterstudier ved Politihøgskolen](../forskrifter/forskrift-2017-04-19-674.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-19-674) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-19-674.md) |
| [Forskrift om opptak, studier og eksamen ved fagskolestudiet Brann, redning og sa](../forskrifter/forskrift-2023-01-30-111.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-30-111) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-30-111.md) |
| [Forskrift om ordningen av påtalemyndigheten (Påtaleinstruksen)](../forskrifter/forskrift-1985-06-28-1679.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-06-28-1679) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-06-28-1679.md) |
| [Forskrift om organisering, bemanning og utrustning av brann- og redningsvesen og](../forskrifter/forskrift-2021-09-15-2755.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-15-2755) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-15-2755.md) |
| [Forskrift om overgangsbestemmelser for gjennomføring av lov av 18. februar 1999 ](../forskrifter/forskrift-1999-09-07-1048.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-09-07-1048) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-09-07-1048.md) |
| [Forskrift om overgangsbestemmelser til lov 15. desember 2006 nr. 88 om endringer](../forskrifter/forskrift-2006-12-15-1433.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-15-1433) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-15-1433.md) |
| [Forskrift om overgangsbestemmelser til lov om endringer i forbrukerkjøpsloven (l](../forskrifter/forskrift-2006-06-30-874.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-874) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-874.md) |
| [Forskrift om overgangsreglar ved ikraftsetjing av lov 2. juli 2004 nr. 63 om end](../forskrifter/forskrift-2004-10-15-1338.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-10-15-1338) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-10-15-1338.md) |
| [Forskrift om overgangsreglar ved ikraftsetjing av lov 30. juni 2006 nr. 52 om en](../forskrifter/forskrift-2006-06-30-729.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-729) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-729.md) |
| [Forskrift om overgangsreglar ved iverksetjing av lov 19. juni 2009 nr. 76 om end](../forskrifter/forskrift-2009-09-04-1153.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-09-04-1153) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-09-04-1153.md) |
| [Forskrift om overgangsregler for behandling av arrestordre og anmodninger om gje](../forskrifter/forskrift-2020-12-18-2868.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2868) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2868.md) |
| [Forskrift om overgangsregler om betaling av egenandeler i saker om fri rettshjel](../forskrifter/forskrift-2003-08-01-988.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-01-988) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-01-988.md) |
| [Forskrift om overgangsregler til lov 28. april 2000 nr. 34 om endringar i retter](../forskrifter/forskrift-2000-04-28-367.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-04-28-367) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-04-28-367.md) |
| [Forskrift om overgangsregler til lov av 16. mars 2001 nr. 8 om endringer i inkas](../forskrifter/forskrift-2001-12-21-1508.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-21-1508) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-21-1508.md) |
| [Forskrift om overgangsregler til tvangsfullbyrdelsesloven.](../forskrifter/forskrift-1992-12-04-891.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-891) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-891.md) |
| [Forskrift om pass og nasjonalt ID-kort (pass- og ID-kortforskriften)](../forskrifter/forskrift-2020-10-09-2012.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-09-2012) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-09-2012.md) |
| [Forskrift om plikt til å gi opplysninger til forvaltning og statistikk på Svalba](../forskrifter/forskrift-2006-06-09-602.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-09-602) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-09-602.md) |
| [Forskrift om politidistrikt, namsmannsdistrikt, lagdømme og domssogn for utøvels](../forskrifter/forskrift-1999-12-17-1391.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-17-1391) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-17-1391.md) |
| [Forskrift om postforkynning](../forskrifter/forskrift-1985-10-11-1810.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-10-11-1810) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-10-11-1810.md) |
| [Forskrift om program mot ruspåvirket kjøring](../forskrifter/forskrift-2008-10-10-1100.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-10-10-1100) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-10-10-1100.md) |
| [Forskrift om pyrotekniske artikler](../forskrifter/forskrift-2013-10-03-1199.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-10-03-1199) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-10-03-1199.md) |
| [Forskrift om reduksjon av utslipp av bensindamp](../forskrifter/forskrift-1999-02-10-206.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-02-10-206) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-02-10-206.md) |
| [Forskrift om register over befolkningen på Svalbard](../forskrifter/forskrift-1994-02-04-111.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-02-04-111) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-02-04-111.md) |
| [Forskrift om registrering og merking av fartøyer i vassdrag som danner riksgrens](../forskrifter/forskrift-2022-04-29-667.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-29-667) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-29-667.md) |
| [Forskrift om registrering, vurdering, godkjenning og begrensning av kjemikalier ](../forskrifter/forskrift-2008-05-30-516.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-30-516) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-30-516.md) |
| [Forskrift om registreringssted for innføring i skipsregisteret av faste innretni](../forskrifter/forskrift-1985-06-07-1016.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-06-07-1016) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-06-07-1016.md) |
| [Forskrift om regulativ for erleggelse av avgift for godkjennelse av og tilsyn me](../forskrifter/forskrift-1987-12-18-991.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-12-18-991) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-12-18-991.md) |
| [Forskrift om rekvirentens ansvar for kostnadene ved konkursbehandling.](../forskrifter/forskrift-2005-01-27-70.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-01-27-70) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-01-27-70.md) |
| [Forskrift om rentesats etter ekteskapsloven](../forskrifter/forskrift-2007-02-13-164.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-02-13-164) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-02-13-164.md) |
| [Forskrift om rentesatser etter dekningsloven § 6-2 og § 9-7.](../forskrifter/forskrift-2003-02-14-145.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-14-145) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-14-145.md) |
| [Forskrift om rettspsykiatriske undersøkelser og sakkyndige](../forskrifter/forskrift-2020-09-30-1921.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-09-30-1921) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-09-30-1921.md) |
| [Forskrift om revisjon m.m. for Longyearbyen lokalstyre.](../forskrifter/forskrift-2001-12-14-1391.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-14-1391) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-14-1391.md) |
| [Forskrift om saksøktes ansvar for sakskostnader ved tvangsfullbyrdelse](../forskrifter/forskrift-2020-10-23-2120.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-23-2120) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-23-2120.md) |
| [Forskrift om salær fra det offentlige til advokater m.fl. etter faste satser (st](../forskrifter/forskrift-2005-12-12-1442.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-12-1442) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-12-1442.md) |
| [Forskrift om salær fra det offentlige til advokater m.v.](../forskrifter/forskrift-1997-12-03-1441.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-03-1441) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-03-1441.md) |
| [Forskrift om samarbeid med Danmark, Finland, Island og Sverige om fullbyrding av](../forskrifter/forskrift-1963-12-03-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-12-03-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-12-03-1.md) |
| [Forskrift om satser for frikjøp av tilfluktsromplasser.](../forskrifter/forskrift-1995-03-14-251.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-03-14-251) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-03-14-251.md) |
| [Forskrift om selskapets opplysningsplikt før og etter generalforsamlingen i viss](../forskrifter/forskrift-2009-07-06-983.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-07-06-983) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-07-06-983.md) |
| [Forskrift om sertifikater for forsikring og annen sikkerhet etter sjøloven mv.](../forskrifter/forskrift-2019-11-11-1492.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-11-1492) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-11-1492.md) |
| [Forskrift om signatur i domstolene mv.](../forskrifter/forskrift-2021-12-01-3314.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-01-3314) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-01-3314.md) |
| [Forskrift om sikkerhet i felt mv. på Svalbard (feltsikkerhetsforskriften)](../forskrifter/forskrift-2025-06-06-940.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-06-940) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-06-940.md) |
| [Forskrift om sikkerhet ved arbeid i og drift av elektriske anlegg.](../forskrifter/forskrift-2006-04-28-458.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-04-28-458) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-04-28-458.md) |
| [Forskrift om sikkerhet ved lekeplassutstyr](../forskrifter/forskrift-1996-07-19-703.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-703) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-703.md) |
| [Forskrift om sikkerhet ved leketøy (leketøyforskriften)](../forskrifter/forskrift-2013-11-18-1403.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-18-1403) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-18-1403.md) |
| [Forskrift om sikkerheten ved rafting.](../forskrifter/forskrift-1994-09-19-994.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-09-19-994) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-09-19-994.md) |
| [Forskrift om sikkerhetsklarering og annen klarering (klareringsforskriften)](../forskrifter/forskrift-2018-12-20-2054.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2054) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2054.md) |
| [Forskrift om sikkerhetslovens anvendelse for Svalbard og Jan Mayen](../forskrifter/forskrift-2018-12-20-2059.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2059) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2059.md) |
| [Forskrift om sikkerhetslovens anvendelse for virksomheter i Dronning Maud Land](../forskrifter/forskrift-2019-12-06-1645.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-06-1645) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-06-1645.md) |
| [Forskrift om sinnsyke sikrings- eller forvaringsdømte](../forskrifter/forskrift-1955-06-23-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1955-06-23-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1955-06-23-2.md) |
| [Forskrift om sivil håndtering av eksplosjonsfarlige stoffer (eksplosivforskrifte](../forskrifter/forskrift-2017-06-15-844.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-15-844) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-15-844.md) |
| [Forskrift om sivilbeskyttelseslovens anvendelse på Svalbard og om beredskapsplik](../forskrifter/forskrift-2012-12-18-1293.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-18-1293) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-18-1293.md) |
| [Forskrift om sivilforsvar (sivilforsvarsforskriften)](../forskrifter/forskrift-2022-02-14-253.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-02-14-253) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-02-14-253.md) |
| [Forskrift om skikkethetsvurdering, utvisning, bortvisning og utestenging av stud](../forskrifter/forskrift-2024-09-27-2338.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-27-2338) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-27-2338.md) |
| [Forskrift om standardisert erstatning etter lov om yrkesskadeforsikring](../forskrifter/forskrift-1990-12-21-1027.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-12-21-1027) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-12-21-1027.md) |
| [Forskrift om standardisert inntektstaperstatning til barn](../forskrifter/forskrift-2018-02-16-236.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-02-16-236) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-02-16-236.md) |
| [Forskrift om standardisert inntektstaperstatning til barn](../forskrifter/forskrift-2026-08-21-1651.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-08-21-1651) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-08-21-1651.md) |
| [Forskrift om standardsatser for oppreisning etter uberettiget strafforfølgning.](../forskrifter/forskrift-2003-12-12-1472.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-12-1472) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-12-1472.md) |
| [Forskrift om statens tilskudd m.v. ved bygging av offentlige tilfluktsrom.](../forskrifter/forskrift-1984-09-21-1674.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-09-21-1674) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-09-21-1674.md) |
| [Forskrift om stengning av et område i Kongsfjorden på Svalbard for fiskeaktivite](../forskrifter/forskrift-2007-02-02-136.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-02-02-136) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-02-02-136.md) |
| [Forskrift om stevnevitners, politiansattes og fengselstjenestemenns utførelse av](../forskrifter/forskrift-1927-06-24-9812.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1927-06-24-9812) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1927-06-24-9812.md) |
| [Forskrift om straffegjennomføring](../forskrifter/forskrift-2002-02-22-183.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-02-22-183) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-02-22-183.md) |
| [Forskrift om studiet bachelor i straffegjennomføring](../forskrifter/forskrift-2018-11-16-1811.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-11-16-1811) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-11-16-1811.md) |
| [Forskrift om stønad til beboere i asylmottak](../forskrifter/forskrift-2022-05-31-948.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-31-948) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-31-948.md) |
| [Forskrift om tap av retten til å føre motorvogn mv.](../forskrifter/forskrift-2003-12-19-1660.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-19-1660) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-19-1660.md) |
| [Forskrift om tilfluktsrom](../forskrifter/forskrift-1995-03-15-254.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-03-15-254) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-03-15-254.md) |
| [Forskrift om tillitsmannens regnskapsplikt ved forvaltningen av beslagsfrie midl](../forskrifter/forskrift-1985-09-20-1873.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-09-20-1873) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-09-20-1873.md) |
| [Forskrift om tilskudd til aktivitetstilbud for barn i asylmottak](../forskrifter/forskrift-2020-12-17-2921.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-17-2921) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-17-2921.md) |
| [Forskrift om tilskudd til assistert retur og tvangsretur](../forskrifter/forskrift-2020-02-17-183.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-17-183) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-17-183.md) |
| [Forskrift om tilskudd til forebygging av kriminalitet](../forskrifter/forskrift-2020-12-10-2677.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2677) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2677.md) |
| [Forskrift om tilskudd til frivillige organisasjoner i kriminalomsorgen](../forskrifter/forskrift-2020-12-10-2678.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2678) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2678.md) |
| [Forskrift om tilskudd til frivillige organisasjoner i redningstjenesten](../forskrifter/forskrift-2020-12-10-2679.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2679) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2679.md) |
| [Forskrift om tilskudd til internasjonalt migrasjonsarbeid](../forskrifter/forskrift-2023-11-20-1949.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-20-1949) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-20-1949.md) |
| [Forskrift om tilskudd til politiforeninger](../forskrifter/forskrift-2022-12-20-2360.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2360) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2360.md) |
| [Forskrift om tilskudd til sikringstiltak for tros- og livssynssamfunn](../forskrifter/forskrift-2020-10-15-2046.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-15-2046) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-15-2046.md) |
| [Forskrift om tilskudd til spesielle rettshjelptiltak](../forskrifter/forskrift-2020-12-10-2676.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2676) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2676.md) |
| [Forskrift om tilskudd til tiltak for å nå personer uten lovlig opphold i Norge m](../forskrifter/forskrift-2020-12-10-2681.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2681) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2681.md) |
| [Forskrift om tilskudd til tiltak mot menneskehandel og prostitusjon](../forskrifter/forskrift-2020-12-10-2675.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2675) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2675.md) |
| [Forskrift om tilskudd til å forebygge og bekjempe vold i nære relasjoner](../forskrifter/forskrift-2020-12-10-2680.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2680) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2680.md) |
| [Forskrift om tilsyn med omsorgen for enslige mindreårige som bor i asylmottak](../forskrifter/forskrift-2022-06-26-1193.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-26-1193) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-26-1193.md) |
| [Forskrift om tilsynsrådet for kriminalomsorgen](../forskrifter/forskrift-2024-12-09-3005.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-09-3005) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-09-3005.md) |
| [Forskrift om tilsynsrådet for tvangsreturer og utlendingsinternatet](../forskrifter/forskrift-2022-06-13-1005.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-13-1005) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-13-1005.md) |
| [Forskrift om tiltak for å forebygge og begrense konsekvensene av storulykker i v](../forskrifter/forskrift-2016-06-03-569.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-03-569) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-03-569.md) |
| [Forskrift om tomtefeste m.m.](../forskrifter/forskrift-2001-06-08-570.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-06-08-570) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-06-08-570.md) |
| [Forskrift om transportabelt trykkutstyr](../forskrifter/forskrift-2012-11-22-1088.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-22-1088) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-22-1088.md) |
| [Forskrift om trekningskretser for meddommere ved Agder tingrett](../forskrifter/forskrift-2021-03-15-996.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-996) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-996.md) |
| [Forskrift om trekningskretser for meddommere ved Buskerud tingrett](../forskrifter/forskrift-2021-03-15-1008.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-1008) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-1008.md) |
| [Forskrift om trekningskretser for meddommere ved Follo og Nordre Østfold tingret](../forskrifter/forskrift-2021-03-15-1010.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-1010) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-1010.md) |
| [Forskrift om trekningskretser for meddommere ved Gudbrandsdal tingrett](../forskrifter/forskrift-2025-05-14-797.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-797) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-797.md) |
| [Forskrift om trekningskretser for meddommere ved Haugaland og Sunnhordland tingr](../forskrifter/forskrift-2021-03-15-856.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-856) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-856.md) |
| [Forskrift om trekningskretser for meddommere ved Hedmarken og Østerdal tingrett](../forskrifter/forskrift-2021-03-15-1012.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-1012) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-1012.md) |
| [Forskrift om trekningskretser for meddommere ved Helgeland tingrett](../forskrifter/forskrift-2021-03-15-852.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-852) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-852.md) |
| [Forskrift om trekningskretser for meddommere ved Indre og Østre Finnmark tingret](../forskrifter/forskrift-2021-03-15-849.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-849) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-849.md) |
| [Forskrift om trekningskretser for meddommere ved Midtre Hålogaland tingrett](../forskrifter/forskrift-2021-03-15-851.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-851) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-851.md) |
| [Forskrift om trekningskretser for meddommere ved Nord-Troms og Senja tingrett](../forskrifter/forskrift-2021-03-15-850.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-850) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-850.md) |
| [Forskrift om trekningskretser for meddommere ved Nordmøre og Romsdal tingrett](../forskrifter/forskrift-2025-05-14-795.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-795) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-795.md) |
| [Forskrift om trekningskretser for meddommere ved Ringerike og Hallingdal tingret](../forskrifter/forskrift-2025-05-14-799.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-799) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-799.md) |
| [Forskrift om trekningskretser for meddommere ved Romerike og Glåmdal tingrett](../forskrifter/forskrift-2021-03-15-1066.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-1066) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-1066.md) |
| [Forskrift om trekningskretser for meddommere ved Salten og Lofoten tingrett](../forskrifter/forskrift-2021-03-15-853.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-853) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-853.md) |
| [Forskrift om trekningskretser for meddommere ved Sunnmøre tingrett](../forskrifter/forskrift-2025-05-14-796.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-796) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-796.md) |
| [Forskrift om trekningskretser for meddommere ved Søndre Østfold tingrett](../forskrifter/forskrift-2021-03-15-767.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-767) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-767.md) |
| [Forskrift om trekningskretser for meddommere ved Sør-Rogaland tingrett](../forskrifter/forskrift-2021-03-15-857.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-857) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-857.md) |
| [Forskrift om trekningskretser for meddommere ved Trøndelag tingrett](../forskrifter/forskrift-2021-03-15-766.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-766) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-766.md) |
| [Forskrift om trekningskretser for meddommere ved Vestoppland og Valdres tingrett](../forskrifter/forskrift-2025-05-14-798.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-798) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-798.md) |
| [Forskrift om trekningskretser for meddommere ved Vestre Finnmark tingrett](../forskrifter/forskrift-2021-03-15-799.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-799) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-799.md) |
| [Forskrift om trekningskretser for meddommere ved Øvre Telemark tingrett](../forskrifter/forskrift-2025-05-14-800.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-800) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-800.md) |
| [Forskrift om tryggleiken ved sportsdykking.](../forskrifter/forskrift-1994-11-10-1134.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-11-10-1134) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-11-10-1134.md) |
| [Forskrift om trykkpåkjent utstyr](../forskrifter/forskrift-2017-10-10-1631.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-10-1631) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-10-1631.md) |
| [Forskrift om tvangssalg ved medhjelper](../forskrifter/forskrift-1992-12-04-895.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-895) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-895.md) |
| [Forskrift om unntak fra kravet til redegjørelse om aksjeinnskudd med andre eiend](../forskrifter/forskrift-2013-10-26-1271.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-10-26-1271) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-10-26-1271.md) |
| [Forskrift om utforming av grensemerker i saker for jordskiftedomstolene](../forskrifter/forskrift-2015-12-07-1416.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-07-1416) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-07-1416.md) |
| [Forskrift om utgangsstoffer for eksplosiver](../forskrifter/forskrift-2024-08-28-2049.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-08-28-2049) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-08-28-2049.md) |
| [Forskrift om utlegg ved lønnstrekk o.l. i særlige tilfelle etter lov om fordring](../forskrifter/forskrift-1975-06-27-4943.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1975-06-27-4943) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1975-06-27-4943.md) |
| [Forskrift om utlendingers adgang til riket og deres opphold her (utlendingsforsk](../forskrifter/forskrift-2009-10-15-1286.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-10-15-1286) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-10-15-1286.md) |
| [Forskrift om utlevering for å få iverksatt vedtak om frihetsinngrep i annet nord](../forskrifter/forskrift-1970-12-18-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1970-12-18-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1970-12-18-2.md) |
| [Forskrift om utstyr og sikkerhetssystem til bruk i eksplosjonsfarlig område](../forskrifter/forskrift-2017-11-29-1849.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-11-29-1849) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-11-29-1849.md) |
| [Forskrift om utvidelse av Svalbardutvalgets stedlige virkeområde m.v.](../forskrifter/forskrift-1971-08-06-3434.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-08-06-3434) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-08-06-3434.md) |
| [Forskrift om utvidelse av anvendelsesområdet for lov 20. juli 1991 nr 67 om over](../forskrifter/forskrift-1995-02-01-90.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-02-01-90) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-02-01-90.md) |
| [Forskrift om utvidelse av virkeområdet for lov om vern av kretsmønstre for integ](../forskrifter/forskrift-1995-12-27-1176.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-12-27-1176) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-12-27-1176.md) |
| [Forskrift om vaktvirksomhet (vaktvirksomhetsforskriften)](../forskrifter/forskrift-2011-03-28-337.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-28-337) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-28-337.md) |
| [Forskrift om valg av utleggsgjenstand](../forskrifter/forskrift-2025-07-09-1508.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-09-1508) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-09-1508.md) |
| [Forskrift om virksomheters arbeid med forebyggende sikkerhet (virksomhetsikkerhe](../forskrifter/forskrift-2018-12-20-2053.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2053) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2053.md) |
| [Forskrift om våpen, skytevåpen, våpendelar og ammunisjon (våpenforskrifta)](../forskrifter/forskrift-2021-05-07-1452.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-07-1452) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-07-1452.md) |
| [Forskrift om å innhente samtykke til eller uttalelse om innsyn i dokumenter innh](../forskrifter/forskrift-2000-03-07-260.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-03-07-260) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-03-07-260.md) |
| [Forskrift om åremålsstillinger i politiet.](../forskrifter/forskrift-2001-06-22-704.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-06-22-704) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-06-22-704.md) |
| [Forskrift til arrestordreloven (arrestordreforskrifta)](../forskrifter/forskrift-2019-10-18-1388.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-18-1388) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-18-1388.md) |
| [Forskrift til arveloven](../forskrifter/forskrift-2020-11-09-2327.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-09-2327) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-09-2327.md) |
| [Forskrift til designloven (designforskriften)](../forskrifter/forskrift-2003-04-04-418.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-04-04-418) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-04-04-418.md) |
| [Forskrift til forvaltningsloven (forvaltningslovforskriften)](../forskrifter/forskrift-2006-12-15-1456.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-15-1456) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-15-1456.md) |
| [Forskrift til inkassoloven m.m. (inkassoforskriften)](../forskrifter/forskrift-1989-07-14-562.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-07-14-562) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-07-14-562.md) |
| [Forskrift til lov om pant (pantelovforskriften).](../forskrifter/forskrift-1980-11-21-14.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-11-21-14) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-11-21-14.md) |
| [Forskrift til lov om yrkesskadeforsikring](../forskrifter/forskrift-1989-10-13-1041.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-10-13-1041) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-10-13-1041.md) |
| [Forskrift til offentleglova (offentlegforskrifta)](../forskrifter/forskrift-2008-10-17-1119.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-10-17-1119) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-10-17-1119.md) |
| [Forskrift til oreigningslova (oreigningsforskrifta)](../forskrifter/forskrift-2026-05-22-870.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-22-870) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-22-870.md) |
| [Forskrift til patentloven (patentforskriften)](../forskrifter/forskrift-2007-12-14-1417.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-14-1417) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-14-1417.md) |
| [Forskrift til sameigeloven § 15 fjerde ledd.](../forskrifter/forskrift-1966-05-25-8701.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-05-25-8701) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-05-25-8701.md) |
| [Forskrift til tvisteloven (tvistelovforskriften)](../forskrifter/forskrift-2007-12-21-1605.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1605) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1605.md) |
| [Forskrift til varemerkeloven (varemerkeforskriften)](../forskrifter/forskrift-2010-06-25-937.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-25-937) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-25-937.md) |
| [Forskrift til vergemålsloven (vergemålsforskriften)](../forskrifter/forskrift-2013-02-15-201.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-02-15-201) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-02-15-201.md) |
| [Forskrift til voldserstatningsloven (voldserstatningsforskriften)](../forskrifter/forskrift-2023-12-14-2088.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-14-2088) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-14-2088.md) |
| [Forskrifter angaaende Fremgangsmaaden ved Salg af Leilændingsgods tilhørende Sta](../forskrifter/forskrift-1896-06-26-9805.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1896-06-26-9805) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1896-06-26-9805.md) |
| [Forskrifter angående innleggelse av alkoholister i kuranstalt i henhold til løsg](../forskrifter/forskrift-1930-11-07-9534.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1930-11-07-9534) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1930-11-07-9534.md) |
| [Forskrifter for teknisk kontroll av gassvernmateriell.](../forskrifter/forskrift-1939-11-17-9575.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1939-11-17-9575) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1939-11-17-9575.md) |
| [Forskrifter for teknisk kontroll av tørrklosetter til bruk i offentlige og priva](../forskrifter/forskrift-1965-03-09-9736.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1965-03-09-9736) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1965-03-09-9736.md) |
| [Forskrifter om det nøyaktige tidspunkt for frigjøringen av Norge.](../forskrifter/forskrift-1945-10-12-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1945-10-12-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1945-10-12-1.md) |
| [Forskrifter om forkynnelse av utenlandske dokumenter i Norge](../forskrifter/forskrift-1969-09-12-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1969-09-12-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1969-09-12-5.md) |
| [Forskrifter om krigsutflytting.](../forskrifter/forskrift-1980-09-05-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-09-05-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-09-05-5.md) |
| [Forskrifter om legeundersøkelse av mannskaper.](../forskrifter/forskrift-1953-07-31-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1953-07-31-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1953-07-31-2.md) |
| [Forskrifter om tilfluktsrom ved industrivernpliktige bedrifter og virksomheter.](../forskrifter/forskrift-1976-08-03-9783.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-08-03-9783) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-08-03-9783.md) |
| [Forskrifter om unntak fra lov og forskrifter om brannfarlige varer.](../forskrifter/forskrift-1978-02-17-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-02-17-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-02-17-2.md) |
| [Forskrifter om utlendingers adgang til Jan Mayen](../forskrifter/forskrift-1962-06-01-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1962-06-01-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1962-06-01-1.md) |
| [Forskrifter om vernepliktige sivilarbeidere.](../forskrifter/forskrift-1952-08-22-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1952-08-22-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1952-08-22-5.md) |
| [Forskrifter vedrørende sivilprosesskonvensjonen av 30. januar 1931 mellom Norge ](../forskrifter/forskrift-1953-03-19-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1953-03-19-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1953-03-19-1.md) |
| [Gebyr- og fakturasatser for Longyearbyen lokalstyre 2026](../forskrifter/forskrift-2025-12-10-3067.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-10-3067) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-10-3067.md) |
| [Godkjennelse av ny forskrift om skikkethetsvurdering, utvisning, bortvisning og ](../forskrifter/forskrift-2024-07-31-2337.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-07-31-2337) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-07-31-2337.md) |
| [Godkjenning av hovedavtalen for Bankklagenemnda.](../forskrifter/forskrift-2000-05-19-442.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-05-19-442) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-05-19-442.md) |
| [Ikraftredelse av lov av 14. juni 1974 nr. 39 om eksplosive varer. Delegasjon av ](../forskrifter/forskrift-1977-03-18-4194.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-03-18-4194) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-03-18-4194.md) |
| [Ikraftsetjing av lov 14. mars 1986 nr. 9 om endringar i lov 30. mai 1975 nr. 20 ](../forskrifter/forskrift-1986-12-05-2161.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-12-05-2161) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-12-05-2161.md) |
| [Ikraftsetting av lov 15. juni 2018 nr. 38 om behandling av personopplysninger (p](../forskrifter/forskrift-2018-06-15-875.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-15-875) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-15-875.md) |
| [Ikraftsetting av lov 16. juni 2017 nr. 58 om endringer i straffeprosessloven mv.](../forskrifter/forskrift-2017-10-13-1613.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-13-1613) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-13-1613.md) |
| [Ikraftsetting av lov 27. mai 2016 nr. 15 om endringer i forvaltningsloven mv. (a](../forskrifter/forskrift-2017-06-09-713.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-09-713) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-09-713.md) |
| [Ikrafttredelse av konkursloven og dekningsloven og om delegering av myndighet.](../forskrifter/forskrift-1985-07-12-1435.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-07-12-1435) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-07-12-1435.md) |
| [Ikrafttredelse av lov 11. juni 1971 nr. 52 om strafferegistrering.](../forskrifter/forskrift-1974-12-20-3.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1974-12-20-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1974-12-20-3.md) |
| [Ikrafttredelse av lov 13. mai 1988 nr. 26 om inkassovirksomhet og annen inndrivi](../forskrifter/forskrift-1989-07-14-553.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-07-14-553) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-07-14-553.md) |
| [Ikrafttredelse av lov 14. juni 1985 nr. 70 om endringer i lov 4. juni 1976 nr. 5](../forskrifter/forskrift-1985-11-22-1986.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-11-22-1986) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-11-22-1986.md) |
| [Ikrafttredelse av lov 15. juni 2007 nr. 37 om endringer i lov 12. mai 1972 nr. 2](../forskrifter/forskrift-2007-06-15-626.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-15-626) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-15-626.md) |
| [Ikrafttredelse av lov 16. juni 1989 nr. 65 om yrkesskadeforsikring. Delegering a](../forskrifter/forskrift-1989-10-13-1040.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-10-13-1040) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-10-13-1040.md) |
| [Ikrafttredelse av lov 16. juni 1989 nr. 69 om forsikringsavtaler og lov 16. juni](../forskrifter/forskrift-1989-12-15-1241.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-12-15-1241) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-12-15-1241.md) |
| [Ikrafttredelse av lov 17. desember 1982 nr. 86 om rettsgebyr. Delegering av mynd](../forskrifter/forskrift-1983-02-11-84.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-02-11-84) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-02-11-84.md) |
| [Ikrafttredelse av lov 19. desember 1975 nr. 70 om brigde i odelsretten og åsetes](../forskrifter/forskrift-1975-12-19-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1975-12-19-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1975-12-19-2.md) |
| [Ikrafttredelse av lov 20. desember 1996 nr. 104 om endringer i lovgivningen om i](../forskrifter/forskrift-1996-12-20-1155.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-12-20-1155) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-12-20-1155.md) |
| [Ikrafttredelse av lov 20. januar 2012 nr. 5 om endringer i utlendingsloven m.m. ](../forskrifter/forskrift-2012-01-20-37.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-20-37) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-20-37.md) |
| [Ikrafttredelse av lov 24. februar 1995 nr. 11 om lotterier m.v. Delegering av my](../forskrifter/forskrift-1995-02-24-184.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-02-24-184) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-02-24-184.md) |
| [Ikrafttredelse av lov 24. juni 1988 nr. 64 om utlendingers adgang til riket og d](../forskrifter/forskrift-1990-12-21-1017.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-12-21-1017) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-12-21-1017.md) |
| [Ikrafttredelse av lov 5. des. 1986 nr. 61 om endring i lov 22. april 1927 om ver](../forskrifter/forskrift-1988-11-10-899.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-11-10-899) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-11-10-899.md) |
| [Ikrafttredelse av lov av 15. juni 1990 nr. 29 om endring i vergemålsloven m.m. (](../forskrifter/forskrift-1990-12-14-982.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-12-14-982) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-12-14-982.md) |
| [Ikrafttredelse av lov av 20. juli 1991 nr. 67 om overføring av domfelte. Deleger](../forskrifter/forskrift-1993-02-12-101.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-02-12-101) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-02-12-101.md) |
| [Ikrafttredelse av lov av 22. juni 1990 nr. 40 om endring i lov av 21. februar 19](../forskrifter/forskrift-1990-11-02-883.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-11-02-883) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-11-02-883.md) |
| [Ikrafttredelse av lov av 7. juni 1985 nr. 52 om endring i arve- og skiftelovgivn](../forskrifter/forskrift-1985-09-06-1690.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-09-06-1690) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-09-06-1690.md) |
| [Ikrafttredelse av lov av 8. juli 1988 nr. 72 om anerkjennelse og fullbyrding av ](../forskrifter/forskrift-1989-02-17-93.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-02-17-93) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-02-17-93.md) |
| [Ikrafttredelse av selskapsloven av 21. juni 1985 nr. 83. Delegering av myndighet](../forskrifter/forskrift-1985-12-13-2091.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-12-13-2091) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-12-13-2091.md) |
| [Ikrafttreden av lov om fullbyrding av nordiske dommer på straff m.v.](../forskrifter/forskrift-1963-11-15-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-11-15-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-11-15-1.md) |
| [Instruks for Direktoratet for samfunnssikkerhet og beredskaps koordinerende roll](../forskrifter/forskrift-2005-06-24-688.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-24-688) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-24-688.md) |
| [Instruks for Politiets sikkerhetstjeneste](../forskrifter/forskrift-2005-08-19-920.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-08-19-920) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-08-19-920.md) |
| [Instruks for behandling av dokumenter som trenger beskyttelse av andre grunner e](../forskrifter/forskrift-1972-03-17-3352.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1972-03-17-3352) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1972-03-17-3352.md) |
| [Instruks for behandling av henvendelser om kritikkverdige forhold utført i tjene](../forskrifter/forskrift-2005-11-21-5026.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-21-5026) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-21-5026.md) |
| [Instruks for behandling av polarsaker og for Det interdepartementale polarutvalg](../forskrifter/forskrift-2002-10-18-1134.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-10-18-1134) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-10-18-1134.md) |
| [Instruks for departementenes arbeid med samfunnssikkerhet (samfunnssikkerhetsins](../forskrifter/forskrift-2017-09-01-1349.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-01-1349) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-01-1349.md) |
| [Instruks for sjefen for den militære stasjon på Jan Mayen for så vidt angår frem](../forskrifter/forskrift-1962-06-01-3341.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1962-06-01-3341) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1962-06-01-3341.md) |
| [Instruks for statsforvalteren og Sysselmesteren på Svalbard sitt arbeid med samf](../forskrifter/forskrift-2015-06-19-703.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-703) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-703.md) |
| [Instruks om adgang til delegering fra namsretten til namsmannen, lensmann, under](../forskrifter/forskrift-1990-06-29-486.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-06-29-486) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-06-29-486.md) |
| [Instruks om regnskap som avlegges av regnskapsførere ved statsforvalterne, domme](../forskrifter/forskrift-1948-02-16-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1948-02-16-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1948-02-16-1.md) |
| [Instruks om samarbeid om grenseoppsynet på landegrensen mellom Norge og Russland](../forskrifter/forskrift-2005-08-05-852.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-08-05-852) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-08-05-852.md) |
| [Instruks om tildeling av begrenset politimyndighet til militære grensevakter ved](../forskrifter/forskrift-2005-08-05-851.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-08-05-851) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-08-05-851.md) |
| [Justering av distriktsinndelingen mv. i politi- og lensmannsetaten som følge av ](../forskrifter/forskrift-2018-08-24-1267.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-08-24-1267) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-08-24-1267.md) |
| [Justering av distriktsinndelingen mv. i politi- og lensmannsetaten som følge av ](../forskrifter/forskrift-2018-10-12-1575.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-10-12-1575) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-10-12-1575.md) |
| [Justering av statsadvokatdistriktene som følge av nærpolitireformen](../forskrifter/forskrift-2016-09-30-1137.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-30-1137) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-30-1137.md) |
| [Justering av statsadvokatembetene som følge av organisasjonsendringer i Den høye](../forskrifter/forskrift-2025-06-20-1187.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1187) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1187.md) |
| [Justeringer av distriktsinndelingen mv. i politi- og lensmannsetaten som følge a](../forskrifter/forskrift-2018-06-15-1074.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-15-1074) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-15-1074.md) |
| [Kompetanse og rapporteringsplikt etter sjøloven § 223](../forskrifter/forskrift-2015-05-12-467.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-12-467) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-12-467.md) |
| [Kunngjøring av York-Antwerpen reglene 1994.](../forskrifter/forskrift-1997-01-24-36.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-01-24-36) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-01-24-36.md) |
| [Meddelelse om ikraftsetting av lov 24. mai 2019 nr. 17 om endringer i Svalbardlo](../forskrifter/forskrift-2019-10-21-1402.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-21-1402) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-21-1402.md) |
| [Meddelelse om ikrafttredelse av forskrift 9. mai 2008 nr. 449 og forskrift 26. m](../forskrifter/forskrift-2008-09-22-1108.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-09-22-1108) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-09-22-1108.md) |
| [Meddelelse om ikrafttredelse av lov 15. juni 2018 nr. 38 om behandling av person](../forskrifter/forskrift-2018-07-17-1195.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-07-17-1195) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-07-17-1195.md) |
| [Opprettelse av Utlendingsdirektoratet m.v.](../forskrifter/forskrift-1987-12-18-972.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-12-18-972) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-12-18-972.md) |
| [Organisasjonsplan for redningstjenesten](../forskrifter/forskrift-2019-12-06-1740.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-06-1740) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-06-1740.md) |
| [Organisering av IKT-området i politi- og lensmannsetaten](../forskrifter/forskrift-2013-10-04-1186.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-10-04-1186) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-10-04-1186.md) |
| [Overgangsbestemmelse til lov 7. mai 2021 nr. 32 om endringer i utlendingsloven (](../forskrifter/forskrift-2021-09-03-2660.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-03-2660) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-03-2660.md) |
| [Overgangsbestemmelser for delt ikrafttredelse 1. mars 2023 av lov 12. juni 2020 ](../forskrifter/forskrift-2023-02-17-230.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-02-17-230) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-02-17-230.md) |
| [Overgangsbestemmelser for gjennomføring av lov 20. april 2012 nr. 19 om endringe](../forskrifter/forskrift-2012-05-25-465.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-25-465) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-25-465.md) |
| [Overgangsbestemmelser til lov 19. juni 2026 nr. 50 om endringer i utlendingslove](../forskrifter/forskrift-2026-06-19-1490.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-19-1490) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-19-1490.md) |
| [Overgangsbestemmelser til lov 22. juni 2018 nr. 78 om endringer i utlendingslove](../forskrifter/forskrift-2018-10-24-1610.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-10-24-1610) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-10-24-1610.md) |
| [Overgangsregel til lov 22. desember 2006 nr. 101 om endringer i lov 17. desember](../forskrifter/forskrift-2006-12-22-1575.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-22-1575) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-22-1575.md) |
| [Overgangsregler om behandling av personopplysninger](../forskrifter/forskrift-2018-06-15-877.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-15-877) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-15-877.md) |
| [Overgangsregler til lov 11. mai 2023 nr. 13 om endringer i tvisteloven mv. (rett](../forskrifter/forskrift-2023-06-02-779.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-02-779) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-02-779.md) |
| [Overgangsregler til lov 11. mai 2023 nr. 13 om endringer i tvisteloven mv. (rett](../forskrifter/forskrift-2023-11-24-1903.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-24-1903) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-24-1903.md) |
| [Overgangsregler til lov 14. juni 2013 nr. 40 om endringer i aksjelovgivningen mv](../forskrifter/forskrift-2013-06-19-662.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-19-662) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-19-662.md) |
| [Overgangsregler til lov 17. juni 2016 nr. 55 om endringer i konkursloven mv. (gr](../forskrifter/forskrift-2021-05-21-1618.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-21-1618) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-21-1618.md) |
| [Overgangsregler til lov 17. juni 2022 nr. 57 om erstatning fra staten til voldsu](../forskrifter/forskrift-2022-12-02-2073.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-02-2073) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-02-2073.md) |
| [Overgangsregler til lov 18. desember 2020 nr. 146 om finansavtaler](../forskrifter/forskrift-2022-09-28-1675.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-28-1675) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-28-1675.md) |
| [Overgangsregler til lov 18. februar 2022 nr. 5 om endringer i forsikringsavtalel](../forskrifter/forskrift-2022-03-04-382.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-04-382) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-04-382.md) |
| [Overgangsregler til lov 29. juni 2007 nr. 80 om endringar i lov 15. desember 196](../forskrifter/forskrift-2007-12-14-1416.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-14-1416) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-14-1416.md) |
| [Regler for granskingskommisjoner. Rundskriv G-48/75 fra Justisdep.](../forskrifter/forskrift-1975-03-04-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1975-03-04-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1975-03-04-1.md) |
| [Regler om bruk av rettskapper m.v. ved domstolen](../forskrifter/forskrift-1995-06-23-577.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-06-23-577) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-06-23-577.md) |
| [Regler om personundersøkelse i straffesaker.](../forskrifter/forskrift-1986-10-22-2373.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-10-22-2373) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-10-22-2373.md) |
| [Res. om at lov av 3. mars 1972 nr. 5 om arv m.m. settes i kraft fra 1. januar 19](../forskrifter/forskrift-1972-06-23-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1972-06-23-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1972-06-23-2.md) |
| [Res. om bruk av telegraf og telefon til forkynnelser i henhold til domstollovens](../forskrifter/forskrift-1932-12-10-3.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1932-12-10-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1932-12-10-3.md) |
| [Res. om dommerforsikring efter domstollovens § 60](../forskrifter/forskrift-1927-06-10-3.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1927-06-10-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1927-06-10-3.md) |
| [Res. om ikraftsetting av lov av 19. mars 1965 om fritaking for militærtjeneste a](../forskrifter/forskrift-1966-06-03-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-06-03-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-06-03-5.md) |
| [Res. om ikrafttreden m.v. av lov om utlevering av lovbrytere til Danmark, Finnla](../forskrifter/forskrift-1961-06-30-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1961-06-30-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1961-06-30-2.md) |
| [Rundskriv om kunngjøring i Norsk Lovtidend avdeling I og II.](../forskrifter/forskrift-1992-10-28-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-10-28-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-10-28-1.md) |
| [Rundskriv om nye blanketter for dødsmeldinger og dødsfallsprotokoller samt endri](../forskrifter/forskrift-1984-12-10-3584.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-12-10-3584) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-12-10-3584.md) |
| [Rundskriv om rettledning til domfelte.](../forskrifter/forskrift-1964-09-10-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1964-09-10-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1964-09-10-1.md) |
| [Sammenslåing av Asker og Bærum herredsrett og herredsskriverembete.](../forskrifter/forskrift-1992-04-24-299.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-04-24-299) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-04-24-299.md) |
| [Sammenslåing av Kristiansand byrett og Setesdal sorenskriverembete.](../forskrifter/forskrift-1992-12-11-1145.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-11-1145) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-11-1145.md) |
| [Stortingsvedtak om formues- og inntektsskatt til Svalbard for inntektsåret 2020](../forskrifter/forskrift-2019-12-12-1818.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-12-1818) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-12-1818.md) |
| [Stortingsvedtak om formues- og inntektsskatt til Svalbard for inntektsåret 2021](../forskrifter/forskrift-2020-12-16-2799.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-16-2799) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-16-2799.md) |
| [Sysselmesterens retningslinjer for skytevåpen og beskyttelses- og skremmemidler ](../forskrifter/forskrift-2024-05-13-850.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-13-850) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-13-850.md) |
| [Tillegging av myndighet etter lov 24. juni 1994 nr. 39 om sjøfarten § 462 tredje](../forskrifter/forskrift-2023-11-03-1766.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-03-1766) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-03-1766.md) |
| [Utfyllande instruks om overføring av domfelte.](../forskrifter/forskrift-1995-02-17-129.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-02-17-129) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-02-17-129.md) |
| [Utpeking av tilsynsmyndighet etter sivilbeskyttelsesloven § 21, jf. § 29](../forskrifter/forskrift-2024-02-29-359.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-29-359) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-29-359.md) |
| [Utpeking av tilsynsmyndighet etter sivilbeskyttelsesloven § 23](../forskrifter/forskrift-2012-04-16-329.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-04-16-329) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-04-16-329.md) |
| [Vedtak om endring av navn fra Nye Kripos til Kripos.](../forskrifter/forskrift-2006-01-20-52.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-01-20-52) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-01-20-52.md) |
| [Vedtak om endring i vedtak 20. januar 2012 nr. 37 om ikrafttredelse av lov 20. j](../forskrifter/forskrift-2012-01-27-69.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-27-69) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-27-69.md) |
| [Vedtak om etablering av Direktoratet for samfunnssikkerhet og beredskap.](../forskrifter/forskrift-2003-08-29-1094.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-29-1094) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-29-1094.md) |
| [Vedtak om formues- og inntektsskatt til Svalbard for inntektsåret 2017](../forskrifter/forskrift-2016-12-19-1741.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-19-1741) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-19-1741.md) |
| [Vedtak om formues- og inntektsskatt til Svalbard for inntektsåret 2018](../forskrifter/forskrift-2017-12-14-2282.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-14-2282) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-14-2282.md) |
| [Vedtak om formues- og inntektsskatt til Svalbard for inntektsåret 2019](../forskrifter/forskrift-2018-12-13-2028.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-13-2028) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-13-2028.md) |
| [Vedtak om godkjenning av vedtekter for klagenemnd for inkassotenester mellom For](../forskrifter/forskrift-2003-03-07-287.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-03-07-287) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-03-07-287.md) |
| [Vedtak om nedleggelse av Kriminalpolitisentralen og opprettelse av Nye Kripos.](../forskrifter/forskrift-2004-09-24-1294.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-09-24-1294) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-09-24-1294.md) |
| [Vedtak om å legge sentral vergemålsmyndighet til Statens sivilrettsforvaltning](../forskrifter/forskrift-2011-02-04-128.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-04-128) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-04-128.md) |
| [Våpeninstruks for politiet](../forskrifter/forskrift-2015-07-02-1088.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-07-02-1088) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-07-02-1088.md) |
