# Klima- og miljødepartementet

*282 forskrifter*

Logglenkene viser eldre, uverifiserte rekonstruksjoner, ikke bekreftet forskriftstekst på en bestemt dato.

| Forskrift | Lovdata | Uverifisert rekonstruksjon |
|-----------|---------|-----------|
| [Bestemmelser om hvilket forvaltningsorgan som skal behandle søknader om dispensa](../forskrifter/forskrift-2011-05-20-525.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-525) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-525.md) |
| [Delegering av Kongens myndighet etter Avtale 30. september 2016 nr. 16 mellom No](../forskrifter/forskrift-2018-03-23-485.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-03-23-485) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-03-23-485.md) |
| [Delegering av Kongens myndighet etter klimakvoteloven](../forskrifter/forskrift-2012-05-25-459.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-25-459) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-25-459.md) |
| [Delegering av Kongens myndighet etter klimakvoteloven § 3, § 3a, § 4, § 5, § 7, ](../forskrifter/forskrift-2023-12-15-2047.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-15-2047) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-15-2047.md) |
| [Delegering av Kongens myndighet etter lov 11. juni 1976 nr. 79 om kontroll med p](../forskrifter/forskrift-2023-09-21-1467.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-21-1467) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-21-1467.md) |
| [Delegering av Kongens myndighet etter lov 11. juni 1976 nr. 79 om kontroll med p](../forskrifter/forskrift-2026-01-23-102.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-23-102) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-23-102.md) |
| [Delegering av Kongens myndighet etter lov 13. mars 1981 nr. 6 om vern mot forure](../forskrifter/forskrift-2024-12-20-3301.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3301) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3301.md) |
| [Delegering av Kongens myndighet etter lov 15. mai 1992 nr. 47 om laksefisk og in](../forskrifter/forskrift-2021-05-28-1702.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-28-1702) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-28-1702.md) |
| [Delegering av Kongens myndighet etter lov 17. desember 2004 nr. 99 om kvoteplikt](../forskrifter/forskrift-2025-06-20-1132.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1132) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1132.md) |
| [Delegering av Kongens myndighet etter lov 25. juni 2024 nr. 69 om bærekraftige p](../forskrifter/forskrift-2024-12-20-3500.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3500) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3500.md) |
| [Delegering av Kongens myndighet etter lov 25. juni 2024 nr. 69 om bærekraftige p](../forskrifter/forskrift-2026-06-19-1144.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-19-1144) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-19-1144.md) |
| [Delegering av forskriftskompetanse etter forurensningsloven § 52c (EMAS) til Mil](../forskrifter/forskrift-2018-08-07-1226.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-08-07-1226) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-08-07-1226.md) |
| [Delegering av forskriftskompetanse til Miljødirektoratet etter produktkontrollov](../forskrifter/forskrift-2017-06-30-1126.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-30-1126) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-30-1126.md) |
| [Delegering av mynde etter genteknologilova § 10 femte ledd](../forskrifter/forskrift-2020-10-23-2125.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-23-2125) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-23-2125.md) |
| [Delegering av myndigheit til Longyearbyen Lokalstyre etter forskrift om sorterin](../forskrifter/forskrift-2009-10-20-5019.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-10-20-5019) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-10-20-5019.md) |
| [Delegering av myndighet etter CITES-forskriften § 31](../forskrifter/forskrift-2019-10-08-1398.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-08-1398) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-08-1398.md) |
| [Delegering av myndighet etter forskrift om utsetting av utenlandske treslag til ](../forskrifter/forskrift-2012-06-26-1493.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-26-1493) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-26-1493.md) |
| [Delegering av myndighet etter forurensningsloven § 52 a og produktkontrolloven §](../forskrifter/forskrift-1986-05-16-1094.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-05-16-1094) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-05-16-1094.md) |
| [Delegering av myndighet etter friluftsloven § 9 fjerde ledd](../forskrifter/forskrift-1984-11-26-1947.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-11-26-1947) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-11-26-1947.md) |
| [Delegering av myndighet etter havvernloven fra Klima- og miljødepartementet til ](../forskrifter/forskrift-2026-01-21-64.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-21-64) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-21-64.md) |
| [Delegering av myndighet etter kulturminneloven](../forskrifter/forskrift-1990-04-30-351.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-04-30-351) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-04-30-351.md) |
| [Delegering av myndighet etter lakse- og innlandsfiskloven § 25 andre og tredje l](../forskrifter/forskrift-2021-01-15-114.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-15-114) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-15-114.md) |
| [Delegering av myndighet etter lakse- og innlandsfiskloven § 40](../forskrifter/forskrift-2020-10-08-2742.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-08-2742) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-08-2742.md) |
| [Delegering av myndighet etter lakse- og innlandsfiskloven § 40 til Miljødirektor](../forskrifter/forskrift-2020-10-08-2010.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-08-2010) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-08-2010.md) |
| [Delegering av myndighet etter lakse- og innlandsfiskloven § 43 tredje ledd (regi](../forskrifter/forskrift-2021-05-05-1548.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-05-1548) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-05-1548.md) |
| [Delegering av myndighet etter lakse- og innlandsfiskloven § 48a første og tredje](../forskrifter/forskrift-2021-06-01-1742.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-01-1742) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-01-1742.md) |
| [Delegering av myndighet etter lakse- og innlandsfiskloven § 7 annet og tredje le](../forskrifter/forskrift-2023-03-31-462.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-03-31-462) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-03-31-462.md) |
| [Delegering av myndighet etter lov av 17. mars 1989 nr. 11 om endringar i lov av ](../forskrifter/forskrift-1989-03-17-168.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-03-17-168) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-03-17-168.md) |
| [Delegering av myndighet etter lov om kontroll med produkter og forbrukertjeneste](../forskrifter/forskrift-1999-08-20-949.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-08-20-949) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-08-20-949.md) |
| [Delegering av myndighet etter lov om kontroll med produkter og forbrukertjeneste](../forskrifter/forskrift-2016-06-17-723.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-17-723) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-17-723.md) |
| [Delegering av myndighet etter lov om kontroll med produkter og forbrukertjeneste](../forskrifter/forskrift-2018-05-25-763.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-05-25-763) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-05-25-763.md) |
| [Delegering av myndighet etter markaloven](../forskrifter/forskrift-2025-06-20-1393.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1393) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1393.md) |
| [Delegering av myndighet etter motorferdselloven § 12b fjerde ledd til Miljødirek](../forskrifter/forskrift-2015-06-18-1923.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-18-1923) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-18-1923.md) |
| [Delegering av myndighet etter naturmangfoldloven fra Klima- og miljødepartemente](../forskrifter/forskrift-2025-02-28-321.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-28-321) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-28-321.md) |
| [Delegering av myndighet etter naturmangfoldloven til Klima- og miljødepartemente](../forskrifter/forskrift-2025-02-28-320.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-28-320) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-28-320.md) |
| [Delegering av myndighet etter naturmangfoldloven til statsforvalterne og nasjona](../forskrifter/forskrift-2025-03-10-399.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-10-399) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-10-399.md) |
| [Delegering av myndighet etter naturoppsynsloven § 5](../forskrifter/forskrift-2017-10-18-2560.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-18-2560) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-18-2560.md) |
| [Delegering av myndighet etter svalbardmiljøloven § 3 bokstav a](../forskrifter/forskrift-2012-04-20-333.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-04-20-333) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-04-20-333.md) |
| [Delegering av myndighet etter viltloven § 26 nr. 8, § 49 første ledd og § 49a](../forskrifter/forskrift-2019-09-13-1124.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-13-1124) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-13-1124.md) |
| [Delegering av myndighet etter viltressursloven fra Klima- og miljødepartementet ](../forskrifter/forskrift-2026-07-13-1550.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-07-13-1550) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-07-13-1550.md) |
| [Delegering av myndighet etter viltressursloven §§ 45, 46, 47 og 49 fra Klima- og](../forskrifter/forskrift-2026-06-25-1378.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-25-1378) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-25-1378.md) |
| [Delegering av myndighet og overføring av oppgaver etter lov om laksefisk og innl](../forskrifter/forskrift-1996-01-19-1480.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-01-19-1480) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-01-19-1480.md) |
| [Delegering av myndighet til Direktoratet for naturforvaltning etter forskrift om](../forskrifter/forskrift-2010-04-30-947.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-30-947) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-30-947.md) |
| [Delegering av myndighet til Direktoratet for naturforvaltning etter friluftslove](../forskrifter/forskrift-1996-06-21-603.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-06-21-603) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-06-21-603.md) |
| [Delegering av myndighet til Direktoratet for naturforvaltning etter lov om lakse](../forskrifter/forskrift-2007-04-26-474.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-04-26-474) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-04-26-474.md) |
| [Delegering av myndighet til Direktoratet for naturforvaltning etter lov om lakse](../forskrifter/forskrift-2001-07-11-831.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-07-11-831) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-07-11-831.md) |
| [Delegering av myndighet til Direktoratet for naturforvaltning etter lov om natur](../forskrifter/forskrift-1988-10-20-4323.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-10-20-4323) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-10-20-4323.md) |
| [Delegering av myndighet til Direktoratet for naturforvaltning etter lov om natur](../forskrifter/forskrift-1988-11-03-4324.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-11-03-4324) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-11-03-4324.md) |
| [Delegering av myndighet til Direktoratet for naturforvaltning etter lov om vilte](../forskrifter/forskrift-2002-09-19-1915.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-09-19-1915) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-09-19-1915.md) |
| [Delegering av myndighet til Direktoratet for naturforvaltning etter lov om vilte](../forskrifter/forskrift-1994-07-01-4322.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-07-01-4322) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-07-01-4322.md) |
| [Delegering av myndighet til Direktoratet for naturforvaltning etter lov om vilte](../forskrifter/forskrift-2001-04-30-1670.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-04-30-1670) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-04-30-1670.md) |
| [Delegering av myndighet til Direktoratet for vilt og ferskvannsfisk etter fjello](../forskrifter/forskrift-1976-01-08-4297.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-01-08-4297) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-01-08-4297.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter forurensningslove](../forskrifter/forskrift-1997-01-31-98.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-01-31-98) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-01-31-98.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter forurensningslove](../forskrifter/forskrift-2004-05-28-790.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-05-28-790) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-05-28-790.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter klimakvoteloven §](../forskrifter/forskrift-2004-12-17-1669.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-17-1669) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-17-1669.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter klimakvoteloven §](../forskrifter/forskrift-2007-06-29-824.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-824) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-824.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter klimakvoteloven §](../forskrifter/forskrift-2019-06-21-858.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-21-858) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-21-858.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter lov 13. mars 1981](../forskrifter/forskrift-2026-06-19-1138.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-19-1138) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-19-1138.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter lov 15. april 201](../forskrifter/forskrift-2011-04-15-426.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-04-15-426) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-04-15-426.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter lov om endringer ](../forskrifter/forskrift-2009-02-27-247.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-02-27-247) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-02-27-247.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter lov om lakse- og ](../forskrifter/forskrift-2000-10-27-1074.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-10-27-1074) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-10-27-1074.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter lov om viltet § 3](../forskrifter/forskrift-2002-09-13-995.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-09-13-995) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-09-13-995.md) |
| [Delegering av myndighet til Klima- og miljødepartementet etter miljøinformasjons](../forskrifter/forskrift-2003-12-05-1432.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-05-1432) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-05-1432.md) |
| [Delegering av myndighet til Longyearbyen lokalstyre etter svalbardmiljøloven](../forskrifter/forskrift-2025-01-31-127.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-31-127) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-31-127.md) |
| [Delegering av myndighet til Miljødirektoratet](../forskrifter/forskrift-2013-03-15-283.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-03-15-283) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-03-15-283.md) |
| [Delegering av myndighet til Miljødirektoratet til å behandle klager på statsforv](../forskrifter/forskrift-2022-12-19-2289.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-19-2289) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-19-2289.md) |
| [Delegering av myndighet til Riksantikvaren etter lov om kulturminner § 20.](../forskrifter/forskrift-2005-07-01-751.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-07-01-751) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-07-01-751.md) |
| [Delegering av myndighet til Sjøfartsdirektoratet etter lov av 9. juni 1903 nr. 7](../forskrifter/forskrift-1980-01-08-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-01-08-1) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-01-08-1.md) |
| [Delegering av myndighet til Sjøfartsdirektoratet etter skipssikkerhetsloven og l](../forskrifter/forskrift-2007-06-29-849.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-849) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-849.md) |
| [Delegering av myndighet til Statens forurensningstilsyn etter produktkontrollove](../forskrifter/forskrift-2009-04-05-574.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-04-05-574) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-04-05-574.md) |
| [Delegering av myndighet til Statens forurensningstilsyn til å fastsette forskrif](../forskrifter/forskrift-2009-03-27-573.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-03-27-573) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-03-27-573.md) |
| [Delegering av myndighet til Statens forurensningstilsyn til å fastsette gebyr i ](../forskrifter/forskrift-1997-11-21-1502.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-11-21-1502) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-11-21-1502.md) |
| [Delegering av myndighet til endring i forskrift 1. september 2023 nr. 1388 om ti](../forskrifter/forskrift-2023-11-03-2426.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-03-2426) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-03-2426.md) |
| [Delegering av myndighet til fylkesmannen etter lov om laksefisk og innlandsfisk ](../forskrifter/forskrift-1993-02-24-4337.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-02-24-4337) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-02-24-4337.md) |
| [Delegering av myndighet til fylkesmennene til å sette i kraft § 26 tredje ledd i](../forskrifter/forskrift-1989-08-10-1428.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-08-10-1428) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-08-10-1428.md) |
| [Delegering av myndighet til kommunene etter forskrift om fiskeravgift.](../forskrifter/forskrift-1996-01-19-1469.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-01-19-1469) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-01-19-1469.md) |
| [Delegering av myndighet til å fastsette forskrifter etter skipssikkerhetsloven §](../forskrifter/forskrift-2017-08-29-1317.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-08-29-1317) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-08-29-1317.md) |
| [Delegering av myndigheten etter lakse- og innlandsfiskloven § 13 til Miljødirekt](../forskrifter/forskrift-2022-04-25-621.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-25-621) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-25-621.md) |
| [Delegering til Longyearbyen lokalstyre av myndighet etter forskrift om forurensi](../forskrifter/forskrift-2020-12-22-3401.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-22-3401) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-22-3401.md) |
| [Delvis ikrafttredelse av lov av 11. juni 1993 nr. 107 om endringer i lov av 13. ](../forskrifter/forskrift-1993-06-11-785.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-06-11-785) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-06-11-785.md) |
| [Delvis ikrafttredelse av lov av 29. mai 1981 nr. 38 om viltet. Delegering av myn](../forskrifter/forskrift-1982-04-02-592.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-04-02-592) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-04-02-592.md) |
| [Erklæring angående beskyttelse av kulturverdier i tilfelle av væpnet konflikt.](../forskrifter/forskrift-1952-12-11-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1952-12-11-2) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1952-12-11-2.md) |
| [Forskrift for bruk av motorkjøretøyer i utmark og på islagte vassdrag](../forskrifter/forskrift-1988-05-15-356.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-05-15-356) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-05-15-356.md) |
| [Forskrift om CO2-kompensasjon for industrien for perioden 2021–2030](../forskrifter/forskrift-2024-12-19-3395.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-19-3395) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-19-3395.md) |
| [Forskrift om EU-gjødselvarer (EU-gjødselvareforskriften)](../forskrifter/forskrift-2024-03-06-538.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-06-538) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-06-538.md) |
| [Forskrift om Klagenemnda for miljøinformasjon](../forskrifter/forskrift-2003-12-14-1572.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-14-1572) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-14-1572.md) |
| [Forskrift om Marka (markalovforskriften)](../forskrifter/forskrift-2015-09-04-1032.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-04-1032) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-04-1032.md) |
| [Forskrift om Miljøvedtaksregisteret](../forskrifter/forskrift-2013-06-14-643.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-14-643) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-14-643.md) |
| [Forskrift om Van Mijenfjorden nasjonalpark på Svalbard](../forskrifter/forskrift-2021-06-18-1980.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-18-1980) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-18-1980.md) |
| [Forskrift om avfallshåndtering og avfalls- og avløpsgebyrer i Longyearbyen plano](../forskrifter/forskrift-2023-03-01-435.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-03-01-435) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-03-01-435.md) |
| [Forskrift om ballastvannbehandling på skip og flyttbare innretninger](../forskrifter/forskrift-2017-09-08-1368.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-08-1368) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-08-1368.md) |
| [Forskrift om begrensning av forurensning (forurensningsforskriften)](../forskrifter/forskrift-2004-06-01-931.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-01-931) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-01-931.md) |
| [Forskrift om begrensning i bruk av helse- og miljøfarlige kjemikalier og andre p](../forskrifter/forskrift-2004-06-01-922.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-01-922) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-01-922.md) |
| [Forskrift om beskyttelse av tradisjonell kunnskap knyttet til genetisk materiale](../forskrifter/forskrift-2016-11-25-1367.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-11-25-1367) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-11-25-1367.md) |
| [Forskrift om biocider (Biocidforskriften)](../forskrifter/forskrift-2017-04-18-480.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-18-480) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-18-480.md) |
| [Forskrift om bruk av kommunens myndighet etter lov om motorferdsel i utmark og v](../forskrifter/forskrift-1988-03-14-225.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-03-14-225) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-03-14-225.md) |
| [Forskrift om bruk av lov 19. juni 2009 nr. 100 om forvaltning av naturens mangfo](../forskrifter/forskrift-2018-06-15-890.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-15-890) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-15-890.md) |
| [Forskrift om båndtvang for hund på Svalbard](../forskrifter/forskrift-2002-06-28-651.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-28-651) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-28-651.md) |
| [Forskrift om definisjon av marin gassolje i svalbardmiljøloven § 82a](../forskrifter/forskrift-2021-12-13-3514.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-13-3514) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-13-3514.md) |
| [Forskrift om deklarering av kjemikalier til produktregisteret (deklareringsforsk](../forskrifter/forskrift-2015-05-19-541.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-19-541) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-19-541.md) |
| [Forskrift om delegering av myndighet etter naturvernloven m.v. til Klima- og mil](../forskrifter/forskrift-1987-07-03-572.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-07-03-572) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-07-03-572.md) |
| [Forskrift om dragehode (Dracocephalum ruyschiana) som prioritert art](../forskrifter/forskrift-2011-05-20-517.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-517) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-517.md) |
| [Forskrift om drift av akvakulturanlegg (akvakulturdriftsforskriften)](../forskrifter/forskrift-2008-06-17-822.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-17-822) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-17-822.md) |
| [Forskrift om dverggås (Anser erythropus) som prioritert art](../forskrifter/forskrift-2011-05-20-518.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-518) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-518.md) |
| [Forskrift om dvergålegras (Zostera noltei) som prioritert art](../forskrifter/forskrift-2015-05-22-546.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-22-546) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-22-546.md) |
| [Forskrift om ekstraordinære tiltak i fisket etter anadrome laksefisk i vassdrag ](../forskrifter/forskrift-2026-07-09-1544.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-07-09-1544) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-07-09-1544.md) |
| [Forskrift om elfenbenslav som prioritert art](../forskrifter/forskrift-2020-12-04-2613.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-04-2613) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-04-2613.md) |
| [Forskrift om elvesandjeger (Cicindela maritima) som prioritert art](../forskrifter/forskrift-2011-05-20-519.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-519) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-519.md) |
| [Forskrift om endring i forskrift om begrensning i bruk av helse- og miljøfarlige](../forskrifter/forskrift-2024-11-25-3026.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-25-3026) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-25-3026.md) |
| [Forskrift om endring i forskrift om faglig ansvarsfordeling mv. etter kulturminn](../forskrifter/forskrift-2004-12-20-1718.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-20-1718) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-20-1718.md) |
| [Forskrift om endring i forskrift om fiske etter anadrome laksefisk i sjøen](../forskrifter/forskrift-2024-05-20-1009.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-20-1009) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-20-1009.md) |
| [Forskrift om endring i forskrift om sikkerhet ved leketøy (leketøyforskriften)](../forskrifter/forskrift-2026-05-07-763.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-07-763) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-07-763.md) |
| [Forskrift om endring i forskrift om utføring av aktiviteter i petroleumsvirksomh](../forskrifter/forskrift-2024-12-18-3263.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-18-3263) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-18-3263.md) |
| [Forskrift om endringer i forskrift om fiske etter anadrome laksefisk i vassdrag](../forskrifter/forskrift-2024-05-20-1548.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-20-1548) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-20-1548.md) |
| [Forskrift om eremitt (Osmoderma eremita) som prioritert art](../forskrifter/forskrift-2011-05-20-520.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-520) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-520.md) |
| [Forskrift om erstatning for tap og følgekostnader når tamrein blir drept eller s](../forskrifter/forskrift-2001-05-04-468.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-05-04-468) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-05-04-468.md) |
| [Forskrift om erstatning når husdyr blir drept eller skadet av rovvilt](../forskrifter/forskrift-2014-05-30-677.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-05-30-677) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-05-30-677.md) |
| [Forskrift om etablering og drift av kultiveringsanlegg for fisk og kreps](../forskrifter/forskrift-1992-12-30-1232.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-30-1232) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-30-1232.md) |
| [Forskrift om fangst av elvemusling](../forskrifter/forskrift-1992-12-30-1230.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-30-1230) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-30-1230.md) |
| [Forskrift om fastsetting av myndighet mv. etter kulturminneloven](../forskrifter/forskrift-2019-02-15-127.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-02-15-127) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-02-15-127.md) |
| [Forskrift om ferdselsbegrensning i Nyrøysaområdet på Bouvetøya.](../forskrifter/forskrift-2005-06-24-687.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-24-687) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-24-687.md) |
| [Forskrift om ferdselsforbud ved automatisk freda kulturminner ved Midterhuken, B](../forskrifter/forskrift-2009-09-23-1220.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-09-23-1220) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-09-23-1220.md) |
| [Forskrift om ferskvannskreps.](../forskrifter/forskrift-2001-07-13-833.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-07-13-833) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-07-13-833.md) |
| [Forskrift om fiske etter anadrome laksefisk i sjøen](../forskrifter/forskrift-2021-03-15-797.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-797) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-797.md) |
| [Forskrift om fiske etter anadrome laksefisk i vassdrag](../forskrifter/forskrift-2021-03-15-798.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-798) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-798.md) |
| [Forskrift om fiske etter innlandsfisk mv. og fangst av kreps (innlandsfiskeforsk](../forskrifter/forskrift-2009-06-26-851.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-26-851) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-26-851.md) |
| [Forskrift om fiske etter røye på Svalbard i 2026](../forskrifter/forskrift-2026-01-07-12.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-07-12) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-07-12.md) |
| [Forskrift om fiskeravgift](../forskrifter/forskrift-1993-06-15-532.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-06-15-532) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-06-15-532.md) |
| [Forskrift om fjellrev (Vulpes lagopus) som prioritert art](../forskrifter/forskrift-2015-01-23-60.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-01-23-60) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-01-23-60.md) |
| [Forskrift om forbud mot bruk av mineralolje til oppvarming av bygninger og fossi](../forskrifter/forskrift-2018-06-28-1060.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-28-1060) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-28-1060.md) |
| [Forskrift om forbud mot omsetning i Norge av bestemte genmodifiserte produkter.](../forskrifter/forskrift-2000-12-15-1268.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-15-1268) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-15-1268.md) |
| [Forskrift om forbud mot utslipp av kloakk fra fritidsbåter i Oslofjorden](../forskrifter/forskrift-2024-05-31-886.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-31-886) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-31-886.md) |
| [Forskrift om forurensning og avfall på Svalbard](../forskrifter/forskrift-2020-07-03-1517.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-03-1517) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-03-1517.md) |
| [Forskrift om forurensningslovens anvendelse på radioaktiv forurensning og radioa](../forskrifter/forskrift-2010-11-01-1394.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-01-1394) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-01-1394.md) |
| [Forskrift om forvaltning av rovvilt](../forskrifter/forskrift-2005-03-18-242.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-03-18-242) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-03-18-242.md) |
| [Forskrift om forvaltning av vilt og ferskvannsfisk på Svalbard og Jan Mayen](../forskrifter/forskrift-1978-08-11-3765.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-08-11-3765) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-08-11-3765.md) |
| [Forskrift om framleie av fiskerett.](../forskrifter/forskrift-1993-06-25-570.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-06-25-570) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-06-25-570.md) |
| [Forskrift om fredning av Bjørnøya naturreservat på Svalbard](../forskrifter/forskrift-2002-08-16-903.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-08-16-903) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-08-16-903.md) |
| [Forskrift om fredning av Bouvetøya med tilliggende territorialfarvann som naturr](../forskrifter/forskrift-1971-12-17-9.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-12-17-9) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-12-17-9.md) |
| [Forskrift om fredning av Festningen geotopvernområde på Svalbard](../forskrifter/forskrift-2003-09-26-1190.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-26-1190) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-26-1190.md) |
| [Forskrift om fredning av Hopen naturreservat på Svalbard](../forskrifter/forskrift-2003-09-26-1185.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-26-1185) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-26-1185.md) |
| [Forskrift om fredning av Indre Wijdefjorden nasjonalpark på Svalbard](../forskrifter/forskrift-2005-09-09-1046.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-09-09-1046) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-09-09-1046.md) |
| [Forskrift om fredning av Jan Mayen naturreservat](../forskrifter/forskrift-2010-11-19-1456.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-19-1456) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-19-1456.md) |
| [Forskrift om fredning av Masimjelt (Oxytropis deflexa) og Purpurkarse (Braya pur](../forskrifter/forskrift-1983-02-25-512.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-02-25-512) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-02-25-512.md) |
| [Forskrift om fredning av Nordre Isfjorden nasjonalpark på Svalbard](../forskrifter/forskrift-2003-09-26-1187.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-26-1187) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-26-1187.md) |
| [Forskrift om fredning av Ossian Sars naturreservat](../forskrifter/forskrift-2003-09-26-1188.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-26-1188) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-26-1188.md) |
| [Forskrift om fredning av Sassen-Bünsow Land nasjonalpark på Svalbard](../forskrifter/forskrift-2003-09-26-1189.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-26-1189) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-26-1189.md) |
| [Forskrift om fredning av bygninger og anlegg i Landsverneplan for Forsvaret.](../forskrifter/forskrift-2004-05-06-718.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-05-06-718) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-05-06-718.md) |
| [Forskrift om fredning av mistelteinen. Delegering av myndighet.](../forskrifter/forskrift-1976-10-29-3763.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-10-29-3763) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-10-29-3763.md) |
| [Forskrift om fredning av statens kulturhistoriske eiendommer](../forskrifter/forskrift-2011-11-09-1088.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-11-09-1088) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-11-09-1088.md) |
| [Forskrift om fredning av truede arter](../forskrifter/forskrift-2001-12-21-1525.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-21-1525) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-21-1525.md) |
| [Forskrift om fredning for Moffen naturreservat på Svalbard](../forskrifter/forskrift-1983-06-03-1029.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-06-03-1029) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-06-03-1029.md) |
| [Forskrift om fremmede organismer](../forskrifter/forskrift-2015-06-19-716.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-716) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-716.md) |
| [Forskrift om frivillig deltakelse for organisasjoner i en fellesskapsordning for](../forskrifter/forskrift-2006-05-03-484.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-05-03-484) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-05-03-484.md) |
| [Forskrift om fylkeskommunenes oppgaver innenfor friluftslivsområdet](../forskrifter/forskrift-2019-09-30-1310.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-30-1310) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-30-1310.md) |
| [Forskrift om fysiske tiltak i vassdrag](../forskrifter/forskrift-2004-11-15-1468.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-11-15-1468) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-11-15-1468.md) |
| [Forskrift om gebyr til statskassen for arbeid med kontroll etter produktkontroll](../forskrifter/forskrift-2024-04-17-649.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-04-17-649) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-04-17-649.md) |
| [Forskrift om gjennomføring av flertallsvedtak vedrørende organisering og drift a](../forskrifter/forskrift-2000-05-03-378.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-05-03-378) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-05-03-378.md) |
| [Forskrift om gjenvinning av skip og flyttbare innretninger](../forskrifter/forskrift-2018-12-06-1813.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-06-1813) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-06-1813.md) |
| [Forskrift om gjenvinning og behandling av avfall (avfallsforskriften)](../forskrifter/forskrift-2004-06-01-930.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-01-930) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-01-930.md) |
| [Forskrift om grunnsatser for tap av tamrein drept eller skadet av rovvilt reindr](../forskrifter/forskrift-2026-06-23-1324.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-23-1324) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-23-1324.md) |
| [Forskrift om honningblom (Herminium monorchis) som prioritert art](../forskrifter/forskrift-2011-05-20-521.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-521) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-521.md) |
| [Forskrift om håndtering av dyrekadaver ved utbrudd av smittsomme dyresjukdommer](../forskrifter/forskrift-2008-05-07-438.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-07-438) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-07-438.md) |
| [Forskrift om høsting på Svalbard](../forskrifter/forskrift-2002-06-24-712.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-24-712) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-24-712.md) |
| [Forskrift om ikrafttredelse av kap. 11 i lov av 8. juni 1979 nr. 49 om endringer](../forskrifter/forskrift-1979-10-12-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1979-10-12-1) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1979-10-12-1.md) |
| [Forskrift om innførsel, utførsel, besittelse mv. av truede arter av vill fauna o](../forskrifter/forskrift-2018-06-15-889.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-15-889) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-15-889.md) |
| [Forskrift om inngrep på åpent hav og i Norges økonomiske sone i tilfelle av havf](../forskrifter/forskrift-1997-09-19-1061.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-09-19-1061) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-09-19-1061.md) |
| [Forskrift om jakt, felling, fangst og fiske i statsallmenning](../forskrifter/forskrift-2021-03-11-681.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-11-681) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-11-681.md) |
| [Forskrift om jakt, felling, fangst og fiske på statsgrunn utenfor statsallmennin](../forskrifter/forskrift-2007-08-20-987.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-08-20-987) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-08-20-987.md) |
| [Forskrift om jakt- og fangsttider samt sanking av egg og dun for jaktsesongene f](../forskrifter/forskrift-2022-01-21-128.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-21-128) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-21-128.md) |
| [Forskrift om klassifisering, merking og emballering av stoffer og stoffblandinge](../forskrifter/forskrift-2012-06-16-622.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-16-622) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-16-622.md) |
| [Forskrift om klinisk utprøving og utlevering av GMO-legemidler til behandling el](../forskrifter/forskrift-2020-10-23-2124.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-23-2124) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-23-2124.md) |
| [Forskrift om klippeblåvinge (Scolitantides orion) som prioritert art](../forskrifter/forskrift-2011-05-20-522.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-522) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-522.md) |
| [Forskrift om kommunens myndighet etter forurensningsloven](../forskrifter/forskrift-2024-12-20-3400.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3400) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3400.md) |
| [Forskrift om konsekvensutredning etter genteknologiloven](../forskrifter/forskrift-2005-12-16-1495.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1495) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1495.md) |
| [Forskrift om konsekvensutredninger](../forskrifter/forskrift-2017-06-21-854.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-21-854) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-21-854.md) |
| [Forskrift om konsekvensutredninger og avgrensing av planområdene på Svalbard](../forskrifter/forskrift-2002-06-28-650.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-28-650) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-28-650.md) |
| [Forskrift om krav til klimagassintensitet for skip som brukes i forbindelse med ](../forskrifter/forskrift-2026-05-12-793.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-12-793) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-12-793.md) |
| [Forskrift om kvoteplikt og handel med kvoter for utslipp av klimagasser (klimakv](../forskrifter/forskrift-2004-12-23-1851.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-23-1851) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-23-1851.md) |
| [Forskrift om lagring og bruk av gjødsel mv.](../forskrifter/forskrift-2025-01-29-115.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-29-115) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-29-115.md) |
| [Forskrift om leiropphold på Svalbard](../forskrifter/forskrift-2002-06-27-731.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-27-731) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-27-731.md) |
| [Forskrift om maskiner](../forskrifter/forskrift-2009-05-20-544.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-05-20-544) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-05-20-544.md) |
| [Forskrift om merking, transport, import og eksport av genmodifiserte organismer.](../forskrifter/forskrift-2005-09-02-1009.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-09-02-1009) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-09-02-1009.md) |
| [Forskrift om midlertidig ordning for energitilskudd til næringslivet som følge a](../forskrifter/forskrift-2022-11-21-1994.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-21-1994) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-21-1994.md) |
| [Forskrift om miljøavgift for tilreisende til Svalbard](../forskrifter/forskrift-2006-12-22-1532.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-22-1532) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-22-1532.md) |
| [Forskrift om miljømessig sikkerhet for skip og flyttbare innretninger](../forskrifter/forskrift-2012-05-30-488.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-30-488) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-30-488.md) |
| [Forskrift om miljøvennlig utforming av energirelaterte produkter (økodesignforsk](../forskrifter/forskrift-2011-02-23-190.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-23-190) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-23-190.md) |
| [Forskrift om miljøvern og sikkerhet i Antarktis](../forskrifter/forskrift-2013-04-26-412.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-04-26-412) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-04-26-412.md) |
| [Forskrift om motorferdsel på Svalbard](../forskrifter/forskrift-2002-06-24-723.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-24-723) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-24-723.md) |
| [Forskrift om myndighet til Klima- og miljødepartementet etter naturvernloven (MI](../forskrifter/forskrift-1990-07-13-554.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-07-13-554) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-07-13-554.md) |
| [Forskrift om nasjonalparkene Sør-Spitsbergen, Forlandet og Nordvest-Spitsbergen,](../forskrifter/forskrift-2014-04-04-377.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-04-04-377) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-04-04-377.md) |
| [Forskrift om nedsenking av garnredskap](../forskrifter/forskrift-2003-06-20-737.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-20-737) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-20-737.md) |
| [Forskrift om omsetning av tømmer og treprodukter med opprinnelse utenfor Norge](../forskrifter/forskrift-2015-04-24-406.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-24-406) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-24-406.md) |
| [Forskrift om oppgaveplikt og om redskaper som er tillatt benyttet ved fiske ette](../forskrifter/forskrift-2003-02-25-256.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-25-256) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-25-256.md) |
| [Forskrift om opprettelse av nasjonalparker, naturresevater og fuglereservater, S](../forskrifter/forskrift-1973-06-01-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1973-06-01-1) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1973-06-01-1.md) |
| [Forskrift om overføring av forvaltningsansvar for naturvernområder. Delegering a](../forskrifter/forskrift-1983-07-26-1385.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-07-26-1385) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-07-26-1385.md) |
| [Forskrift om overgangsbestemmelser etter naturmangfoldloven § 77 i forbindelse m](../forskrifter/forskrift-2010-10-15-1339.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-10-15-1339) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-10-15-1339.md) |
| [Forskrift om overgangsbestemmelser ved ikrafttreden av lov om miljøvern på Svalb](../forskrifter/forskrift-2002-06-28-649.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-28-649) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-28-649.md) |
| [Forskrift om overtredelsesgebyr etter lakse- og innlandsfiskloven](../forskrifter/forskrift-2021-06-01-1741.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-01-1741) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-01-1741.md) |
| [Forskrift om overtredelsesgebyr etter motorferdselloven](../forskrifter/forskrift-2024-02-27-355.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-27-355) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-27-355.md) |
| [Forskrift om overtredelsesgebyr etter svalbardmiljøloven § 96a](../forskrifter/forskrift-2024-02-06-224.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-06-224) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-06-224.md) |
| [Forskrift om overtredelsesgebyr for overtredelser av bestemmelser i REACH-forskr](../forskrifter/forskrift-2023-09-29-1568.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-29-1568) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-29-1568.md) |
| [Forskrift om pliktig organisering og drift av vassdrag med anadrome laksefisk](../forskrifter/forskrift-2013-06-25-761.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-25-761) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-25-761.md) |
| [Forskrift om rammer for vannforvaltningen](../forskrifter/forskrift-2006-12-15-1446.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-15-1446) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-15-1446.md) |
| [Forskrift om reduksjon av utslipp av bensindamp](../forskrifter/forskrift-1999-02-10-206.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-02-10-206) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-02-10-206.md) |
| [Forskrift om registrering og merking av eldre preparater av dødt vilt.](../forskrifter/forskrift-2005-03-21-247.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-03-21-247) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-03-21-247.md) |
| [Forskrift om registrering, vurdering, godkjenning og begrensning av kjemikalier ](../forskrifter/forskrift-2008-05-30-516.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-30-516) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-30-516.md) |
| [Forskrift om rovdyravvisende gjerde](../forskrifter/forskrift-2012-06-22-652.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-22-652) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-22-652.md) |
| [Forskrift om rød skogfrue (Cephalanthera rubra) som prioritert art](../forskrifter/forskrift-2011-05-20-523.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-523) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-523.md) |
| [Forskrift om satser for avgift for jakt-, fangst- og fiskekort m.m. på Svalbard.](../forskrifter/forskrift-2006-12-01-1578.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-01-1578) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-01-1578.md) |
| [Forskrift om sikkerhet ved leketøy (leketøyforskriften)](../forskrifter/forskrift-2013-11-18-1403.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-18-1403) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-18-1403.md) |
| [Forskrift om skadefelling, dødt vilt og bruk av vilt i oppdrett, forskning og dy](../forskrifter/forskrift-2020-04-01-565.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-01-565) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-01-565.md) |
| [Forskrift om skredmjelt (Oxytropis campestris ssp. scotica) som prioritert art](../forskrifter/forskrift-2015-05-29-561.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-29-561) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-29-561.md) |
| [Forskrift om smittefarlig avfall fra helsetjeneste og dyrehelsetjeneste mv.](../forskrifter/forskrift-2005-10-11-1196.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-10-11-1196) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-10-11-1196.md) |
| [Forskrift om styring og opplysningsplikt i petroleumsvirksomheten og på enkelte ](../forskrifter/forskrift-2010-04-29-611.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-29-611) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-29-611.md) |
| [Forskrift om svarthalespove (Limosa limosa) som prioritert art](../forskrifter/forskrift-2011-05-20-524.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-524) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-524.md) |
| [Forskrift om svartkurle (Nigritella nigra) som prioritert art](../forskrifter/forskrift-2015-05-29-562.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-29-562) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-29-562.md) |
| [Forskrift om tillatelse til bruk av beltebil.](../forskrifter/forskrift-2005-11-07-1264.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-07-1264) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-07-1264.md) |
| [Forskrift om tilskudd fra Svalbards miljøvernfond](../forskrifter/forskrift-2007-04-30-599.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-04-30-599) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-04-30-599.md) |
| [Forskrift om tilskudd til Nasjonale turiststier](../forskrifter/forskrift-2023-11-15-1847.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1847) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1847.md) |
| [Forskrift om tilskudd til anadrome laksefisk](../forskrifter/forskrift-2014-11-25-1530.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-25-1530) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-25-1530.md) |
| [Forskrift om tilskudd til automatisk fredete og andre arkeologiske kulturminner](../forskrifter/forskrift-2021-08-13-2507.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2507) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2507.md) |
| [Forskrift om tilskudd til besøkssenter for natur](../forskrifter/forskrift-2023-11-15-1846.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1846) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1846.md) |
| [Forskrift om tilskudd til besøkssenter for verdensarv](../forskrifter/forskrift-2023-11-15-1845.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1845) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1845.md) |
| [Forskrift om tilskudd til fagutvikling i fartøyvernet](../forskrifter/forskrift-2021-08-13-2512.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2512) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2512.md) |
| [Forskrift om tilskudd til fartøyvern](../forskrifter/forskrift-2021-08-13-2511.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2511) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2511.md) |
| [Forskrift om tilskudd til forebyggende tiltak mot rovviltskader og konfliktdempe](../forskrifter/forskrift-2024-12-12-3074.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-12-3074) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-12-3074.md) |
| [Forskrift om tilskudd til fredete kulturminner i privat eie](../forskrifter/forskrift-2021-08-13-2508.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2508) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2508.md) |
| [Forskrift om tilskudd til friluftslivsaktivitet](../forskrifter/forskrift-2023-11-15-1832.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1832) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1832.md) |
| [Forskrift om tilskudd til frivillige klima- og miljøorganisasjoner samt klima- o](../forskrifter/forskrift-2021-06-11-1928.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-11-1928) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-11-1928.md) |
| [Forskrift om tilskudd til klimatilpasning](../forskrifter/forskrift-2018-06-25-1169.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-25-1169) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-25-1169.md) |
| [Forskrift om tilskudd til klimatiltak i kommunene, fylkeskommunene og Longyearby](../forskrifter/forskrift-2017-10-26-1771.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-26-1771) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-26-1771.md) |
| [Forskrift om tilskudd til kommuner for å bedre tilgangen til strandsonen langs O](../forskrifter/forskrift-2022-09-20-1602.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-20-1602) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-20-1602.md) |
| [Forskrift om tilskudd til natur- og friluftslivstiltak i områder som er berørt a](../forskrifter/forskrift-2025-06-12-1551.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1551) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1551.md) |
| [Forskrift om tilskudd til naturrestaurering](../forskrifter/forskrift-2025-11-02-2228.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-02-2228) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-02-2228.md) |
| [Forskrift om tilskudd til nitrogenfjerning ved avløpsrenseanlegg](../forskrifter/forskrift-2023-09-01-1388.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-01-1388) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-01-1388.md) |
| [Forskrift om tilskudd til oppryddingstiltak i forurenset grunn og forurenset bun](../forskrifter/forskrift-2015-06-26-808.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-26-808) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-26-808.md) |
| [Forskrift om tilskudd til stavkirker, bygg og anlegg fra middelalderen, konserve](../forskrifter/forskrift-2021-08-13-2510.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2510) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2510.md) |
| [Forskrift om tilskudd til tekniske og industrielle kulturminner](../forskrifter/forskrift-2021-08-13-2509.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2509) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2509.md) |
| [Forskrift om tilskudd til tiltak for å ivareta natur](../forskrifter/forskrift-2024-10-04-2408.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-04-2408) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-04-2408.md) |
| [Forskrift om tilskudd til tiltak i Utvalgte kulturlandskap i jordbruket og verde](../forskrifter/forskrift-2019-12-18-2024.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-18-2024) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-18-2024.md) |
| [Forskrift om tilskudd til tiltak i statlig sikrede friluftslivsområder og område](../forskrifter/forskrift-2023-11-15-1848.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1848) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1848.md) |
| [Forskrift om tilskudd til tiltak mot marin forsøpling](../forskrifter/forskrift-2018-12-05-1812.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-05-1812) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-05-1812.md) |
| [Forskrift om tilskudd til vannmiljøtiltak, kalking og anadrom laksefisk](../forskrifter/forskrift-2024-10-04-2409.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-04-2409) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-04-2409.md) |
| [Forskrift om tilskudd til verdensarv](../forskrifter/forskrift-2021-08-13-2514.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2514) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2514.md) |
| [Forskrift om tilskudd til verdiskaping basert på naturarven](../forskrifter/forskrift-2014-11-25-1567.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-25-1567) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-25-1567.md) |
| [Forskrift om tilskudd til verdiskaping på kulturmiljøområdet](../forskrifter/forskrift-2021-08-13-2513.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2513) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2513.md) |
| [Forskrift om tilskudd til å styrke kunnskapen om og formidlingen av naturmangfol](../forskrifter/forskrift-2023-11-15-1887.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1887) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1887.md) |
| [Forskrift om trøndertorvmose (Sphagnum troendelagicum) som prioritert art](../forskrifter/forskrift-2015-05-29-563.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-29-563) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-29-563.md) |
| [Forskrift om utforming og utrustning av innretninger med mer i petroleumsvirksom](../forskrifter/forskrift-2010-04-29-634.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-29-634) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-29-634.md) |
| [Forskrift om utføring av aktiviteter i petroleumsvirksomheten (aktivitetsforskri](../forskrifter/forskrift-2010-04-29-613.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-29-613) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-29-613.md) |
| [Forskrift om utlegging av åte og fôring av vilt](../forskrifter/forskrift-2019-12-17-1878.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-17-1878) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-17-1878.md) |
| [Forskrift om utnytting i Norge av genetisk materiale med opprinnelse i andre lan](../forskrifter/forskrift-2022-06-17-1047.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-17-1047) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-17-1047.md) |
| [Forskrift om utsetting av fisk og andre ferskvannsorganismer for kultiveringsfor](../forskrifter/forskrift-1993-11-11-1020.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-11-11-1020) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-11-11-1020.md) |
| [Forskrift om utsetting av utenlandske treslag til skogbruksformål](../forskrifter/forskrift-2012-05-25-460.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-25-460) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-25-460.md) |
| [Forskrift om utvalgte naturtyper etter naturmangfoldloven](../forskrifter/forskrift-2011-05-13-512.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-13-512) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-13-512.md) |
| [Forskrift om utvidelse av det geografiske virkeområdet til forurensningsloven § ](../forskrifter/forskrift-1997-08-22-945.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-08-22-945) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-08-22-945.md) |
| [Forskrift om utøvelse av jakt, felling og fangst](../forskrifter/forskrift-2002-03-22-313.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-03-22-313) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-03-22-313.md) |
| [Forskrift om utøving av fiske etter anadrome laksefisk](../forskrifter/forskrift-2026-05-18-859.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-18-859) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-18-859.md) |
| [Forskrift om varsling ved eksport av visse farlige kjemikalier](../forskrifter/forskrift-2020-11-04-2293.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-04-2293) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-04-2293.md) |
| [Forskrift om vedtekter for Meteorologisk institutt](../forskrifter/forskrift-2025-02-28-393.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-28-393) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-28-393.md) |
| [Forskrift om vedtekter for Norsk kulturminnefond](../forskrifter/forskrift-2003-06-27-801.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-27-801) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-27-801.md) |
| [Forskrift om å begrense utslipp fra bygge- og anleggsplasser](../forskrifter/forskrift-2025-04-03-594.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-03-594) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-03-594.md) |
| [Forskrift om åpning for fiske etter anadrome laksefisk (åpningsforskriften)](../forskrifter/forskrift-2003-06-20-736.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-20-736) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-20-736.md) |
| [Forskrift om øvre rammer for overtredelsesgebyr etter naturmangfoldloven § 74](../forskrifter/forskrift-2020-12-11-2726.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2726) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2726.md) |
| [Forskrifter om fredning for sibirstjerne Aster sibiricus](../forskrifter/forskrift-1981-10-02-8783.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-10-02-8783) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-10-02-8783.md) |
| [Forskrifter om gjennomføring av lov om kontroll med produkter og forbrukertjenes](../forskrifter/forskrift-1977-08-05-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-08-05-2) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-08-05-2.md) |
| [Ikrafttredelse av lov av 13. mars 1981 nr. 6 om vern mot forurensninger og om av](../forskrifter/forskrift-1983-07-08-1245.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-07-08-1245) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-07-08-1245.md) |
| [Ikrafttredelse av lov av 15. mai 1992 nr. 47 om laksefisk og innlandsfisk m.v. §](../forskrifter/forskrift-1992-11-27-864.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-11-27-864) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-11-27-864.md) |
| [Ikrafttredelse av lov av 2. april 1993 nr. 38 om framstilling og bruk av genmodi](../forskrifter/forskrift-1993-08-20-811.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-20-811) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-20-811.md) |
| [Ikrafttredelse av lov av 31. mai 1974 nr. 17 om kommunale vass- og kloakkavgifte](../forskrifter/forskrift-1974-09-06-14.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1974-09-06-14) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1974-09-06-14.md) |
| [Kvalitetsnorm for ville bestander av atlantisk laks (Salmo salar)](../forskrifter/forskrift-2013-09-20-1109.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-09-20-1109) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-09-20-1109.md) |
| [Kvalitetsnorm for villrein (Rangifer tarandus)](../forskrifter/forskrift-2020-06-23-1298.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-23-1298) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-23-1298.md) |
| [Midlertidig forskrift for regulering av naturinngrep på Svalbard og Jan Mayen.](../forskrifter/forskrift-1971-05-28-8617.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-05-28-8617) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-05-28-8617.md) |
| [Naturmangfoldloven § 55 – Myndighet som klageinstans](../forskrifter/forskrift-2011-05-13-513.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-13-513) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-13-513.md) |
| [Opprettelse av Statens naturoppsyn og delegering av myndighet til Klima- og milj](../forskrifter/forskrift-1996-10-25-1008.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-10-25-1008) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-10-25-1008.md) |
| [Overføring av myndighet etter forurensningsloven § 85 fra Miljødirektoratet til ](../forskrifter/forskrift-2025-02-14-216.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-14-216) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-14-216.md) |
| [Overføring til Samferdselsdepartementet av myndighet etter plan- og bygningslove](../forskrifter/forskrift-1992-10-23-768.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-10-23-768) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-10-23-768.md) |
| [Res. om fredning av kongeørn og havørn hele året](../forskrifter/forskrift-1968-09-06-3.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1968-09-06-3) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1968-09-06-3.md) |
| [Sammenslåing av miljødirektorater](../forskrifter/forskrift-2013-03-08-276.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-03-08-276) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-03-08-276.md) |
| [Vedtak om fristutsettelse for å fremsette krav om erstatning ved vern av nasjona](../forskrifter/forskrift-2008-11-13-1693.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-11-13-1693) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-11-13-1693.md) |
| [Vedtak om nytt navn på Statens forurensningstilsyn](../forskrifter/forskrift-2009-11-27-1433.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-11-27-1433) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-11-27-1433.md) |
