# Kommunal- og distriktsdepartementet

*150 forskrifter*

Logglenkene viser eldre, uverifiserte rekonstruksjoner, ikke bekreftet forskriftstekst på en bestemt dato.

| Forskrift | Lovdata | Uverifisert rekonstruksjon |
|-----------|---------|-----------|
| [Delegering av Kongen sin forskriftskompetanse etter personopplysningsloven til K](../forskrifter/forskrift-2008-04-11-345.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-04-11-345) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-04-11-345.md) |
| [Delegering av Kongens myndighet etter finnmarksloven § 16 til Kommunal- og moder](../forskrifter/forskrift-2011-04-08-387.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-04-08-387) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-04-08-387.md) |
| [Delegering av Kongens myndighet etter kommuneloven § 31-4 til Kommunal- og moder](../forskrifter/forskrift-2018-12-20-2063.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2063) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2063.md) |
| [Delegering av Kongens myndighet etter lov om forsøk i offentlig forvaltning til ](../forskrifter/forskrift-1992-12-11-1050.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-11-1050) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-11-1050.md) |
| [Delegering av Kongens myndighet etter matrikkellova § 2 andre ledd til Kommunal-](../forskrifter/forskrift-2021-12-17-3634.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-17-3634) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-17-3634.md) |
| [Delegering av Kongens myndighet til å fastsette forskrifter etter plan- og bygni](../forskrifter/forskrift-2017-12-08-1949.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-08-1949) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-08-1949.md) |
| [Delegering av forskriftskompetanse etter plan- og bygningsloven til Direktoratet](../forskrifter/forskrift-2017-02-08-2182.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-02-08-2182) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-02-08-2182.md) |
| [Delegering av fullmakt til Finans- og tolldepartementet til å fastsette forskrif](../forskrifter/forskrift-1984-03-30-816.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-03-30-816) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-03-30-816.md) |
| [Delegering av kompetanse til å avgjøre klage på seksjoneringsvedtak](../forskrifter/forskrift-2017-10-25-2463.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-25-2463) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-25-2463.md) |
| [Delegering av kompetanse til å behandle seksjoneringssaker innenfor Longyearbyen](../forskrifter/forskrift-2018-02-16-233.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-02-16-233) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-02-16-233.md) |
| [Delegering av mynde til statsforvaltarene etter inndelingslova](../forskrifter/forskrift-2017-03-10-313.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-03-10-313) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-03-10-313.md) |
| [Delegering av myndigheit til å fastsetje føresegner i forskrift etter plan- og b](../forskrifter/forskrift-2024-06-21-1102.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-21-1102) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-21-1102.md) |
| [Delegering av myndighet etter lov 22. juni 2018 nr. 83 om kommuner og fylkeskomm](../forskrifter/forskrift-2022-07-05-1304.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-07-05-1304) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-07-05-1304.md) |
| [Delegering av myndighet etter lov 22. juni 2018 nr. 83 om kommuner og fylkeskomm](../forskrifter/forskrift-2019-08-30-1096.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-08-30-1096) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-08-30-1096.md) |
| [Delegering av myndighet etter lov om registrering av elektriske kraftledninger §](../forskrifter/forskrift-2013-12-13-1475.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-13-1475) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-13-1475.md) |
| [Delegering av myndighet etter lov om tinglysing § 12b](../forskrifter/forskrift-2013-12-13-1476.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-13-1476) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-13-1476.md) |
| [Delegering av myndighet etter lov om tinglysing § 38 annet ledd](../forskrifter/forskrift-2013-12-13-1473.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-13-1473) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-13-1473.md) |
| [Delegering av myndighet etter plan- og bygningsloven § 16-2 andre ledd til Kommu](../forskrifter/forskrift-2020-08-28-1782.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-08-28-1782) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-08-28-1782.md) |
| [Delegering av myndighet til Arbeids- og sosialdepartementet etter lov om interko](../forskrifter/forskrift-2006-08-18-991.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-08-18-991) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-08-18-991.md) |
| [Delegering av myndighet til Husbanken til å begjære påtale på statens vegne](../forskrifter/forskrift-2017-05-15-598.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-15-598) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-15-598.md) |
| [Delegering av myndighet til Kommunal- og arbeidsdepartementet etter lov om arbei](../forskrifter/forskrift-1995-02-10-120.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-02-10-120) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-02-10-120.md) |
| [Delegering av myndighet til Kommunal- og arbeidsdepartementet etter lov om brann](../forskrifter/forskrift-1995-06-30-601.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-06-30-601) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-06-30-601.md) |
| [Delegering av myndighet til Kommunal- og arbeidsdepartementet etter lov om brann](../forskrifter/forskrift-1996-07-19-702.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-702) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-702.md) |
| [Delegering av myndighet til Kommunal- og arbeidsdepartementet etter lov om tilsy](../forskrifter/forskrift-1995-08-04-692.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-08-04-692) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-08-04-692.md) |
| [Delegering av myndighet til Kommunal- og regionaldepartementet etter utlendingsl](../forskrifter/forskrift-2005-09-02-957.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-09-02-957) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-09-02-957.md) |
| [Delegering av myndighet til Kommunal- og regionaldepartementet etter valgloven §](../forskrifter/forskrift-2003-02-14-154.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-14-154) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-14-154.md) |
| [Delegering av myndighet til Kommunal- og regionaldepartementet og Miljøverndepar](../forskrifter/forskrift-2009-06-12-639.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-12-639) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-12-639.md) |
| [Delegering av myndighet til Miljøverndepartementet etter lov 27. juni 2008 nr. 7](../forskrifter/forskrift-2013-05-24-532.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-24-532) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-24-532.md) |
| [Delegering av myndighet til Miljøverndepartementet etter plan- og bygningslovens](../forskrifter/forskrift-1990-03-16-174.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-03-16-174) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-03-16-174.md) |
| [Delegering av myndighet til Valgdirektoratet etter valgloven, valgforskriften og](../forskrifter/forskrift-2024-11-05-2699.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-05-2699) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-05-2699.md) |
| [Delegering av myndighet til å avgjøre søknader om utlevering av taushetsbelagt i](../forskrifter/forskrift-2018-11-28-1770.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-11-28-1770) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-11-28-1770.md) |
| [Delegering av myndighet til å begjære påtale til Statens kartverk etter straffel](../forskrifter/forskrift-2014-04-11-541.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-04-11-541) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-04-11-541.md) |
| [Delegering av myndighet til å dispensere fra bestemmelsene i forskrift om avgift](../forskrifter/forskrift-2000-05-19-531.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-05-19-531) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-05-19-531.md) |
| [Delegering av myndighet til å dispensere fra lov 14. juni 1974 nr. 39 om eksplos](../forskrifter/forskrift-2000-09-01-891.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-09-01-891) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-09-01-891.md) |
| [Erstatning til ansatte i staten ved skade på eller tap av private eiendeler i fo](../forskrifter/forskrift-2017-10-27-1667.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-27-1667) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-27-1667.md) |
| [Forskrift for produksjons- og hjelpesystemer på produksjonsanlegg m.v. for utvin](../forskrifter/forskrift-1978-04-03-9460.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-04-03-9460) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-04-03-9460.md) |
| [Forskrift om Husleietvistutvalget](../forskrifter/forskrift-2016-06-21-765.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-21-765) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-21-765.md) |
| [Forskrift om Kommunal- og distriktsdepartementets tilskot til kompetanse og arbe](../forskrifter/forskrift-2025-04-02-576.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-02-576) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-02-576.md) |
| [Forskrift om Kommunal- og distriktsdepartementets tilskudd til FoU-program innen](../forskrifter/forskrift-2023-02-20-222.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-02-20-222) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-02-20-222.md) |
| [Forskrift om Kommunal- og distriktsdepartementets tilskudd til Forskningsbasert ](../forskrifter/forskrift-2022-02-11-250.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-02-11-250) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-02-11-250.md) |
| [Forskrift om Kommunal- og distriktsdepartementets tilskuddsmidler til Arktis 203](../forskrifter/forskrift-2019-12-19-2112.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-19-2112) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-19-2112.md) |
| [Forskrift om Kommunal- og moderniseringsdepartementets distrikts- og regionalpol](../forskrifter/forskrift-2018-05-23-747.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-05-23-747) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-05-23-747.md) |
| [Forskrift om behandling av personopplysninger på det boligsosiale feltet](../forskrifter/forskrift-2023-08-17-1330.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-08-17-1330) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-08-17-1330.md) |
| [Forskrift om behandling av private forslag til detaljregulering etter plan- og b](../forskrifter/forskrift-2017-12-08-1950.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-08-1950) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-08-1950.md) |
| [Forskrift om beregning av samlet selvkost for kommunale og fylkeskommunale gebyr](../forskrifter/forskrift-2019-12-11-1731.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-11-1731) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-11-1731.md) |
| [Forskrift om bruk av det samiske flagget](../forskrifter/forskrift-2004-05-27-1087.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-05-27-1087) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-05-27-1087.md) |
| [Forskrift om bruk av standardisert søknad om seksjonering](../forskrifter/forskrift-2017-12-17-2119.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-17-2119) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-17-2119.md) |
| [Forskrift om bustøtte](../forskrifter/forskrift-2012-11-29-1283.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-29-1283) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-29-1283.md) |
| [Forskrift om byggesak (byggesaksforskriften)](../forskrifter/forskrift-2010-03-26-488.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-03-26-488) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-03-26-488.md) |
| [Forskrift om delegering etter plan- og bygningsloven av 14. juni 1985 nr. 77.](../forskrifter/forskrift-1986-06-20-1284.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-06-20-1284) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-06-20-1284.md) |
| [Forskrift om direkte valg til kommunedelsutvalg.](../forskrifter/forskrift-2003-01-03-8.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-03-8) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-03-8.md) |
| [Forskrift om driftstilskudd til organisasjoner for nasjonale minoriteter](../forskrifter/forskrift-2022-06-21-1137.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-21-1137) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-21-1137.md) |
| [Forskrift om eiendomsregistrering (matrikkelforskriften)](../forskrifter/forskrift-2009-06-26-864.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-26-864) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-26-864.md) |
| [Forskrift om eiendomsregistrering på Svalbard](../forskrifter/forskrift-2021-12-17-3633.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-17-3633) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-17-3633.md) |
| [Forskrift om elektronisk kommunikasjon ved tinglysing av salgspant og leasing av](../forskrifter/forskrift-2017-05-04-536.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-04-536) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-04-536.md) |
| [Forskrift om endring i forskrift om bustøtte](../forskrifter/forskrift-2022-12-22-2501.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-22-2501) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-22-2501.md) |
| [Forskrift om endring i forskrift om tekniske krav til byggverk (Byggteknisk fors](../forskrifter/forskrift-2026-09-11-1792.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-09-11-1792) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-09-11-1792.md) |
| [Forskrift om endringer i personopplysningsforskriften](../forskrifter/forskrift-2013-08-09-970.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-08-09-970) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-08-09-970.md) |
| [Forskrift om forbud mot vilkår om sosial infrastruktur i utbyggingsavtaler.](../forskrifter/forskrift-2006-04-20-453.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-04-20-453) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-04-20-453.md) |
| [Forskrift om forvaltningsområdet for samiske språk](../forskrifter/forskrift-2005-06-17-657.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-17-657) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-17-657.md) |
| [Forskrift om garantier og finans- og gjeldsforvaltning i kommuner og fylkeskommu](../forskrifter/forskrift-2019-11-18-1520.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-18-1520) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-18-1520.md) |
| [Forskrift om gebyr for tinglysing, registrering eller anmerkning i grunnboken og](../forskrifter/forskrift-2013-12-18-1634.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-18-1634) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-18-1634.md) |
| [Forskrift om gebyrregulativ for sentral godkjenning av foretak for ansvarsrett e](../forskrifter/forskrift-2010-06-29-989.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-29-989) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-29-989.md) |
| [Forskrift om hvilke kostnader som skal inn i et borettslags driftsbudsjett](../forskrifter/forskrift-2011-03-31-416.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-31-416) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-31-416.md) |
| [Forskrift om hvilke opplysninger som skal gis i melding om salg av leiegård.](../forskrifter/forskrift-1993-01-15-30.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-01-15-30) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-01-15-30.md) |
| [Forskrift om ikrafttredelse av lov 28. juni 1996 nr. 56. Delegering av myndighet](../forskrifter/forskrift-1996-06-28-616.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-06-28-616) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-06-28-616.md) |
| [Forskrift om infrastruktur for geografisk informasjon (geodataforskriften)](../forskrifter/forskrift-2012-08-08-797.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-08-08-797) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-08-08-797.md) |
| [Forskrift om innmåling, dokumentasjon og utlevering av geografisk informasjon om](../forskrifter/forskrift-2020-12-18-2986.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2986) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2986.md) |
| [Forskrift om iverksetting av matrikkelen](../forskrifter/forskrift-2007-02-09-151.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-02-09-151) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-02-09-151.md) |
| [Forskrift om kart, stedfestet informasjon, arealformål og kommunalt planregister](../forskrifter/forskrift-2025-01-20-52.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-20-52) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-20-52.md) |
| [Forskrift om klagenemnd for Husbanken](../forskrifter/forskrift-2012-10-31-1182.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-31-1182) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-31-1182.md) |
| [Forskrift om kommunale og fylkeskommunale budsjetter og regnskaper.](../forskrifter/forskrift-1990-03-01-715.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-03-01-715) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-03-01-715.md) |
| [Forskrift om kommunale og fylkeskommunale råd for eldre, personer med funksjonsn](../forskrifter/forskrift-2019-06-17-727.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-17-727) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-17-727.md) |
| [Forskrift om kommunalt rapporteringsregister (KOR-forskriften)](../forskrifter/forskrift-2019-11-18-1521.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-18-1521) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-18-1521.md) |
| [Forskrift om kompetansetilskudd til bærekraftig bolig- og byggkvalitet fra Husba](../forskrifter/forskrift-2011-02-23-194.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-23-194) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-23-194.md) |
| [Forskrift om konsekvensutredninger](../forskrifter/forskrift-2017-06-21-854.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-21-854) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-21-854.md) |
| [Forskrift om kontrollutvalg og revisjon](../forskrifter/forskrift-2019-06-17-904.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-17-904) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-17-904.md) |
| [Forskrift om lån fra Husbanken](../forskrifter/forskrift-2019-11-18-1546.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-18-1546) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-18-1546.md) |
| [Forskrift om lån til omsorgsboliger, sykehjemsplasser og lokaler for omsorgstilt](../forskrifter/forskrift-2003-07-10-957.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-10-957) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-10-957.md) |
| [Forskrift om minimumsavdrag på lån for kommuner, fylkeskommuner, kommunale og fy](../forskrifter/forskrift-2024-09-27-2348.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-27-2348) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-27-2348.md) |
| [Forskrift om minstekrav til sikringsordningar i burettslag](../forskrifter/forskrift-2010-12-15-1694.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-15-1694) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-15-1694.md) |
| [Forskrift om omsetning og dokumentasjon av heiser og sikkerhetskomponenter for h](../forskrifter/forskrift-2016-04-13-373.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-04-13-373) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-04-13-373.md) |
| [Forskrift om omsetning og dokumentasjon av produkter til byggverk](../forskrifter/forskrift-2013-12-17-1579.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-17-1579) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-17-1579.md) |
| [Forskrift om oppheving av forskrift om arealtilskott til privateide skoler, kirk](../forskrifter/forskrift-1987-02-06-71.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-02-06-71) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-02-06-71.md) |
| [Forskrift om ordningen for kollektiv oppreisning til romanifolket/taterne](../forskrifter/forskrift-2019-09-27-1277.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-27-1277) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-27-1277.md) |
| [Forskrift om overgangsbestemmelser for gjennomføring av lov om endringar i parti](../forskrifter/forskrift-2013-02-01-129.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-02-01-129) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-02-01-129.md) |
| [Forskrift om overgangsbestemmelser til ny kommunelov](../forskrifter/forskrift-2019-06-27-937.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-27-937) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-27-937.md) |
| [Forskrift om pensjonsordning for sametingsrepresentanter](../forskrifter/forskrift-2013-08-23-1006.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-08-23-1006) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-08-23-1006.md) |
| [Forskrift om prosjekttilskudd til nasjonale minoriteter](../forskrifter/forskrift-2020-01-13-40.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-13-40) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-13-40.md) |
| [Forskrift om rapportering fra kommuner og fylkeskommuner mv. (KOSTRA-forskriften](../forskrifter/forskrift-2019-10-18-1412.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-18-1412) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-18-1412.md) |
| [Forskrift om registrering av beslutninger om utlegg i Løsøreregisteret (utleggsr](../forskrifter/forskrift-2025-08-08-1616.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-08-1616) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-08-1616.md) |
| [Forskrift om registrering av regjeringsmedlemmers, statssekretærers og politiske](../forskrifter/forskrift-2012-11-30-1114.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-30-1114) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-30-1114.md) |
| [Forskrift om rett til å kreve seksjonering etter eierseksjonsloven § 9](../forskrifter/forskrift-2018-06-18-921.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-18-921) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-18-921.md) |
| [Forskrift om samvirke mellom bestemmelsen i plan- og bygningsloven 14. juni 1985](../forskrifter/forskrift-2009-06-15-669.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-15-669) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-15-669.md) |
| [Forskrift om tekniske krav til byggverk (Byggteknisk forskrift)](../forskrifter/forskrift-2017-06-19-840.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-19-840) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-19-840.md) |
| [Forskrift om tidsfrist for krav om lovlighetskontroll.](../forskrifter/forskrift-1993-01-13-4041.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-01-13-4041) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-01-13-4041.md) |
| [Forskrift om tildeling av myndighet til Nye Veier AS etter lov 27. juni 2008 nr.](../forskrifter/forskrift-2019-03-08-203.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-08-203) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-08-203.md) |
| [Forskrift om tilskot frå Merkur-programmet (Merkur-forskrifta)](../forskrifter/forskrift-2024-11-21-2989.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-21-2989) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-21-2989.md) |
| [Forskrift om tilskudd til boligtiltak](../forskrifter/forskrift-2026-03-26-506.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-26-506) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-26-506.md) |
| [Forskrift om tilskudd til etablering og tilpasning i distriktskommuner](../forskrifter/forskrift-2025-04-29-709.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-29-709) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-29-709.md) |
| [Forskrift om tilskudd til forsøk med nye boligmodeller fra Husbanken](../forskrifter/forskrift-2021-12-20-3779.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-20-3779) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-20-3779.md) |
| [Forskrift om tilskudd til informasjonstiltak ved valg til Stortinget, Sametinget](../forskrifter/forskrift-2020-10-13-2034.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-13-2034) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-13-2034.md) |
| [Forskrift om tilskudd til kompetansetiltak innen kart, plan og geodata](../forskrifter/forskrift-2025-04-08-633.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-08-633) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-08-633.md) |
| [Forskrift om tilskudd til kvensk språk og kvensk og norskfinsk kultur](../forskrifter/forskrift-2019-11-22-1570.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-22-1570) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-22-1570.md) |
| [Forskrift om tilskudd til utleieboliger fra Husbanken](../forskrifter/forskrift-2017-12-18-2235.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-18-2235) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-18-2235.md) |
| [Forskrift om tilskuddsordning forvaltet av Barentssekretariatet IKS](../forskrifter/forskrift-2024-02-07-234.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-07-234) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-07-234.md) |
| [Forskrift om tilskuddsordninger til omstilling og utvikling i områder med særlig](../forskrifter/forskrift-2024-04-03-556.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-04-03-556) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-04-03-556.md) |
| [Forskrift om tinglysing](../forskrifter/forskrift-1995-11-03-875.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-11-03-875) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-11-03-875.md) |
| [Forskrift om unntak fra husleieloven § 3-5](../forskrifter/forskrift-2009-06-02-628.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-02-628) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-02-628.md) |
| [Forskrift om utlevering, viderebruk og annen behandling av opplysninger fra grun](../forskrifter/forskrift-2013-12-18-1599.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-18-1599) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-18-1599.md) |
| [Forskrift om valg til Sametinget](../forskrifter/forskrift-2008-12-19-1480.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-19-1480) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-19-1480.md) |
| [Forskrift om valg til Stortinget, fylkesting og kommunestyrer (valgforskriften)](../forskrifter/forskrift-2024-11-05-2662.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-05-2662) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-05-2662.md) |
| [Forskrift om virkeområdet for distriktsrettet investeringsstøtte](../forskrifter/forskrift-2021-12-14-3661.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-14-3661) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-14-3661.md) |
| [Forskrift om visse forhold vedrørende de politiske partiene (partilovforskriften](../forskrifter/forskrift-2014-02-05-107.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-02-05-107) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-02-05-107.md) |
| [Forskrift om økonomiplan, årsbudsjett, årsregnskap og årsberetning for interkomm](../forskrifter/forskrift-2023-08-16-1327.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-08-16-1327) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-08-16-1327.md) |
| [Forskrift om økonomiplan, årsbudsjett, årsregnskap og årsberetning for kommuner ](../forskrifter/forskrift-2019-06-07-714.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-07-714) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-07-714.md) |
| [Forskrift til avhendingslova (tryggere bolighandel)](../forskrifter/forskrift-2021-06-08-1850.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-08-1850) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-08-1850.md) |
| [Forskrift til samelovens språkregler](../forskrifter/forskrift-2003-01-07-13.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-07-13) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-07-13.md) |
| [Fullmakt for Kommunal- og moderniseringsdepartementet til å fastsette og vedlike](../forskrifter/forskrift-2015-06-12-649.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-12-649) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-12-649.md) |
| [Fullmakt til å inngå og forvalte felles innkjøpsavtaler som er obligatoriske for](../forskrifter/forskrift-2021-09-03-2661.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-03-2661) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-03-2661.md) |
| [Ikraftsetjing av lov 5. mai 1995 nr. 20 og lov 28. juni 1996 nr. 55 om endringer](../forskrifter/forskrift-1997-03-21-228.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-21-228) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-21-228.md) |
| [Ikraftsetting av lov 8. mai 2009 nr. 27 om endringer i lov om planlegging og byg](../forskrifter/forskrift-2010-06-18-896.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-18-896) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-18-896.md) |
| [Ikrafttredelse av lov 23. mai 1997 nr. 31 om eierseksjoner (eierseksjonsloven). ](../forskrifter/forskrift-1997-12-05-1256.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-05-1256) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-05-1256.md) |
| [Ikrafttredelse av lov av 25. september 1992 nr. 107 om kommuner og fylkeskommune](../forskrifter/forskrift-1992-11-27-865.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-11-27-865) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-11-27-865.md) |
| [Instruks for statsforvaltere](../forskrifter/forskrift-1981-08-07-3642.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-08-07-3642) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-08-07-3642.md) |
| [Meddelelse om ikrafttredelse av lov 22. juni 2018 nr. 83 om kommuner og fylkesko](../forskrifter/forskrift-2019-10-03-1294.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-03-1294) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-03-1294.md) |
| [Midlertidig forskrift for elektriske anlegg på innretninger som anvendes til und](../forskrifter/forskrift-1985-07-26-1565.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-07-26-1565) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-07-26-1565.md) |
| [Midlertidig forskrift om tilskudd til kommunale næringsfond som følge av covid-1](../forskrifter/forskrift-2020-06-30-1437.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-30-1437) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-30-1437.md) |
| [Midlertidig forskrift om unntak fra plan- og bygningsloven for å håndtere høye a](../forskrifter/forskrift-2022-06-08-991.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-08-991) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-08-991.md) |
| [Overføring av Kommunal- og moderniseringsdepartementet si myndigheit etter kommu](../forskrifter/forskrift-2009-11-20-1386.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-11-20-1386) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-11-20-1386.md) |
| [Overføring av ansvaret for elektrisitetssikkerheten til Kommunaldepartementet m.](../forskrifter/forskrift-1990-12-14-991.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-12-14-991) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-12-14-991.md) |
| [Overføring av myndighet etter lov 27. juni 2008 nr. 71 om planlegging og byggesa](../forskrifter/forskrift-2015-06-19-670.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-670) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-670.md) |
| [Overføring av myndighet fra Miljøverndepartementet til Energidepartementet til å](../forskrifter/forskrift-2008-04-18-372.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-04-18-372) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-04-18-372.md) |
| [Overføring av myndighet til Energidepartementet etter plan- og bygningsloven § 1](../forskrifter/forskrift-2009-03-27-362.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-03-27-362) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-03-27-362.md) |
| [Overføring av myndighet til Olje- og energidepartementet etter lov om planleggin](../forskrifter/forskrift-2009-06-26-858.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-26-858) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-26-858.md) |
| [Refusjon av merutgifter og tap som følge av hevnaksjoner, som har sammenheng med](../forskrifter/forskrift-2020-12-11-2711.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2711) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2711.md) |
| [Retningslinjer for lokalisering av statlege arbeidsplassar og statleg tenestepro](../forskrifter/forskrift-2024-09-27-2305.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-27-2305) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-27-2305.md) |
| [Rikspolitiske retningslinjer for barn og planlegging](../forskrifter/forskrift-1995-09-20-4146.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-09-20-4146) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-09-20-4146.md) |
| [Rikspolitiske retningslinjer for vernede vassdrag](../forskrifter/forskrift-1994-11-10-1001.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-11-10-1001) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-11-10-1001.md) |
| [Sammenslåing av fylkesmannsembetet i Troms og fylkesmannsembetet i Finnmark fra ](../forskrifter/forskrift-2017-06-16-755.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-16-755) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-16-755.md) |
| [Statlige planretningslinjer for arealbruk og mobilitet](../forskrifter/forskrift-2025-01-24-69.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-24-69) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-24-69.md) |
| [Statlige planretningslinjer for differensiert forvaltning av strandsonen langs s](../forskrifter/forskrift-2021-05-28-1666.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-28-1666) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-28-1666.md) |
| [Statlige planretningslinjer for klima og energi](../forskrifter/forskrift-2024-12-20-3359.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3359) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3359.md) |
| [Tildeling av myndighet til statsforvalteren etter plan- og bygningsloven](../forskrifter/forskrift-2026-06-01-976.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-01-976) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-01-976.md) |
| [Vedtak om endring av namn for Statens bygningstekniske etat til Direktoratet for](../forskrifter/forskrift-2011-09-16-964.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-09-16-964) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-09-16-964.md) |
| [Vedtak om endring i delvis ikraftsetting av lov 17. juni 2005 nr. 101 om eigedom](../forskrifter/forskrift-2009-12-04-1453.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-04-1453) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-04-1453.md) |
| [Vedtak om etablering av koordineringsorgan for forvaltningens bruk av sikkerhets](../forskrifter/forskrift-2005-10-07-1117.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-10-07-1117) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-10-07-1117.md) |
| [Vedtak om innføring av matrikkelsystem](../forskrifter/forskrift-2009-04-25-975.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-04-25-975) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-04-25-975.md) |
| [Vedtak om sammenslåing av fylkesmannsembetet i Vest-Agder og fylkesmannsembetet ](../forskrifter/forskrift-2014-11-14-1425.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-14-1425) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-14-1425.md) |
| [Økonomireglement for Det Kongelige Hoff](../forskrifter/forskrift-2002-07-05-717.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-07-05-717) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-07-05-717.md) |
