# Kunnskapsdepartementet

*359 forskrifter*

Logglenkene viser eldre, uverifiserte rekonstruksjoner, ikke bekreftet forskriftstekst på en bestemt dato.

| Forskrift | Lovdata | Uverifisert rekonstruksjon |
|-----------|---------|-----------|
| [Ansgar Teologiske Høgskole status som høgskole](../forskrifter/forskrift-2011-06-24-649.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-06-24-649) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-06-24-649.md) |
| [Delegering av Kongens myndighet etter lov 1. april 2005 nr. 15 om universiteter ](../forskrifter/forskrift-2017-12-15-2115.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-15-2115) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-15-2115.md) |
| [Delegering av Kongens myndighet etter lov 10. juni 2005 nr. 51 om norsk statsbor](../forskrifter/forskrift-2021-06-18-1968.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-18-1968) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-18-1968.md) |
| [Delegering av Kongens myndighet etter universitets- og høyskoleloven § 1-2 tredj](../forskrifter/forskrift-2026-08-21-1652.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-08-21-1652) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-08-21-1652.md) |
| [Delegering av Kongens myndighet etter universitets- og høyskoleloven § 7-2](../forskrifter/forskrift-2012-02-03-126.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-02-03-126) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-02-03-126.md) |
| [Delegering av Kongens myndighet til å endre forskrift om Politihøgskolens virkso](../forskrifter/forskrift-2026-09-11-1772.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-09-11-1772) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-09-11-1772.md) |
| [Delegering av Kongens myndighet til å endre forskrift om tilpasning til universi](../forskrifter/forskrift-2026-04-17-603.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-17-603) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-17-603.md) |
| [Delegering av fullmakt m.o.t. endringar av hjelpestillingar, vitskaplege mellomg](../forskrifter/forskrift-1983-01-07-8.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-01-07-8) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-01-07-8.md) |
| [Delegering av fullmakt til Kyrkje-, utdannings- og forskingsdepartementet etter ](../forskrifter/forskrift-1998-01-23-73.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-01-23-73) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-01-23-73.md) |
| [Delegering av myndigheit etter lov om utdanningsstøtte til elever og studenter.](../forskrifter/forskrift-1999-03-05-241.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-03-05-241) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-03-05-241.md) |
| [Delegering av myndighet til Arbeids- og inkluderingsdepartementet etter statsbor](../forskrifter/forskrift-2006-06-30-755.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-755) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-755.md) |
| [Delegering av myndighet til Forsvarsdepartementet etter lov 8. juni 2018 nr. 28 ](../forskrifter/forskrift-2026-06-19-1145.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-19-1145) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-19-1145.md) |
| [Delegering av myndighet til Kirke-, utdannings- og forskningsdepartementet etter](../forskrifter/forskrift-1996-09-06-850.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-09-06-850) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-09-06-850.md) |
| [Delegering av myndighet til Kunnskapsdepartementet til å avslå søknader om endre](../forskrifter/forskrift-2015-10-30-1256.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-10-30-1256) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-10-30-1256.md) |
| [Delegering av myndighet til Utdannings- og forskningsdepartementet etter lov om ](../forskrifter/forskrift-2003-01-31-89.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-31-89) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-31-89.md) |
| [Eksamensreglement for Høgskulen for landbruk og bygdenæringar BA](../forskrifter/forskrift-2007-08-31-1133.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-08-31-1133) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-08-31-1133.md) |
| [Endring av navn på Kunsthøgskolen i Bergen til Kunst- og designhøgskolen i Berge](../forskrifter/forskrift-2012-02-03-125.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-02-03-125) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-02-03-125.md) |
| [Forskrift endring i forskrift om opptak til studier og emner ved Universitetet i](../forskrifter/forskrift-2026-05-19-1415.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-19-1415) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-19-1415.md) |
| [Forskrift for Fagskolen AOF Hordaland – Sogn og Fjordane](../forskrifter/forskrift-2017-12-14-2471.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-14-2471) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-14-2471.md) |
| [Forskrift for OSM Aviation Academy](../forskrifter/forskrift-2023-11-13-2011.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-13-2011) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-13-2011.md) |
| [Forskrift for bachelorstudiet Bevegelige bilder ved Nordland kunst- og filmfagsk](../forskrifter/forskrift-2017-02-15-2466.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-02-15-2466) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-02-15-2466.md) |
| [Forskrift for fagskolestudier ved Fagskolen TLA AS](../forskrifter/forskrift-2017-09-01-1416.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-01-1416) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-01-1416.md) |
| [Forskrift for fagskoleutdanning i yrkesdykking ved Høgskulen på Vestlandet](../forskrifter/forskrift-2017-06-15-1044.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-15-1044) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-15-1044.md) |
| [Forskrift for forskerlinjen i medisin ved Norges teknisk-naturvitenskapelige uni](../forskrifter/forskrift-2023-11-29-1935.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-29-1935) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-29-1935.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Nord universitet](../forskrifter/forskrift-2025-05-08-862.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-08-862) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-08-862.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Norges miljø- og biovi](../forskrifter/forskrift-2024-11-13-2941.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-13-2941) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-13-2941.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Norges teknisk-naturvi](../forskrifter/forskrift-2026-02-03-425.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-03-425) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-03-425.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Universitetet i Bergen](../forskrifter/forskrift-2025-02-13-284.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-13-284) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-13-284.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Universitetet i Oslo](../forskrifter/forskrift-2011-01-05-841.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-01-05-841) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-01-05-841.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Universitetet i Sørøst](../forskrifter/forskrift-2019-11-21-2304.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-21-2304) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-21-2304.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved VID vitenskapelige høg](../forskrifter/forskrift-2026-03-11-448.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-11-448) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-11-448.md) |
| [Forskrift for graden dr.philos. ved MF vitenskapelig høyskole](../forskrifter/forskrift-2018-08-30-1682.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-08-30-1682) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-08-30-1682.md) |
| [Forskrift for graden dr.philos. ved Universitetet i Stavanger](../forskrifter/forskrift-2019-06-13-1472.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-13-1472) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-13-1472.md) |
| [Forskrift for graden philosophiae doctor (Ph.D.) – med utfyllende bestemmelser f](../forskrifter/forskrift-2003-12-16-4680.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-16-4680) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-16-4680.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid ](../forskrifter/forskrift-2021-09-15-4051.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-15-4051) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-15-4051.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid ](../forskrifter/forskrift-2025-02-13-283.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-13-283) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-13-283.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid ](../forskrifter/forskrift-2022-08-29-1598.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-29-1598) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-29-1598.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid ](../forskrifter/forskrift-2025-06-12-1280.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1280) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1280.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Arkitektur- og designhøgsko](../forskrifter/forskrift-2016-10-26-1442.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-26-1442) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-26-1442.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Høgskolen i Molde, Vitenska](../forskrifter/forskrift-2026-01-28-149.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-28-149) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-28-149.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Høgskolen i Østfold](../forskrifter/forskrift-2024-09-17-3171.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-17-3171) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-17-3171.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Høyskolen Kristiania](../forskrifter/forskrift-2025-03-11-440.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-11-440) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-11-440.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved MF vitenskapelig høyskole](../forskrifter/forskrift-2012-06-05-645.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-05-645) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-05-645.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Nord universitet](../forskrifter/forskrift-2026-05-07-1167.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-07-1167) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-07-1167.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Norges Handelshøyskole](../forskrifter/forskrift-2025-01-29-126.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-29-126) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-29-126.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Norges miljø- og biovitensk](../forskrifter/forskrift-2024-11-13-3024.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-13-3024) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-13-3024.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Universitetet i Agder](../forskrifter/forskrift-2022-02-01-1149.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-02-01-1149) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-02-01-1149.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Universitetet i Bergen](../forskrifter/forskrift-2025-02-13-282.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-13-282) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-13-282.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Universitetet i Innlandet](../forskrifter/forskrift-2017-12-19-2396.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-19-2396) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-19-2396.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Universitetet i Oslo](../forskrifter/forskrift-2010-06-22-4998.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-22-4998) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-22-4998.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Universitetet i Stavanger](../forskrifter/forskrift-2025-06-12-1279.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1279) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1279.md) |
| [Forskrift for gradene philosophiae doctor (ph.d.) og philosophiae doctor i kunst](../forskrifter/forskrift-2026-02-03-387.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-03-387) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-03-387.md) |
| [Forskrift for integrert ph.d.-utdanning ved Universitetet i Agder (UiA)](../forskrifter/forskrift-2017-06-22-1145.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-22-1145) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-22-1145.md) |
| [Forskrift for masterstudiet ved Bergen Arkitekthøgskole](../forskrifter/forskrift-2019-03-04-179.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-04-179) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-04-179.md) |
| [Forskrift for medisinsk embetseksamen og medisinsk eksamen ved Universitetet i T](../forskrifter/forskrift-1976-03-22-8875.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-03-22-8875) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-03-22-8875.md) |
| [Forskrift for opptak, gjennomføring av studier, eksamen og klageregler for fagsk](../forskrifter/forskrift-2017-09-18-1634.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-18-1634) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-18-1634.md) |
| [Forskrift for opptak, studier og eksamen ved Høyskolen for yrkesfag AS](../forskrifter/forskrift-2020-01-08-906.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-08-906) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-08-906.md) |
| [Forskrift for opptak, studier og eksamen ved Imageakademiet](../forskrifter/forskrift-2020-02-14-146.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-14-146) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-14-146.md) |
| [Forskrift for studier og eksamen ved Lillehammer Institute of Music Production a](../forskrifter/forskrift-2016-07-04-1634.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-07-04-1634) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-07-04-1634.md) |
| [Forskrift om Nasjonalt kvalifikasjonsrammeverk for livslang læring og om henvisn](../forskrifter/forskrift-2017-11-08-1846.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-11-08-1846) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-11-08-1846.md) |
| [Forskrift om Politihøgskolens virksomhet og tilpasning til universitets- og høys](../forskrifter/forskrift-2026-09-11-1770.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-09-11-1770) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-09-11-1770.md) |
| [Forskrift om akkreditering av og tilsyn med høyere yrkesfaglig utdanning (fagsko](../forskrifter/forskrift-2020-04-23-853.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-23-853) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-23-853.md) |
| [Forskrift om ansvar for spesialpedagogisk hjelp for barn under opplæringspliktig](../forskrifter/forskrift-2017-06-22-1050.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-22-1050) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-22-1050.md) |
| [Forskrift om autorisasjonsprøven ved Norges Handelshøyskole for å bli statsautor](../forskrifter/forskrift-2021-06-17-2044.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-17-2044) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-17-2044.md) |
| [Forskrift om bachelorgrad ved Atlantis Medisinske Høgskole](../forskrifter/forskrift-2013-05-24-548.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-24-548) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-24-548.md) |
| [Forskrift om bachelorgrad ved Høgskolen i Buskerud](../forskrifter/forskrift-2006-06-21-1718.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-21-1718) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-21-1718.md) |
| [Forskrift om barnehagevirksomhet i Longyearbyen](../forskrifter/forskrift-2022-06-17-1219.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-17-1219) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-17-1219.md) |
| [Forskrift om behandling av personopplysninger i Lånekassen](../forskrifter/forskrift-2021-12-17-3713.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-17-3713) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-17-3713.md) |
| [Forskrift om behandling av personopplysninger i barnehagesektoren](../forskrifter/forskrift-2018-09-28-1479.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-28-1479) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-28-1479.md) |
| [Forskrift om de regionale forskningsfondene](../forskrifter/forskrift-2019-12-18-2110.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-18-2110) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-18-2110.md) |
| [Forskrift om eksamen ved Atlantis Medisinske Høgskole](../forskrifter/forskrift-2013-05-24-547.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-24-547) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-24-547.md) |
| [Forskrift om eksamen ved Norges Informasjonsteknologiske Høgskole](../forskrifter/forskrift-2005-12-16-1620.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1620) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1620.md) |
| [Forskrift om eksamen, studierett og grader ved Høgskolen i Østfold](../forskrifter/forskrift-2024-09-17-2231.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-17-2231) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-17-2231.md) |
| [Forskrift om endring i forskrift om graden philosophiae doctor (ph.d.) ved Hande](../forskrifter/forskrift-2026-03-11-396.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-11-396) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-11-396.md) |
| [Forskrift om endring i forskrift om regnskapsplikt mv. for private barnehager (ø](../forskrifter/forskrift-2026-06-26-1394.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-26-1394) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-26-1394.md) |
| [Forskrift om endring i forskrift om studier ved Dronning Mauds Minne Høgskole fo](../forskrifter/forskrift-2023-10-19-1685.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-19-1685) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-19-1685.md) |
| [Forskrift om enkelte klagenemnder på Kunnskapsdepartementets område](../forskrifter/forskrift-2025-07-02-1462.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-02-1462) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-02-1462.md) |
| [Forskrift om fagskoleutdanning ved AOF Østlandet](../forskrifter/forskrift-2025-06-24-2981.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-24-2981) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-24-2981.md) |
| [Forskrift om fagskoleutdanning ved Fredrikstad FagAkademi](../forskrifter/forskrift-2017-10-17-1637.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-17-1637) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-17-1637.md) |
| [Forskrift om fagskoleutdanning ved Treider Fagskoler](../forskrifter/forskrift-2017-06-16-1124.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-16-1124) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-16-1124.md) |
| [Forskrift om fagskoleutdanning ved fagskolen AOF Norge](../forskrifter/forskrift-2017-04-04-446.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-04-446) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-04-446.md) |
| [Forskrift om familiebarnehager](../forskrifter/forskrift-2005-12-16-1555.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1555) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1555.md) |
| [Forskrift om felles rammeplan for helse- og sosialfagutdanninger](../forskrifter/forskrift-2025-07-04-1478.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1478) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1478.md) |
| [Forskrift om finansiering av private barnehager (finansieringsforskriften)](../forskrifter/forskrift-2026-03-23-454.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-23-454) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-23-454.md) |
| [Forskrift om foreldrebetaling i barnehager](../forskrifter/forskrift-2005-12-16-1478.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1478) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1478.md) |
| [Forskrift om forskningsetiske komiteer og utvalg (forskningsetikkforskriften)](../forskrifter/forskrift-2018-03-05-321.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-03-05-321) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-03-05-321.md) |
| [Forskrift om forsterkning av gaver til forskning (gaveforsterkningsforskriften)](../forskrifter/forskrift-2013-12-20-1662.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-20-1662) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-20-1662.md) |
| [Forskrift om frister for sensur av eksamen ved Det juridiske fakultet ved Univer](../forskrifter/forskrift-2018-11-29-2298.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-11-29-2298) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-11-29-2298.md) |
| [Forskrift om fulltidsstudiene ved Norges Handelshøyskole, NHH](../forskrifter/forskrift-2024-06-18-1108.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-18-1108) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-18-1108.md) |
| [Forskrift om føring av register til bruk i forbindelse med kontroll av beregning](../forskrifter/forskrift-2005-12-16-1510.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1510) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1510.md) |
| [Forskrift om generell godkjenning av utenlandsk høyere utdanning](../forskrifter/forskrift-2024-05-21-789.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-21-789) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-21-789.md) |
| [Forskrift om godkjenning av yrkeskvalifikasjoner](../forskrifter/forskrift-2017-12-22-2384.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-22-2384) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-22-2384.md) |
| [Forskrift om godkjenning av yrkeskvalifikasjoner for styrer og pedagogisk leder ](../forskrifter/forskrift-2008-09-12-1071.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-09-12-1071) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-09-12-1071.md) |
| [Forskrift om godkjenning for utdanningsstøtte av utvekslingsorganisasjoner og ut](../forskrifter/forskrift-2019-06-14-734.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-14-734) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-14-734.md) |
| [Forskrift om godkjenning for utdanningsstøtte i Norge](../forskrifter/forskrift-2020-03-27-562.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-27-562) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-27-562.md) |
| [Forskrift om graden doctor philosophiae (dr.philos.) ved Norges Handelshøyskole](../forskrifter/forskrift-2024-03-05-415.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-05-415) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-05-415.md) |
| [Forskrift om graden doctor philosophiae (dr.philos.) ved Norges musikkhøgskole](../forskrifter/forskrift-2021-06-10-1861.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-10-1861) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-10-1861.md) |
| [Forskrift om graden doctor philosophiae (dr.philos.) ved Universitetet i Agder](../forskrifter/forskrift-2021-09-15-3067.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-15-3067) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-15-3067.md) |
| [Forskrift om graden doctor philosophiae (dr.philos.) ved Universitetet i Tromsø ](../forskrifter/forskrift-2018-06-19-1186.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-19-1186) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-19-1186.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid v](../forskrifter/forskrift-2018-02-06-177.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-02-06-177) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-02-06-177.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid v](../forskrifter/forskrift-2024-06-06-1106.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-06-1106) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-06-1106.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved Handelshøyskolen BI](../forskrifter/forskrift-2015-06-11-924.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-11-924) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-11-924.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved Høgskulen i Volda](../forskrifter/forskrift-2024-09-05-2677.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-05-2677) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-05-2677.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved Høgskulen på Vestlandet](../forskrifter/forskrift-2024-06-24-1859.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-24-1859) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-24-1859.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved Norges musikkhøgskole](../forskrifter/forskrift-2024-06-06-969.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-06-969) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-06-969.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved OsloMet – storbyuniversitete](../forskrifter/forskrift-2024-09-17-2297.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-17-2297) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-17-2297.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved Universitetet i Sørøst-Norge](../forskrifter/forskrift-2017-12-14-2411.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-14-2411) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-14-2411.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved VID vitenskapelige høgskole](../forskrifter/forskrift-2015-12-11-1666.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-11-1666) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-11-1666.md) |
| [Forskrift om graden philosophiae doctor ved Samisk høgskole](../forskrifter/forskrift-2019-11-12-2240.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-12-2240) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-12-2240.md) |
| [Forskrift om gradene philosophiae doctor (ph.d.) og philosophiae doctor (ph.d.) ](../forskrifter/forskrift-2022-12-01-2087.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-01-2087) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-01-2087.md) |
| [Forskrift om grader ved Kunsthøgskolen i Bergen.](../forskrifter/forskrift-2003-06-25-1236.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-25-1236) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-25-1236.md) |
| [Forskrift om grader, opptak, studier og eksamen ved VID vitenskapelige høgskole](../forskrifter/forskrift-2024-06-04-1483.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-04-1483) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-04-1483.md) |
| [Forskrift om grunnskoleopplæring og vidaregåande opplæring i Longyearbyen](../forskrifter/forskrift-2024-06-21-1103.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-21-1103) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-21-1103.md) |
| [Forskrift om grunnskoleopplæringa og den vidaregåande opplæringa (opplæringsfors](../forskrifter/forskrift-2024-06-03-900.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-03-900) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-03-900.md) |
| [Forskrift om grunntilskudd til organisasjoner på grunnopplæringsområdet](../forskrifter/forskrift-2023-12-19-2176.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-19-2176) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-19-2176.md) |
| [Forskrift om høyere yrkesfaglig utdanning (fagskoleforskriften)](../forskrifter/forskrift-2019-07-11-1005.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-07-11-1005) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-07-11-1005.md) |
| [Forskrift om høyere yrkesfaglig utdanning for Fagskolen i Agder (Forskrift for F](../forskrifter/forskrift-2024-04-30-783.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-04-30-783) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-04-30-783.md) |
| [Forskrift om høyere yrkesfaglig utdanning for TISIP fagskole](../forskrifter/forskrift-2020-10-12-2054.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-12-2054) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-12-2054.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen Innlandet](../forskrifter/forskrift-2023-12-04-2342.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-04-2342) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-04-2342.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen Tirna](../forskrifter/forskrift-2025-09-15-1843.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-15-1843) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-15-1843.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen Vestfold og Telemark](../forskrifter/forskrift-2025-06-26-1539.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-26-1539) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-26-1539.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen i Finnmark](../forskrifter/forskrift-2024-01-05-300.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-05-300) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-05-300.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen i Møre og Romsdal](../forskrifter/forskrift-2020-10-20-2103.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-20-2103) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-20-2103.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen i Nord](../forskrifter/forskrift-2025-06-24-1413.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-24-1413) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-24-1413.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved KRM Tekniske Fagskole](../forskrifter/forskrift-2020-11-26-3304.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-26-3304) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-26-3304.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Nordland fagskole](../forskrifter/forskrift-2025-12-16-3020.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-16-3020) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-16-3020.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Norges Fagakademi](../forskrifter/forskrift-2019-12-11-2093.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-11-2093) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-11-2093.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Norges grønne fagskole – Vea](../forskrifter/forskrift-2024-06-12-1347.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-12-1347) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-12-1347.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Noroff fagskole](../forskrifter/forskrift-2025-08-06-1713.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-06-1713) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-06-1713.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Trøndelag høyere yrkesfagskole](../forskrifter/forskrift-2025-06-24-1643.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-24-1643) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-24-1643.md) |
| [Forskrift om inntak til videregående opplæring i Longyearbyen, Longyearbyen loka](../forskrifter/forskrift-2025-11-04-2265.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-04-2265) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-04-2265.md) |
| [Forskrift om kompensasjon for renteutgifter til investering i læringsarenaer, ut](../forskrifter/forskrift-2024-06-14-1054.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-14-1054) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-14-1054.md) |
| [Forskrift om kompensasjon for utgifter til investering i skole- og svømmeanlegg ](../forskrifter/forskrift-2014-12-11-1583.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-11-1583) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-11-1583.md) |
| [Forskrift om krav til bachelorgrad ved Høgskolen i Vestfold](../forskrifter/forskrift-2011-06-23-724.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-06-23-724) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-06-23-724.md) |
| [Forskrift om krav til bachelorgrad ved Høgskulen for landbruk og bygdenæringar](../forskrifter/forskrift-2010-05-27-1897.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-05-27-1897) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-05-27-1897.md) |
| [Forskrift om lokale opptak til Universitetet i Oslo](../forskrifter/forskrift-2014-02-12-130.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-02-12-130) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-02-12-130.md) |
| [Forskrift om masterstudiene ved Arkitektur- og designhøgskolen i Oslo](../forskrifter/forskrift-2010-05-28-1888.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-05-28-1888) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-05-28-1888.md) |
| [Forskrift om midlertidige opptaksregler ved Statens kunstakademi.](../forskrifter/forskrift-1991-01-21-54.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-01-21-54) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-01-21-54.md) |
| [Forskrift om nasjonal retningslinje for anestesisykepleierutdanning](../forskrifter/forskrift-2025-09-05-1833.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1833) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1833.md) |
| [Forskrift om nasjonal retningslinje for audiografutdanning](../forskrifter/forskrift-2025-07-04-1471.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1471) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1471.md) |
| [Forskrift om nasjonal retningslinje for barnesykepleierutdanning](../forskrifter/forskrift-2025-09-05-1832.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1832) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1832.md) |
| [Forskrift om nasjonal retningslinje for barnevernspedagogutdanning](../forskrifter/forskrift-2025-09-04-1828.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-04-1828) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-04-1828.md) |
| [Forskrift om nasjonal retningslinje for bioingeniørutdanning](../forskrifter/forskrift-2025-07-04-1486.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1486) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1486.md) |
| [Forskrift om nasjonal retningslinje for ergoterapeututdanning](../forskrifter/forskrift-2025-07-04-1484.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1484) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1484.md) |
| [Forskrift om nasjonal retningslinje for farmasøytutdanningene, bachelor- og mast](../forskrifter/forskrift-2025-07-04-1474.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1474) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1474.md) |
| [Forskrift om nasjonal retningslinje for fysioterapeututdanning](../forskrifter/forskrift-2025-07-04-1485.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1485) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1485.md) |
| [Forskrift om nasjonal retningslinje for helsesykepleierutdanning](../forskrifter/forskrift-2025-07-04-1458.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1458) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1458.md) |
| [Forskrift om nasjonal retningslinje for intensivsykepleierutdanning](../forskrifter/forskrift-2025-09-05-1834.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1834) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1834.md) |
| [Forskrift om nasjonal retningslinje for jordmorutdanning](../forskrifter/forskrift-2025-09-05-1829.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1829) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1829.md) |
| [Forskrift om nasjonal retningslinje for klinisk ernæringsfysiologutdanning](../forskrifter/forskrift-2025-07-04-1473.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1473) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1473.md) |
| [Forskrift om nasjonal retningslinje for kreftsykepleierutdanning](../forskrifter/forskrift-2025-09-05-1831.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1831) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1831.md) |
| [Forskrift om nasjonal retningslinje for masterutdanning i avansert klinisk allme](../forskrifter/forskrift-2025-07-04-1454.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1454) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1454.md) |
| [Forskrift om nasjonal retningslinje for masterutdanning i barnevern](../forskrifter/forskrift-2025-07-04-1456.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1456) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1456.md) |
| [Forskrift om nasjonal retningslinje for masterutdanning i barnevernsarbeid](../forskrifter/forskrift-2025-07-04-1455.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1455) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1455.md) |
| [Forskrift om nasjonal retningslinje for masterutdanning i sykepleie innen psykis](../forskrifter/forskrift-2025-07-04-1916.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1916) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1916.md) |
| [Forskrift om nasjonal retningslinje for medisinutdanning](../forskrifter/forskrift-2025-07-04-1472.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1472) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1472.md) |
| [Forskrift om nasjonal retningslinje for operasjonssykepleierutdanning](../forskrifter/forskrift-2025-09-05-1830.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1830) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1830.md) |
| [Forskrift om nasjonal retningslinje for optikerutdanning](../forskrifter/forskrift-2025-07-04-1470.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1470) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1470.md) |
| [Forskrift om nasjonal retningslinje for ortopediingeniørutdanning](../forskrifter/forskrift-2025-07-04-1469.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1469) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1469.md) |
| [Forskrift om nasjonal retningslinje for paramedisinutdanning](../forskrifter/forskrift-2025-07-04-1487.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1487) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1487.md) |
| [Forskrift om nasjonal retningslinje for psykologutdanning](../forskrifter/forskrift-2025-07-04-1468.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1468) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1468.md) |
| [Forskrift om nasjonal retningslinje for radiografutdanning](../forskrifter/forskrift-2025-07-04-1483.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1483) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1483.md) |
| [Forskrift om nasjonal retningslinje for samisk sykepleierutdanning](../forskrifter/forskrift-2025-07-04-1475.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1475) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1475.md) |
| [Forskrift om nasjonal retningslinje for sosionomutdanning](../forskrifter/forskrift-2025-07-04-1465.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1465) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1465.md) |
| [Forskrift om nasjonal retningslinje for sykepleierutdanning](../forskrifter/forskrift-2025-07-04-1477.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1477) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1477.md) |
| [Forskrift om nasjonal retningslinje for tannlegeutdanning](../forskrifter/forskrift-2025-07-04-1467.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1467) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1467.md) |
| [Forskrift om nasjonal retningslinje for tannpleierutdanning](../forskrifter/forskrift-2025-07-04-1466.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1466) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1466.md) |
| [Forskrift om nasjonal retningslinje for tannteknikerutdanning](../forskrifter/forskrift-2025-07-04-1482.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1482) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1482.md) |
| [Forskrift om nasjonal retningslinje for tverrfaglig videreutdanning i psykisk he](../forskrifter/forskrift-2025-07-04-1457.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1457) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1457.md) |
| [Forskrift om nasjonal retningslinje for tverrfaglig videreutdanning i psykososia](../forskrifter/forskrift-2025-03-18-523.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-18-523) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-18-523.md) |
| [Forskrift om nasjonal retningslinje for vernepleierutdanning](../forskrifter/forskrift-2025-07-04-1476.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1476) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1476.md) |
| [Forskrift om opphevelse av og vedtak vedrørende forskrifter om graden philosophi](../forskrifter/forskrift-2015-12-08-1451.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-08-1451) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-08-1451.md) |
| [Forskrift om oppheving av lov av 1. mars 1940 nr. 1 om yrkesskoler for håndverk ](../forskrifter/forskrift-1977-01-07-3540.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-01-07-3540) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-01-07-3540.md) |
| [Forskrift om opptak og eksamen for Astrologiskolen Herkules](../forskrifter/forskrift-2019-05-15-635.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-05-15-635) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-05-15-635.md) |
| [Forskrift om opptak og eksamen ved Eccera IT Academy](../forskrifter/forskrift-2020-10-15-2116.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-15-2116) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-15-2116.md) |
| [Forskrift om opptak og eksamen ved Fagskolen Aldring og helse](../forskrifter/forskrift-2019-12-13-1794.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-13-1794) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-13-1794.md) |
| [Forskrift om opptak til Høgskulen på Vestlandet](../forskrifter/forskrift-2024-06-24-1858.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-24-1858) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-24-1858.md) |
| [Forskrift om opptak til Universitetet i Bergen](../forskrifter/forskrift-2018-11-27-1907.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-11-27-1907) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-11-27-1907.md) |
| [Forskrift om opptak til Universitetet i Tromsø – Norges arktiske universitet](../forskrifter/forskrift-2020-09-15-1794.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-09-15-1794) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-09-15-1794.md) |
| [Forskrift om opptak til høgare utdanning](../forskrifter/forskrift-2017-01-06-13.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-01-06-13) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-01-06-13.md) |
| [Forskrift om opptak til høgare utdanning (opptaksforskrifta)](../forskrifter/forskrift-2025-09-11-1850.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-11-1850) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-11-1850.md) |
| [Forskrift om opptak til høyere yrkesfaglig utdanning ved Fagskolen Rogaland (opp](../forskrifter/forskrift-2024-09-19-2344.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-19-2344) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-19-2344.md) |
| [Forskrift om opptak til masterstudier ved Politihøgskolen](../forskrifter/forskrift-2017-04-19-674.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-19-674) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-19-674.md) |
| [Forskrift om opptak til masterutdanning ved Høgskolen i Buskerud](../forskrifter/forskrift-2006-06-21-1719.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-21-1719) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-21-1719.md) |
| [Forskrift om opptak til studier og emner ved Universitetet i Agder](../forskrifter/forskrift-2021-11-24-3370.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-24-3370) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-24-3370.md) |
| [Forskrift om opptak til studier og emner ved Universitetet i Stavanger](../forskrifter/forskrift-2018-10-18-1671.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-10-18-1671) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-10-18-1671.md) |
| [Forskrift om opptak til studier ved Høgskolen i Østfold](../forskrifter/forskrift-2025-12-15-2610.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-15-2610) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-15-2610.md) |
| [Forskrift om opptak til studier ved Norges teknisk-naturvitenskapelige universit](../forskrifter/forskrift-2025-03-06-376.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-06-376) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-06-376.md) |
| [Forskrift om opptak ved Fagskulen Vestland](../forskrifter/forskrift-2021-09-17-2913.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-17-2913) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-17-2913.md) |
| [Forskrift om opptak ved Lovisenberg diakonale høgskole](../forskrifter/forskrift-2025-12-16-2962.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-16-2962) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-16-2962.md) |
| [Forskrift om opptak ved Universitetet i Sørøst-Norge](../forskrifter/forskrift-2023-12-13-2111.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-13-2111) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-13-2111.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved Fa](../forskrifter/forskrift-2023-01-02-96.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-02-96) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-02-96.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved Lu](../forskrifter/forskrift-2024-10-24-3634.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-24-3634) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-24-3634.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](../forskrifter/forskrift-2020-03-24-500.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-24-500) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-24-500.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](../forskrifter/forskrift-2025-08-04-1620.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-04-1620) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-04-1620.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](../forskrifter/forskrift-2021-06-22-2204.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-22-2204) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-22-2204.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](../forskrifter/forskrift-2025-12-01-2991.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-01-2991) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-01-2991.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](../forskrifter/forskrift-2021-08-01-4016.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-01-4016) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-01-4016.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](../forskrifter/forskrift-2017-09-20-1444.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-20-1444) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-20-1444.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](../forskrifter/forskrift-2022-01-17-2725.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-17-2725) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-17-2725.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](../forskrifter/forskrift-2023-08-30-2528.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-08-30-2528) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-08-30-2528.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](../forskrifter/forskrift-2025-04-23-746.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-23-746) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-23-746.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](../forskrifter/forskrift-2019-08-22-1094.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-08-22-1094) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-08-22-1094.md) |
| [Forskrift om opptak, eksamen, disiplinære sanksjoner og klagehåndtering for Lofo](../forskrifter/forskrift-2017-10-30-2479.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-30-2479) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-30-2479.md) |
| [Forskrift om opptak, gjennomføring av studier, eksamen og klageregler ved Fagsko](../forskrifter/forskrift-2025-03-06-396.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-06-396) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-06-396.md) |
| [Forskrift om opptak, gjennomføring av studier, eksamen og klageregler ved Tunsbe](../forskrifter/forskrift-2020-12-03-2662.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-03-2662) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-03-2662.md) |
| [Forskrift om opptak, gjennomføring av studier, sluttvurdering, klageregler og sk](../forskrifter/forskrift-2023-09-05-2500.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-05-2500) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-05-2500.md) |
| [Forskrift om opptak, gjennomføring og eksamen for Lokomotivførerutdanningen ved ](../forskrifter/forskrift-2017-04-27-636.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-27-636) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-27-636.md) |
| [Forskrift om opptak, skikkethet, eksamen og klagebehandling ved Sjøforsvarets fa](../forskrifter/forskrift-2022-08-01-1410.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-01-1410) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-01-1410.md) |
| [Forskrift om opptak, studier og eksamen for Einar Granum Kunstfagskole](../forskrifter/forskrift-2019-12-05-2158.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-05-2158) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-05-2158.md) |
| [Forskrift om opptak, studier og eksamen for Kunstfagskolen i Bergen](../forskrifter/forskrift-2022-10-19-2084.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-10-19-2084) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-10-19-2084.md) |
| [Forskrift om opptak, studier og eksamen ved Agder Kunstfagskole](../forskrifter/forskrift-2019-08-31-2291.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-08-31-2291) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-08-31-2291.md) |
| [Forskrift om opptak, studier og eksamen ved Ansgar høyskole](../forskrifter/forskrift-2024-12-11-3175.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-11-3175) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-11-3175.md) |
| [Forskrift om opptak, studier og eksamen ved Arkitektur- og designhøgskolen i Osl](../forskrifter/forskrift-2025-12-17-2645.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-17-2645) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-17-2645.md) |
| [Forskrift om opptak, studier og eksamen ved Den norske Eurytmihøyskole (DnE).](../forskrifter/forskrift-2005-12-09-1716.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-09-1716) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-09-1716.md) |
| [Forskrift om opptak, studier og eksamen ved Designinstituttet](../forskrifter/forskrift-2020-06-09-1167.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-09-1167) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-09-1167.md) |
| [Forskrift om opptak, studier og eksamen ved Fagskolen Aldring og helse](../forskrifter/forskrift-2017-05-22-661.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-22-661) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-22-661.md) |
| [Forskrift om opptak, studier og eksamen ved Fagskolen Kristiania](../forskrifter/forskrift-2026-06-18-1131.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-18-1131) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-18-1131.md) |
| [Forskrift om opptak, studier og eksamen ved Fagskolen Viken](../forskrifter/forskrift-2021-06-14-1978.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-14-1978) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-14-1978.md) |
| [Forskrift om opptak, studier og eksamen ved Fagskolen for bokbransjen](../forskrifter/forskrift-2017-05-15-1139.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-15-1139) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-15-1139.md) |
| [Forskrift om opptak, studier og eksamen ved Fjellhaug Internasjonale Høgskole](../forskrifter/forskrift-2024-11-27-3659.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-27-3659) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-27-3659.md) |
| [Forskrift om opptak, studier og eksamen ved Handelshøyskolen BI](../forskrifter/forskrift-2018-06-01-1546.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-01-1546) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-01-1546.md) |
| [Forskrift om opptak, studier og eksamen ved Høgskolen i Molde – Vitenskapelig hø](../forskrifter/forskrift-2015-05-07-540.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-07-540) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-07-540.md) |
| [Forskrift om opptak, studier og eksamen ved Høyskolen for Ledelse og Teologi](../forskrifter/forskrift-2019-09-23-1468.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-23-1468) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-23-1468.md) |
| [Forskrift om opptak, studier og eksamen ved International Stunt Academy](../forskrifter/forskrift-2021-02-16-530.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-16-530) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-16-530.md) |
| [Forskrift om opptak, studier og eksamen ved Jusutdanning AS](../forskrifter/forskrift-2021-07-28-2462.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-07-28-2462) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-07-28-2462.md) |
| [Forskrift om opptak, studier og eksamen ved KBT fagskole](../forskrifter/forskrift-2022-04-08-2655.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-08-2655) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-08-2655.md) |
| [Forskrift om opptak, studier og eksamen ved MF vitenskapelig høyskole (MF)](../forskrifter/forskrift-2026-06-09-1387.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-09-1387) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-09-1387.md) |
| [Forskrift om opptak, studier og eksamen ved NSKI Høyskole](../forskrifter/forskrift-2017-06-27-1229.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-27-1229) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-27-1229.md) |
| [Forskrift om opptak, studier og eksamen ved Norges Dansehøyskole, NDH (tidligere](../forskrifter/forskrift-2005-08-24-1037.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-08-24-1037) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-08-24-1037.md) |
| [Forskrift om opptak, studier og eksamen ved Norges idrettshøgskole](../forskrifter/forskrift-2005-05-26-1811.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-05-26-1811) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-05-26-1811.md) |
| [Forskrift om opptak, studier og eksamen ved Norsk Fotofagskole](../forskrifter/forskrift-2021-01-22-176.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-22-176) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-22-176.md) |
| [Forskrift om opptak, studier og eksamen ved Norsk Gestaltinstitutt Høyskole](../forskrifter/forskrift-2025-06-16-1701.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-16-1701) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-16-1701.md) |
| [Forskrift om opptak, studier og eksamen ved Norsk barnebokinstitutt](../forskrifter/forskrift-2020-02-13-688.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-13-688) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-13-688.md) |
| [Forskrift om opptak, studier og eksamen ved Nortrain fagskole](../forskrifter/forskrift-2017-05-10-596.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-10-596) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-10-596.md) |
| [Forskrift om opptak, studier og eksamen ved Oslo Nye Fagskole](../forskrifter/forskrift-2024-03-15-478.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-15-478) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-15-478.md) |
| [Forskrift om opptak, studier og eksamen ved Oslo Nye Høyskole](../forskrifter/forskrift-2019-03-01-1082.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-01-1082) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-01-1082.md) |
| [Forskrift om opptak, studier og eksamen ved OsloMet – storbyuniversitetet (OsloM](../forskrifter/forskrift-2026-05-08-1479.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-08-1479) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-08-1479.md) |
| [Forskrift om opptak, studier og eksamen ved Steinerhøyskolen](../forskrifter/forskrift-2006-03-07-563.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-03-07-563) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-03-07-563.md) |
| [Forskrift om opptak, studier og eksamen ved Stiftelsen Norsk Hestesenter](../forskrifter/forskrift-2020-10-21-2137.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-21-2137) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-21-2137.md) |
| [Forskrift om opptak, studier og eksamen ved Universitetet i Innlandet](../forskrifter/forskrift-2024-06-19-1221.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-19-1221) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-19-1221.md) |
| [Forskrift om opptak, studier og eksamener ved Universitetssenteret på Svalbard A](../forskrifter/forskrift-2019-09-27-1441.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-27-1441) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-27-1441.md) |
| [Forskrift om opptak, studier, eksamen og klagebehandling for Fabrikken Asker Kun](../forskrifter/forskrift-2019-12-17-2134.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-17-2134) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-17-2134.md) |
| [Forskrift om opptak, studier, eksamen og klagebehandling for Kunstskolen i Stava](../forskrifter/forskrift-2019-12-09-2189.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-09-2189) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-09-2189.md) |
| [Forskrift om opptak, studier, eksamen og klagebehandling for Ytre kunstfagskole](../forskrifter/forskrift-2020-01-16-54.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-16-54) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-16-54.md) |
| [Forskrift om opptak, studier, eksamen og klagebehandling ved Campus BLÅ Fagskole](../forskrifter/forskrift-2019-02-15-223.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-02-15-223) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-02-15-223.md) |
| [Forskrift om opptak, studier, grader og eksamen ved Høyskolen Kristiania](../forskrifter/forskrift-2024-12-12-3309.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-12-3309) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-12-3309.md) |
| [Forskrift om opptak, studier, grader og eksamen ved Noroff University College AS](../forskrifter/forskrift-2024-10-11-3715.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-11-3715) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-11-3715.md) |
| [Forskrift om opptak, studium og eksamen ved Høgskulen i Volda](../forskrifter/forskrift-2026-06-10-1052.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-10-1052) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-10-1052.md) |
| [Forskrift om opptak, studium og eksamen ved Skrivekunstakademiet i Hordaland](../forskrifter/forskrift-2017-03-14-324.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-03-14-324) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-03-14-324.md) |
| [Forskrift om opptak, utdanninger og eksamen ved Fagskolen Diakonova](../forskrifter/forskrift-2025-01-09-20.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-09-20) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-09-20.md) |
| [Forskrift om overføring av avgjørelsesmyndighet etter lov om proteseteknikere og](../forskrifter/forskrift-1982-04-23-777.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-04-23-777) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-04-23-777.md) |
| [Forskrift om overføring av forhandlingsansvaret for undervisningspersonale til k](../forskrifter/forskrift-2003-01-31-90.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-31-90) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-31-90.md) |
| [Forskrift om overgangsregler for Høgskolen i Oslo og Akershus](../forskrifter/forskrift-2011-09-01-948.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-09-01-948) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-09-01-948.md) |
| [Forskrift om overgangsregler for NLA Høgskolen](../forskrifter/forskrift-2012-12-13-1432.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-13-1432) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-13-1432.md) |
| [Forskrift om overgangsregler til barnehageloven – overføring av ansvaret for å f](../forskrifter/forskrift-2021-10-06-3079.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-10-06-3079) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-10-06-3079.md) |
| [Forskrift om overordna mål og prinsipp for grunnskoleopplæringa og den vidaregåa](../forskrifter/forskrift-2026-05-22-871.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-22-871) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-22-871.md) |
| [Forskrift om pedagogisk bemanning og dispensasjon i barnehager](../forskrifter/forskrift-2017-06-22-1049.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-22-1049) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-22-1049.md) |
| [Forskrift om politiattest i barnehager](../forskrifter/forskrift-2015-11-11-1285.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-11-11-1285) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-11-11-1285.md) |
| [Forskrift om private universiteter, høyskoler og fagskoler – krav til regnskap m](../forskrifter/forskrift-2017-12-21-2383.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-21-2383) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-21-2383.md) |
| [Forskrift om rammeplan for bachelor i regnskap og revisjon](../forskrifter/forskrift-2012-06-27-687.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-27-687) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-27-687.md) |
| [Forskrift om rammeplan for barnehagelærerutdanning](../forskrifter/forskrift-2025-07-04-1447.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1447) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1447.md) |
| [Forskrift om rammeplan for barnehagens innhold og oppgaver](../forskrifter/forskrift-2017-04-24-487.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-24-487) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-24-487.md) |
| [Forskrift om rammeplan for grunnskolelærerutdanning for trinn 1–7](../forskrifter/forskrift-2025-07-04-1442.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1442) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1442.md) |
| [Forskrift om rammeplan for grunnskolelærerutdanning for trinn 5–10](../forskrifter/forskrift-2025-07-04-1444.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1444) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1444.md) |
| [Forskrift om rammeplan for ingeniørutdanning](../forskrifter/forskrift-2018-05-18-870.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-05-18-870) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-05-18-870.md) |
| [Forskrift om rammeplan for lektorutdanning for trinn 8–13](../forskrifter/forskrift-2025-07-04-1446.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1446) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1446.md) |
| [Forskrift om rammeplan for lærerutdanning i praktiske og estetiske fag for trinn](../forskrifter/forskrift-2025-07-04-1451.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1451) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1451.md) |
| [Forskrift om rammeplan for praktisk-pedagogisk utdanning](../forskrifter/forskrift-2025-07-04-1449.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1449) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1449.md) |
| [Forskrift om rammeplan for praktisk-pedagogisk utdanning for yrkesfag for trinn ](../forskrifter/forskrift-2025-07-04-1450.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1450) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1450.md) |
| [Forskrift om rammeplan for samisk barnehagelærerutdanning](../forskrifter/forskrift-2025-07-04-1448.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1448) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1448.md) |
| [Forskrift om rammeplan for samisk grunnskolelærerutdanning for trinn 1–7](../forskrifter/forskrift-2025-07-04-1443.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1443) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1443.md) |
| [Forskrift om rammeplan for samisk grunnskolelærerutdanning for trinn 5–10](../forskrifter/forskrift-2025-07-04-1445.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1445) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1445.md) |
| [Forskrift om rammeplan for skolefritidsordningen](../forskrifter/forskrift-2021-05-31-1825.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-31-1825) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-31-1825.md) |
| [Forskrift om rammeplan for yrkesfaglærerutdanning for trinn 8–13](../forskrifter/forskrift-2025-07-04-1453.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1453) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1453.md) |
| [Forskrift om regler for utdanningsstøtte for 2019–2020 som følge av utbruddet av](../forskrifter/forskrift-2020-04-03-569.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-03-569) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-03-569.md) |
| [Forskrift om regnskapsplikt mv. for private barnehager (økonomiforskrift til bar](../forskrifter/forskrift-2022-12-16-2322.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-16-2322) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-16-2322.md) |
| [Forskrift om rett til eksamen som privatist ved Universitetet i Stavanger (priva](../forskrifter/forskrift-2025-10-14-2123.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-14-2123) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-14-2123.md) |
| [Forskrift om rett til opplæring i samisk](../forskrifter/forskrift-1992-03-31-204.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-03-31-204) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-03-31-204.md) |
| [Forskrift om saksbehandlingsregler ved opptak i barnehage](../forskrifter/forskrift-2005-12-16-1477.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1477) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1477.md) |
| [Forskrift om skole- og feriedager (skoleruta) (2026–2027), Samisk videregående s](../forskrifter/forskrift-2026-06-09-1808.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-09-1808) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-09-1808.md) |
| [Forskrift om skole- og feriedager (skoleruta) (2026–2027), Samisk videregående s](../forskrifter/forskrift-2026-06-09-1029.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-09-1029) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-09-1029.md) |
| [Forskrift om skoleregler for Samisk videregående skole, Karasjok og Samisk vider](../forskrifter/forskrift-2025-06-20-1156.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1156) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1156.md) |
| [Forskrift om studentsamskipnader](../forskrifter/forskrift-2008-07-22-828.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-07-22-828) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-07-22-828.md) |
| [Forskrift om studieforbund godkjent av Kunnskapsdepartementet](../forskrifter/forskrift-2020-12-15-2874.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-15-2874) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-15-2874.md) |
| [Forskrift om studiene ved Kunsthøgskolen i Oslo](../forskrifter/forskrift-2024-06-11-1304.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-11-1304) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-11-1304.md) |
| [Forskrift om studiene ved Musikkteaterhøyskolen](../forskrifter/forskrift-2012-08-03-1479.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-08-03-1479) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-08-03-1479.md) |
| [Forskrift om studiene ved Norges musikkhøgskole](../forskrifter/forskrift-2005-12-16-1559.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1559) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1559.md) |
| [Forskrift om studiene ved etter- og videreutdanningen ved Norges Handelshøyskole](../forskrifter/forskrift-2024-06-18-1057.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-18-1057) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-18-1057.md) |
| [Forskrift om studier og eksamen ved Lovisenberg diakonale høgskole](../forskrifter/forskrift-2024-12-03-3571.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-03-3571) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-03-3571.md) |
| [Forskrift om studier og eksamen ved Nord universitet](../forskrifter/forskrift-2024-06-19-1643.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-19-1643) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-19-1643.md) |
| [Forskrift om studier og eksamen ved Politihøgskolen (PHS)](../forskrifter/forskrift-2026-06-25-1497.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-25-1497) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-25-1497.md) |
| [Forskrift om studier og eksamen ved Samisk høgskole](../forskrifter/forskrift-2026-06-11-1612.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-11-1612) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-11-1612.md) |
| [Forskrift om studier og eksamen ved Universitetet i Agder](../forskrifter/forskrift-2005-06-22-833.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-22-833) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-22-833.md) |
| [Forskrift om studier og eksamen ved Universitetet i Stavanger](../forskrifter/forskrift-2025-06-12-1278.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1278) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1278.md) |
| [Forskrift om studier og eksamen ved Universitetet i Sørøst-Norge (USN)](../forskrifter/forskrift-2024-06-19-1376.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-19-1376) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-19-1376.md) |
| [Forskrift om studier og eksamener ved Universitetet i Oslo](../forskrifter/forskrift-2005-12-20-1798.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-20-1798) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-20-1798.md) |
| [Forskrift om studier og eksamener ved Universitetet i Tromsø – Norges arktiske u](../forskrifter/forskrift-2020-06-26-1617.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-26-1617) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-26-1617.md) |
| [Forskrift om studier ved Dronning Mauds Minne Høgskole for barnehagelærerutdanni](../forskrifter/forskrift-2025-06-05-1370.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-05-1370) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-05-1370.md) |
| [Forskrift om studier ved NLA Høgskolen](../forskrifter/forskrift-2024-06-05-1822.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-05-1822) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-05-1822.md) |
| [Forskrift om studier ved Norges miljø- og biovitenskapelige universitet](../forskrifter/forskrift-2023-03-09-322.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-03-09-322) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-03-09-322.md) |
| [Forskrift om studier ved Norges teknisk-naturvitenskapelige universitet (NTNU)](../forskrifter/forskrift-2025-03-06-384.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-06-384) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-06-384.md) |
| [Forskrift om studium og eksamen ved Høgskulen på Vestlandet](../forskrifter/forskrift-2025-06-12-1547.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1547) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1547.md) |
| [Forskrift om studium ved Fagskulen Vestland](../forskrifter/forskrift-2025-03-07-529.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-07-529) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-07-529.md) |
| [Forskrift om studium ved Universitetet i Bergen](../forskrifter/forskrift-2023-06-15-1359.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-15-1359) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-15-1359.md) |
| [Forskrift om tilbakebetaling av utdanningslån](../forskrifter/forskrift-2022-12-15-2259.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-15-2259) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-15-2259.md) |
| [Forskrift om tilbakebetaling av utdanningslån 2020](../forskrifter/forskrift-2019-12-17-1872.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-17-1872) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-17-1872.md) |
| [Forskrift om tilbakebetaling av utdanningslån 2021](../forskrifter/forskrift-2020-12-17-3022.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-17-3022) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-17-3022.md) |
| [Forskrift om tilbakebetaling av utdanningslån 2022](../forskrifter/forskrift-2021-12-15-3636.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-15-3636) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-15-3636.md) |
| [Forskrift om tildeling av tilskudd til private barnehager](../forskrifter/forskrift-2015-10-09-1166.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-10-09-1166) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-10-09-1166.md) |
| [Forskrift om tildeling av utdanningsstøtte for undervisningsåret 2019–2020](../forskrifter/forskrift-2019-03-15-254.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-15-254) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-15-254.md) |
| [Forskrift om tilpasning til universitets- og høyskoleloven for Høgskolen for kri](../forskrifter/forskrift-2026-04-17-602.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-17-602) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-17-602.md) |
| [Forskrift om tilskudd til dekning av skolepenger til elever ved utenlandske elle](../forskrifter/forskrift-2003-02-13-224.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-13-224) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-13-224.md) |
| [Forskrift om tilskudd til kollektiv kompetanseutvikling i barnehage og grunnskol](../forskrifter/forskrift-2026-01-12-23.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-12-23) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-12-23.md) |
| [Forskrift om tilskudd til kollektiv kompetanseutvikling i videregående opplæring](../forskrifter/forskrift-2026-01-12-25.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-12-25) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-12-25.md) |
| [Forskrift om tilskudd til studentboliger](../forskrifter/forskrift-2004-01-28-424.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-01-28-424) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-01-28-424.md) |
| [Forskrift om tilskudd til videreutdanning i barnehage, grunnskole og videregåend](../forskrifter/forskrift-2026-01-12-24.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-12-24) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-12-24.md) |
| [Forskrift om trafikkflyger fagskoleutdanning CAE Oslo Aviation Academy](../forskrifter/forskrift-2019-11-13-2285.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-13-2285) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-13-2285.md) |
| [Forskrift om trafikkflyger fagskoleutdanning European Helicopter Center](../forskrifter/forskrift-2023-12-27-2428.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-27-2428) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-27-2428.md) |
| [Forskrift om unntak fra og tilpasninger til lov om høyere yrkesfaglig utdanning ](../forskrifter/forskrift-2026-06-19-1140.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-19-1140) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-19-1140.md) |
| [Forskrift om unntak fra og tilpasninger til universitets- og høyskoleloven for F](../forskrifter/forskrift-2026-08-21-1658.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-08-21-1658) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-08-21-1658.md) |
| [Forskrift om unntak fra rett og plikt til deltagelse i opplæring i norsk og samf](../forskrifter/forskrift-2020-12-18-2830.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2830) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2830.md) |
| [Forskrift om utanrettslege gjeldsordningar og ettergiving av fordringar som er u](../forskrifter/forskrift-2001-10-31-1274.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-10-31-1274) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-10-31-1274.md) |
| [Forskrift om utdanning ved Fagskolen Rogaland (utdanningsforskrift for Fagskolen](../forskrifter/forskrift-2024-09-19-2345.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-19-2345) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-19-2345.md) |
| [Forskrift om utdanningsstøtte](../forskrifter/forskrift-2020-04-15-798.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-15-798) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-15-798.md) |
| [Forskrift om utvidet sensurfrist for fjernundervisningsemner ved Høgskolen i Sør](../forskrifter/forskrift-2005-11-16-1340.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-16-1340) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-16-1340.md) |
| [Forskrift om vedtekter for Norges forskningsråd](../forskrifter/forskrift-2016-06-10-658.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-10-658) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-10-658.md) |
| [Forskrift til folkehøgskoleloven (folkehøgskoleforskriften)](../forskrifter/forskrift-2025-08-21-1693.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-21-1693) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-21-1693.md) |
| [Forskrift til privatskolelova (privatskoleforskrifta)](../forskrifter/forskrift-2024-06-03-901.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-03-901) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-03-901.md) |
| [Forskrift til privatskolelova kapittel 6A](../forskrifter/forskrift-2020-11-23-2476.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-23-2476) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-23-2476.md) |
| [Forskrift til rammeplan for videreutdanning i aldring og eldreomsorg](../forskrifter/forskrift-2005-12-01-1383.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-01-1383) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-01-1383.md) |
| [Forskrift til rammeplan for videreutdanning i helsefremmende og forebyggende arb](../forskrifter/forskrift-2005-12-01-1382.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-01-1382) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-01-1382.md) |
| [Forskrift til universitets- og høyskoleloven (universitets- og høyskoleforskrift](../forskrifter/forskrift-2024-06-28-1392.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-28-1392) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-28-1392.md) |
| [Fusjon mellom Høgskolen i Finnmark og Universitetet i Tromsø](../forskrifter/forskrift-2013-02-15-186.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-02-15-186) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-02-15-186.md) |
| [Fusjon mellom Høgskolen i Oslo og Høgskolen i Akershus](../forskrifter/forskrift-2011-01-21-93.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-01-21-93) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-01-21-93.md) |
| [Grunnregler for skoler til utdanning av vernepleiere (grunnregler i vernepleie)](../forskrifter/forskrift-1980-06-17-8756.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-06-17-8756) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-06-17-8756.md) |
| [Ikraftsetjing og overgangsreglar til lov av 4. juli 2003 nr. 84 om frittståande ](../forskrifter/forskrift-2003-07-04-896.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-04-896) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-04-896.md) |
| [Ikrafttredelse av lov 29. juni 2007 nr. 90 om endringer i lov 20. juni 2003 nr. ](../forskrifter/forskrift-2007-06-29-759.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-759) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-759.md) |
| [Iverksetjing av lov 19. juni 1997 nr. 83 om endringar i lov av 13. juni 1969 nr.](../forskrifter/forskrift-1997-06-27-645.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-06-27-645) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-06-27-645.md) |
| [Kongens myndighet etter lov 1. april 2005 nr. 15 om universiteter og høyskoler (](../forskrifter/forskrift-2023-10-27-1708.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-27-1708) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-27-1708.md) |
| [Lovisenberg diakonale høgskole status som høgskole](../forskrifter/forskrift-2011-06-24-650.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-06-24-650) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-06-24-650.md) |
| [Mellombels forskrift om sensurfristar ved Norges Handelshøyskole (NHH)](../forskrifter/forskrift-2021-12-16-3961.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-16-3961) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-16-3961.md) |
| [Mellombels forskrift om sensurfristar ved Norges Handelshøyskole (NHH)](../forskrifter/forskrift-2023-12-12-2083.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-12-2083) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-12-2083.md) |
| [Midlertidig forskrift om midlertidig godkjenning av ordinære barnehager og midle](../forskrifter/forskrift-2023-06-27-1136.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-27-1136) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-27-1136.md) |
| [Retningslinjer for statlig grunnbevilgning til forskningsinstitutter og forsknin](../forskrifter/forskrift-2008-12-19-1579.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-19-1579) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-19-1579.md) |
| [Sammenslåing av Høgskolen i Buskerud og Vestfold og Høgskolen i Telemark](../forskrifter/forskrift-2015-06-19-694.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-694) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-694.md) |
| [Sammenslåing av Høgskolen i Oslo og Akershus og Norsk institutt for by- og regio](../forskrifter/forskrift-2015-12-18-1623.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-18-1623) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-18-1623.md) |
| [Sammenslåing av Høgskolen i Oslo og Akershus og Statens institutt for forbruksfo](../forskrifter/forskrift-2015-09-25-1127.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-25-1127) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-25-1127.md) |
| [Sammenslåing av Høgskolen i Oslo og Akershus, Arbeidsforskningsinstituttet AS og](../forskrifter/forskrift-2013-09-20-1110.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-09-20-1110) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-09-20-1110.md) |
| [Sammenslåing av NTNU, Høgskolen i Sør-Trøndelag, Høgskolen i Gjøvik og Høgskolen](../forskrifter/forskrift-2015-06-19-695.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-695) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-695.md) |
| [Sammenslåing av Universitetet i Nordland, Høgskolen i Nord-Trøndelag og Høgskole](../forskrifter/forskrift-2015-10-09-1192.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-10-09-1192) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-10-09-1192.md) |
| [Sammenslåing av Universitetet i Tromsø – Norges arktiske universitet, Høgskolen ](../forskrifter/forskrift-2015-06-19-696.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-696) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-696.md) |
| [Sammenslåing av høyskolene i Vestfold og Buskerud](../forskrifter/forskrift-2012-10-26-994.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-26-994) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-26-994.md) |
| [Sammenslåing av universitetet i Nordland og Høgskolen i Nesna](../forskrifter/forskrift-2015-06-19-697.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-697) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-697.md) |
| [Vedtak om Høgskolen i Bodø – godkjenning av status som universitet](../forskrifter/forskrift-2010-11-19-1470.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-19-1470) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-19-1470.md) |
| [Vedtak om godkjenning av Norsk Lærerakademi Bachelor- og masterstudier som høysk](../forskrifter/forskrift-2007-03-16-304.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-03-16-304) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-03-16-304.md) |
| [Vedtak om sammenslåing av Norges veterinærhøgskole og Universitetet for miljø- o](../forskrifter/forskrift-2013-06-21-734.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-21-734) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-21-734.md) |
| [Vedtak om status som vitenskapelig høgskole og nytt navn for Høgskolen i Molde](../forskrifter/forskrift-2009-11-20-1428.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-11-20-1428) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-11-20-1428.md) |
| [Økonomiforskrift til privatskolelova](../forskrifter/forskrift-2018-09-01-1295.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-01-1295) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-01-1295.md) |
