# Kultur- og likestillingsdepartementet

*141 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Delegering av Kongens myndighet etter forvaltningsloven § 28 fjerde ledd til Kul](../forskrifter/forskrift-2013-05-24-519.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-24-519) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-24-519.md) |
| [Delegering av Kongens myndighet etter forvaltningsloven § 28 fjerde ledd til Kul](../forskrifter/forskrift-2020-10-30-2216.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-30-2216) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-30-2216.md) |
| [Delegering av Kongens myndighet etter forvaltningsloven § 28 fjerde ledd til Kul](../forskrifter/forskrift-2020-11-27-2487.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-27-2487) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-27-2487.md) |
| [Delegering av Kongens myndighet etter likestillings- og diskrimineringsloven § 3](../forskrifter/forskrift-2021-11-12-3207.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-12-3207) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-12-3207.md) |
| [Delegering av Kongens myndighet etter lov 16. juni 2017 nr. 51 om likestilling o](../forskrifter/forskrift-2022-04-08-559.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-08-559) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-08-559.md) |
| [Delegering av Kongens myndighet etter lov 16. juni 2017 nr. 51 om likestilling o](../forskrifter/forskrift-2021-09-17-2780.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-17-2780) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-17-2780.md) |
| [Delegering av Kongens myndighet etter lov 28. august 1992 nr. 103 om pengespill ](../forskrifter/forskrift-2022-12-20-2297.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2297) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2297.md) |
| [Delegering av Kongens myndighet etter lov 4. desember 1992 nr. 127 om kringkasti](../forskrifter/forskrift-2025-02-28-332.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-28-332) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-28-332.md) |
| [Delegering av Kongens myndighet etter lov om pengespill mv til Kulturdepartement](../forskrifter/forskrift-1992-12-11-1051.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-11-1051) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-11-1051.md) |
| [Delegering av Kongens myndighet etter pengespilloven § 10 fjerde ledd, for så vi](../forskrifter/forskrift-2022-04-01-519.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-01-519) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-01-519.md) |
| [Delegering av ansvar etter målbruksforskrifta § 8 til Språkrådet](../forskrifter/forskrift-2016-06-03-1951.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-03-1951) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-03-1951.md) |
| [Delegering av ansvar for ansettelse av riksteatersjef og fastsettelse av styrein](../forskrifter/forskrift-2018-05-25-755.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-05-25-755) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-05-25-755.md) |
| [Delegering av fullmakt til Kulturdepartementet etter lov om stadnamn m.m.](../forskrifter/forskrift-1991-07-04-448.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-07-04-448) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-07-04-448.md) |
| [Delegering av myndighet etter lov 4. desember 1992 nr. 126 om arkiv til å gi bes](../forskrifter/forskrift-2008-10-10-1110.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-10-10-1110) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-10-10-1110.md) |
| [Delegering av myndighet etter lov om avleveringsplikt for allment tilgjengelege ](../forskrifter/forskrift-2018-06-22-962.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-962) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-962.md) |
| [Delegering av myndighet etter pengespilloven § 3 tredje ledd og § 10 tredje ledd](../forskrifter/forskrift-2013-04-05-342.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-04-05-342) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-04-05-342.md) |
| [Delegering av myndighet til Kultur- og kirkedepartementet etter lov om avgift på](../forskrifter/forskrift-2001-12-21-1510.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-21-1510) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-21-1510.md) |
| [Delegering av myndighet til Kultur- og kirkedepartementet etter lov om kringkast](../forskrifter/forskrift-2001-07-06-823.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-07-06-823) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-07-06-823.md) |
| [Delegering av myndighet til Kultur- og kirkedepartementet – produksjonstilskudd ](../forskrifter/forskrift-1996-11-07-1016.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-11-07-1016) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-11-07-1016.md) |
| [Delegering av myndighet til Kultur- og kirkedepartementet – tilskudd til innvand](../forskrifter/forskrift-1996-11-07-1018.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-11-07-1018) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-11-07-1018.md) |
| [Delegering av myndighet til Kulturdepartementet etter lov om avgift på offentlig](../forskrifter/forskrift-1991-09-20-619.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-09-20-619) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-09-20-619.md) |
| [Delegering av myndighet til Kulturdepartementet etter lov om kringkasting.](../forskrifter/forskrift-1991-07-04-449.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-07-04-449) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-07-04-449.md) |
| [Delegering av myndighet til Kulturdepartementet etter åndsverkloven § 16e og § 3](../forskrifter/forskrift-2015-06-19-725.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-725) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-725.md) |
| [Delegering av myndighet til Lotteri- og stiftelsestilsynet etter forskrift om gr](../forskrifter/forskrift-2013-01-16-43.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-01-16-43) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-01-16-43.md) |
| [Delegering av myndighet til Lotteritilsynet etter lov om pengespill m.v. § 2 før](../forskrifter/forskrift-2003-08-25-1122.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-25-1122) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-25-1122.md) |
| [Delegering av myndighet til Norsk rikskringkasting, Medietilsynet og Kultur- og ](../forskrifter/forskrift-2004-01-30-243.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-01-30-243) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-01-30-243.md) |
| [Delegering av myndighet til Statens medieforvaltning til å gi konsesjon til drif](../forskrifter/forskrift-1994-01-14-637.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-01-14-637) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-01-14-637.md) |
| [Delegering av myndighet til Statens medieforvaltning til å gi konsesjon til etab](../forskrifter/forskrift-1993-08-23-1424.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-23-1424) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-23-1424.md) |
| [Delegering av myndighet til Statens medieforvaltning til å gi konsesjon til oppr](../forskrifter/forskrift-1994-06-01-639.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-06-01-639) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-06-01-639.md) |
| [Delegering av myndighet til å oppnevne og gjenoppnevne medlemmer i Lotterinemnda](../forskrifter/forskrift-2013-02-08-153.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-02-08-153) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-02-08-153.md) |
| [Endringer i 1) rettskrivningen og læreboknormalen for bokmål og 2) bruksområdet ](../forskrifter/forskrift-1981-07-24-4940.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-07-24-4940) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-07-24-4940.md) |
| [Forskrift for strømstøtteordningen for frivillig sektor](../forskrifter/forskrift-2022-07-01-1283.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-07-01-1283) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-07-01-1283.md) |
| [Forskrift for tilbakelån av arkivsaker fra arkivverket til avleverende institusj](../forskrifter/forskrift-1980-05-19-3564.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-05-19-3564) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-05-19-3564.md) |
| [Forskrift for vigsel ved sjømannsprest utsendt av Den norske Sjømannsmisjon.](../forskrifter/forskrift-1956-09-14-3.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1956-09-14-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1956-09-14-3.md) |
| [Forskrift om Fond for lyd og bilde](../forskrifter/forskrift-2025-12-19-2845.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2845) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2845.md) |
| [Forskrift om Norsk kulturfond](../forskrifter/forskrift-1965-06-19-3583.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1965-06-19-3583) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1965-06-19-3583.md) |
| [Forskrift om Statens kunstnarstipend](../forskrifter/forskrift-2026-05-26-897.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-26-897) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-26-897.md) |
| [Forskrift om aspirantordning for kunstnere i etableringsfasen](../forskrifter/forskrift-1998-10-01-1031.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-10-01-1031) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-10-01-1031.md) |
| [Forskrift om avleveringsplikt for allment tilgjengelege dokument](../forskrifter/forskrift-2018-07-01-1139.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-07-01-1139) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-07-01-1139.md) |
| [Forskrift om beskyttelse av mindreårige mot skadelige bildeprogram](../forskrifter/forskrift-2015-06-26-800.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-26-800) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-26-800.md) |
| [Forskrift om bibliotekstatistikk](../forskrifter/forskrift-1987-01-05-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-01-05-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-01-05-2.md) |
| [Forskrift om bruken av midlar frå Norsk kulturfond.](../forskrifter/forskrift-1965-06-19-3582.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1965-06-19-3582) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1965-06-19-3582.md) |
| [Forskrift om delegering av myndighet vedr. det fylkeskommunale arkivvesen.](../forskrifter/forskrift-1977-07-22-3565.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-07-22-3565) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-07-22-3565.md) |
| [Forskrift om dokumentasjon og arkiv (arkivforskrifta)](../forskrifter/forskrift-2025-12-17-2647.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-17-2647) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-17-2647.md) |
| [Forskrift om endring av rettskriving og læreboknormal](../forskrifter/forskrift-1982-02-16-382.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-02-16-382) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-02-16-382.md) |
| [Forskrift om film og videogram.](../forskrifter/forskrift-1999-12-20-1515.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-20-1515) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-20-1515.md) |
| [Forskrift om fordeling av Norsk Tippings overskudd til idrettsformål](../forskrifter/forskrift-2022-12-05-2122.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-05-2122) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-05-2122.md) |
| [Forskrift om fordeling av Norsk Tippings overskudd til kulturformål](../forskrifter/forskrift-2026-04-17-615.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-17-615) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-17-615.md) |
| [Forskrift om fordeling av formue til frivillig virksomhet til fordel for barn og](../forskrifter/forskrift-2023-10-27-1706.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-27-1706) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-27-1706.md) |
| [Forskrift om fortsatt bevilling til TONO og NCB til å drive virksomhet i Norge.](../forskrifter/forskrift-1971-06-25-3800.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-06-25-3800) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-06-25-3800.md) |
| [Forskrift om forvaltning av Fond for utøvende kunstnere og om fastsetting av avg](../forskrifter/forskrift-2001-12-21-1559.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-21-1559) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-21-1559.md) |
| [Forskrift om grasrotandel](../forskrifter/forskrift-2022-12-05-2124.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-05-2124) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-05-2124.md) |
| [Forskrift om helseføretak som statsorgan etter lov om målbruk i offentleg tenest](../forskrifter/forskrift-2004-03-18-532.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-03-18-532) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-03-18-532.md) |
| [Forskrift om innovasjons- og utviklingstilskudd til nyhets- og aktualitetsmedier](../forskrifter/forskrift-2018-06-26-1033.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-26-1033) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-26-1033.md) |
| [Forskrift om insentivordning for film- og serieproduksjoner](../forskrifter/forskrift-2015-12-16-1684.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-16-1684) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-16-1684.md) |
| [Forskrift om insentivordning for ny dramatikk](../forskrifter/forskrift-2024-11-25-2837.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-25-2837) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-25-2837.md) |
| [Forskrift om kompensasjon for portoutgifter i avisene.](../forskrifter/forskrift-2006-11-20-1267.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-11-20-1267) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-11-20-1267.md) |
| [Forskrift om kompensasjon for utgifter til renter til investeringer for istandse](../forskrifter/forskrift-2014-09-01-1139.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-09-01-1139) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-09-01-1139.md) |
| [Forskrift om konsesjonsområder for lokalradio.](../forskrifter/forskrift-2000-10-10-1004.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-10-10-1004) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-10-10-1004.md) |
| [Forskrift om krigsgraver](../forskrifter/forskrift-2015-04-13-370.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-13-370) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-13-370.md) |
| [Forskrift om kringkasting og audiovisuelle bestillingstjenester mv. (kringkastin](../forskrifter/forskrift-1997-02-28-153.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-02-28-153) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-02-28-153.md) |
| [Forskrift om kva dokumentasjon som skal takast vare på for ettertida (bevaringsf](../forskrifter/forskrift-2025-12-19-2729.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2729) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2729.md) |
| [Forskrift om kvalifikasjonskrav for ansatte i folkebibliotek](../forskrifter/forskrift-2013-12-20-1656.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-20-1656) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-20-1656.md) |
| [Forskrift om medieregioner.](../forskrifter/forskrift-2005-07-01-754.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-07-01-754) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-07-01-754.md) |
| [Forskrift om merverdiavgiftskompensasjon for frivillige organisasjoner](../forskrifter/forskrift-2025-12-18-2719.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2719) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2719.md) |
| [Forskrift om midlertidig kompensasjonsordning for arrangører i kultursektoren ve](../forskrifter/forskrift-2020-04-03-677.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-03-677) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-03-677.md) |
| [Forskrift om midlertidig kompensasjonsordning for avlyste, stengte eller nedskal](../forskrifter/forskrift-2021-05-26-1642.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-26-1642) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-26-1642.md) |
| [Forskrift om midlertidig kompensasjonsordning for avlyste, stengte eller nedskal](../forskrifter/forskrift-2021-10-01-2923.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-10-01-2923) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-10-01-2923.md) |
| [Forskrift om midlertidig kompensasjonsordning for avlyste, stengte eller nedskal](../forskrifter/forskrift-2022-03-08-345.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-08-345) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-08-345.md) |
| [Forskrift om midlertidig kompensasjonsordning for frivillighets- og idrettssekto](../forskrifter/forskrift-2020-07-16-1581.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-16-1581) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-16-1581.md) |
| [Forskrift om midlertidig kompensasjonsordning for frivillighets- og idrettssekto](../forskrifter/forskrift-2020-10-16-2084.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-16-2084) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-16-2084.md) |
| [Forskrift om midlertidig kompensasjonsordning for redaktørstyrte medier med fall](../forskrifter/forskrift-2020-07-07-1521.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-07-1521) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-07-1521.md) |
| [Forskrift om midlertidig kompensasjonsordning i forbindelse med avlysning eller ](../forskrifter/forskrift-2020-11-04-2245.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-04-2245) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-04-2245.md) |
| [Forskrift om midlertidig kompensasjonsordning i forbindelse med avlysning, steng](../forskrifter/forskrift-2020-11-04-2250.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-04-2250) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-04-2250.md) |
| [Forskrift om midlertidig kompensasjonsordning i forbindelse med avlysning, steng](../forskrifter/forskrift-2020-07-16-1568.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-16-1568) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-16-1568.md) |
| [Forskrift om midlertidig støtte til aktivitet for utøvende kunstnere rammet av o](../forskrifter/forskrift-2020-07-01-1462.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-01-1462) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-01-1462.md) |
| [Forskrift om midlertidig tilskudd til kulturarrangementer fra juli 2021 som følg](../forskrifter/forskrift-2021-05-14-1521.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-14-1521) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-14-1521.md) |
| [Forskrift om midlertidig tilskudd til kulturarrangementer første halvår 2021 som](../forskrifter/forskrift-2021-01-28-273.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-28-273) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-28-273.md) |
| [Forskrift om midlertidig tilskudd til kulturarrangementer som følge av covid-19](../forskrifter/forskrift-2020-10-19-2070.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-19-2070) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-19-2070.md) |
| [Forskrift om målbruk i offentleg teneste](../forskrifter/forskrift-1980-12-05-4938.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-12-05-4938) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-12-05-4938.md) |
| [Forskrift om målform i eksamensoppgåver.](../forskrifter/forskrift-1987-07-07-4148.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-07-07-4148) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-07-07-4148.md) |
| [Forskrift om omsetning av bøker (bokforskriften)](../forskrifter/forskrift-2023-12-21-2268.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-21-2268) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-21-2268.md) |
| [Forskrift om organisasjon, oppgaver og saksbehandling for Diskrimineringsnemnda](../forskrifter/forskrift-2017-12-20-2260.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-20-2260) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-20-2260.md) |
| [Forskrift om pengespill (pengespillforskriften)](../forskrifter/forskrift-2022-11-17-1978.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-17-1978) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-17-1978.md) |
| [Forskrift om produksjonstilskudd til nyhets- og aktualitetsmedier](../forskrifter/forskrift-2022-12-08-2117.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-08-2117) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-08-2117.md) |
| [Forskrift om regionale kulturfond](../forskrifter/forskrift-2025-06-10-985.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-10-985) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-10-985.md) |
| [Forskrift om representasjon av begge kjønn i statlige utvalg, styrer, råd, deleg](../forskrifter/forskrift-1996-02-02-110.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-02-02-110) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-02-02-110.md) |
| [Forskrift om sikkerhetsbestemmelser til lov om organisert kampaktivitet som till](../forskrifter/forskrift-2024-12-06-2944.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-06-2944) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-06-2944.md) |
| [Forskrift om språkvedtak i kommunar og fylkeskommunar (språkvedtaksforskrifta)](../forskrifter/forskrift-2019-12-20-2114.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-20-2114) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-20-2114.md) |
| [Forskrift om stadnamn](../forskrifter/forskrift-2017-05-23-638.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-23-638) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-23-638.md) |
| [Forskrift om statens stipend og garantiinntekter for kunstnere](../forskrifter/forskrift-1998-09-16-936.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-09-16-936) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-09-16-936.md) |
| [Forskrift om studieforbund godkjent av Kultur- og likestillingsdepartementet](../forskrifter/forskrift-2020-12-08-2896.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-08-2896) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-08-2896.md) |
| [Forskrift om søknad, utbetaling og kontroll av tilskudd til manuskriptutvikling ](../forskrifter/forskrift-2010-01-05-7.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-01-05-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-01-05-7.md) |
| [Forskrift om tilbakelevering av stjålne og ulovlig utførte kulturgjenstander](../forskrifter/forskrift-2001-10-04-1179.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-10-04-1179) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-10-04-1179.md) |
| [Forskrift om tilskudd fra Norsk kulturfond](../forskrifter/forskrift-2014-10-31-1387.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-10-31-1387) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-10-31-1387.md) |
| [Forskrift om tilskudd til arrangementer for idrett og fysisk aktivitet for perso](../forskrifter/forskrift-2022-12-05-2602.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-05-2602) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-05-2602.md) |
| [Forskrift om tilskudd til audiovisuell produksjon](../forskrifter/forskrift-2016-10-31-1264.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-31-1264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-31-1264.md) |
| [Forskrift om tilskudd til bygging og rehabilitering av anlegg for idrett og fysi](../forskrifter/forskrift-2026-06-05-1024.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-05-1024) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-05-1024.md) |
| [Forskrift om tilskudd til filmformidling](../forskrifter/forskrift-2016-10-12-1209.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-12-1209) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-12-1209.md) |
| [Forskrift om tilskudd til frivillige organisasjoner på familie- og likestillings](../forskrifter/forskrift-2022-01-14-70.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-14-70) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-14-70.md) |
| [Forskrift om tilskudd til frivillige organisasjoner som arbeider med problematis](../forskrifter/forskrift-2022-11-17-1980.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-17-1980) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-17-1980.md) |
| [Forskrift om tilskudd til frivilligsentraler](../forskrifter/forskrift-2022-06-30-1272.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-30-1272) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-30-1272.md) |
| [Forskrift om tilskudd til funksjonshemmedes organisasjoner](../forskrifter/forskrift-2023-01-01-122.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-01-122) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-01-122.md) |
| [Forskrift om tilskudd til informasjonsvirksomhet i politiske partier.](../forskrifter/forskrift-1999-02-08-199.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-02-08-199) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-02-08-199.md) |
| [Forskrift om tilskudd til lokale lyd- og bildemedier](../forskrifter/forskrift-2016-02-19-166.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-19-166) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-19-166.md) |
| [Forskrift om tilskudd til minoritetsspråklige publikasjoner](../forskrifter/forskrift-2003-10-22-1256.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-10-22-1256) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-10-22-1256.md) |
| [Forskrift om tilskudd til produksjon og formidling av audiovisuelle verk](../forskrifter/forskrift-2016-10-07-1196.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-07-1196) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-07-1196.md) |
| [Forskrift om tilskudd til samfunnsnyttige og humanitære organisasjoner fra spill](../forskrifter/forskrift-2022-12-05-2123.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-05-2123) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-05-2123.md) |
| [Forskrift om tilskudd til samiske nyhets- og aktualitetsmedier](../forskrifter/forskrift-2025-12-10-2490.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-10-2490) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-10-2490.md) |
| [Forskrift om tilskudd til utvikling, lansering og formidling av dataspill](../forskrifter/forskrift-2021-02-23-557.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-23-557) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-23-557.md) |
| [Forskrift om tilskudd til å styrke kjønns- og seksualitetsmangfold](../forskrifter/forskrift-2021-10-13-3048.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-10-13-3048) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-10-13-3048.md) |
| [Forskrift om unntak fra adgangen til å klage over vedtak i Norsk kulturråd, Nors](../forskrifter/forskrift-1987-11-20-924.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-11-20-924) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-11-20-924.md) |
| [Forskrift om utførsel og innførsel av kulturgjenstander](../forskrifter/forskrift-2007-01-01-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-01-01-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-01-01-1.md) |
| [Forskrift om vigselrett for studentpresten i Bonn.](../forskrifter/forskrift-1973-12-18-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1973-12-18-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1973-12-18-1.md) |
| [Forskrift om virksomheten i Norsk rikskringkasting under beredskap og i krig.](../forskrifter/forskrift-1989-10-06-4154.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-10-06-4154) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-10-06-4154.md) |
| [Forskrift til lov om avgift på omsetning av billedkunst](../forskrifter/forskrift-1990-09-28-778.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-09-28-778) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-09-28-778.md) |
| [Forskrift til lov om kollektiv forvaltning av opphavsrett mv.](../forskrifter/forskrift-2021-08-09-2484.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-09-2484) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-09-2484.md) |
| [Forskrift til lov om register for frivillig virksomhet](../forskrifter/forskrift-2008-10-15-1214.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-10-15-1214) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-10-15-1214.md) |
| [Forskrift til stiftelsesloven mv.](../forskrifter/forskrift-2004-12-21-1793.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-21-1793) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-21-1793.md) |
| [Forskrift til åndsverkloven](../forskrifter/forskrift-2021-08-26-2608.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-26-2608) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-26-2608.md) |
| [Forskrifter for Statens barne- og ungdomsråd.](../forskrifter/forskrift-1985-01-25-3553.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-01-25-3553) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-01-25-3553.md) |
| [Forskrifter for bruk av Den norske kirkes våpen.](../forskrifter/forskrift-1990-06-08-4151.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-06-08-4151) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-06-08-4151.md) |
| [Forskrifter om fjernsynsmottakere](../forskrifter/forskrift-1980-10-23-8798.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-10-23-8798) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-10-23-8798.md) |
| [Forskrifter om opplysningsplikt og om betaling av avgifter til Det norske kompon](../forskrifter/forskrift-1966-10-18-9040.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-10-18-9040) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-10-18-9040.md) |
| [Godkjenning av våpen og flagg for Den norske kirke](../forskrifter/forskrift-1990-09-28-866.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-09-28-866) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-09-28-866.md) |
| [Ikraftsetting og overgangsregler for lov 28. mai 2021 nr. 49 om kollektiv forval](../forskrifter/forskrift-2021-05-28-1685.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-28-1685) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-28-1685.md) |
| [Ikrafttredelse av lov 2. februar 1996 nr. 6 om endringer i lov 4. desember 1992 ](../forskrifter/forskrift-1996-04-26-381.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-04-26-381) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-04-26-381.md) |
| [Ikrafttredelse av lov 9. juni 1989 nr. 33 om endringer i lov 13. juni 1980 nr. 3](../forskrifter/forskrift-1990-02-16-108.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-02-16-108) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-02-16-108.md) |
| [Instruks for Statskontrollen ved Norsk Tipping AS.](../forskrifter/forskrift-2000-03-21-285.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-03-21-285) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-03-21-285.md) |
| [Instruks for institusjonar som forvaltar dokument innkomne etter lov om avleveri](../forskrifter/forskrift-1990-05-25-4696.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-05-25-4696) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-05-25-4696.md) |
| [Iverksetjing av lov 9. juni 1989 nr. 32 om avleveringsplikt for allment tilgjeng](../forskrifter/forskrift-1990-05-25-366.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-05-25-366) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-05-25-366.md) |
| [Kampaktivitetslisten](../forskrifter/forskrift-2016-12-22-1924.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-22-1924) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-22-1924.md) |
| [Vedtak om norsk vigselsrett for den til enhver tid fungerende sjømannsprest i Mi](../forskrifter/forskrift-2005-05-25-483.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-05-25-483) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-05-25-483.md) |
| [Vedtak om utvidelse av det geografiske virkeområdet for lov om arkiv til også å ](../forskrifter/forskrift-2001-03-09-192.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-03-09-192) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-03-09-192.md) |
| [Vedtak om vigselrett for norsk prest på Solgården i Alicante i Spania.](../forskrifter/forskrift-1982-10-26-1527.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-10-26-1527) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-10-26-1527.md) |
| [Vedtak om vigselsrett for den norske sjømannsprest i Gøteborg.](../forskrifter/forskrift-1983-01-20-903.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-01-20-903) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-01-20-903.md) |
| [Vedtak om vigselsrett for norsk prest i Bangkok.](../forskrifter/forskrift-2002-02-06-1916.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-02-06-1916) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-02-06-1916.md) |
| [Vedtekter for Norsk Tipping AS](../forskrifter/forskrift-1992-12-11-1266.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-11-1266) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-11-1266.md) |
| [Vigselrett for norske prester i Spania.](../forskrifter/forskrift-1992-02-21-305.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-02-21-305) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-02-21-305.md) |
| [Vigselsrett for den til enhver tid fungerende sjømannsprest i Houston, Texas, US](../forskrifter/forskrift-1988-03-23-247.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-03-23-247) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-03-23-247.md) |
| [Vigselsrett for den til enhver tid fungerende sjømannsprest i Japan.](../forskrifter/forskrift-1987-06-22-546.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-06-22-546) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-06-22-546.md) |
