# Digitaliserings- og forvaltningsdepartementet

*69 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Delegering av Kongens kompetanse etter lov 19. juni 2015 nr. 70 om informasjonsp](../forskrifter/forskrift-2016-02-05-96.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-05-96) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-05-96.md) |
| [Delegering av Kongens myndighet etter ekomloven § 1-2 andre ledd og § 1-3 andre ](../forskrifter/forskrift-2024-12-13-3093.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-13-3093) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-13-3093.md) |
| [Delegering av Kongens myndighet etter lov 10. april 2025 nr. 9 om statsføretak §](../forskrifter/forskrift-2026-03-06-345.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-06-345) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-06-345.md) |
| [Delegering av Kongens myndighet etter lov om statens ansatte mv. (statsansattelo](../forskrifter/forskrift-2017-06-16-764.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-16-764) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-16-764.md) |
| [Delegering av Kongens myndighet etter statsforetakslovens regler om ansatterepre](../forskrifter/forskrift-2014-06-20-810.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-20-810) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-20-810.md) |
| [Delegering av forskriftskompetanse etter lov 19. juni 2015 nr. 70 om informasjon](../forskrifter/forskrift-2015-09-25-1086.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-25-1086) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-25-1086.md) |
| [Delegering av myndighet etter lov om elektroniske tillitstjenester](../forskrifter/forskrift-2019-11-08-1491.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-08-1491) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-08-1491.md) |
| [Delegering av myndighet etter lov om statsforetak](../forskrifter/forskrift-1991-12-20-827.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-12-20-827) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-12-20-827.md) |
| [Delegering av myndighet etter straffeprosessloven § 118](../forskrifter/forskrift-2024-11-26-2873.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-26-2873) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-26-2873.md) |
| [Delegering av myndighet fra Kommunal- og moderniseringsdepartementet til Digital](../forskrifter/forskrift-2021-02-05-494.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-05-494) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-05-494.md) |
| [Delegering av myndighet fra Kommunal- og moderniseringsdepartementet til Nasjona](../forskrifter/forskrift-2021-01-27-243.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-27-243) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-27-243.md) |
| [Delegering av myndighet til Arbeids- og administrasjonsdepartementet etter lov o](../forskrifter/forskrift-2002-05-15-450.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-05-15-450) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-05-15-450.md) |
| [Delegering av myndighet til Justis- og politidepartementet etter ekomloven § 5-3](../forskrifter/forskrift-2005-03-14-233.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-03-14-233) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-03-14-233.md) |
| [Delegering av myndighet til Post- og teletilsynet etter ekomloven § 1-4.](../forskrifter/forskrift-2004-02-16-427.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-02-16-427) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-02-16-427.md) |
| [Delegering av myndighet til Post- og teletilsynet etter ekomloven § 2-7, § 2-8 o](../forskrifter/forskrift-2013-05-13-472.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-13-472) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-13-472.md) |
| [Delegering av myndighet til Post- og teletilsynet i ekspropriasjonssaker etter l](../forskrifter/forskrift-2009-03-31-392.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-03-31-392) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-03-31-392.md) |
| [Delegering av myndighet til Samferdselsdepartementet etter ekomloven § 1-2](../forskrifter/forskrift-2008-01-11-9.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-01-11-9) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-01-11-9.md) |
| [Delegering av myndighet til Samferdselsdepartementet etter ekomloven § 1-2, § 1-](../forskrifter/forskrift-2003-07-04-880.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-04-880) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-04-880.md) |
| [Forskrift om Digitaliseringsdirektoratets tilgang til taushetsbelagte opplysning](../forskrifter/forskrift-2023-06-20-955.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-20-955) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-20-955.md) |
| [Forskrift om Digitalt dødsbo](../forskrifter/forskrift-2024-12-19-3276.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-19-3276) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-19-3276.md) |
| [Forskrift om EØS-krav til elektromagnetisk kompatibilitet (EMC) for utstyr til e](../forskrifter/forskrift-2016-04-15-378.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-04-15-378) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-04-15-378.md) |
| [Forskrift om EØS-krav til maritimt radioutstyr](../forskrifter/forskrift-2016-09-29-1161.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-29-1161) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-29-1161.md) |
| [Forskrift om EØS-krav til radioutstyr](../forskrifter/forskrift-2016-04-15-377.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-04-15-377) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-04-15-377.md) |
| [Forskrift om EØS-krav til sikkerhet for utstyr til elektronisk kommunikasjon](../forskrifter/forskrift-2016-04-15-379.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-04-15-379) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-04-15-379.md) |
| [Forskrift om IT-standarder i offentlig forvaltning](../forskrifter/forskrift-2013-04-05-959.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-04-05-959) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-04-05-959.md) |
| [Forskrift om Klagenemnda for elektronisk kommunikasjon](../forskrifter/forskrift-2025-12-23-2895.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-23-2895) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-23-2895.md) |
| [Forskrift om Norsk Lysingsblad. Innrykking og betaling for proklamaer og ektepak](../forskrifter/forskrift-1949-01-20-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1949-01-20-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1949-01-20-1.md) |
| [Forskrift om Norsk Lysningsblad](../forskrifter/forskrift-1948-06-22-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1948-06-22-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1948-06-22-1.md) |
| [Forskrift om anvendelse av lov 16. juni 2017 nr. 67 om statens ansatte mv. (stat](../forskrifter/forskrift-2025-12-12-2509.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-12-2509) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-12-2509.md) |
| [Forskrift om autorisasjon for virksomhet som utfører installasjon og vedlikehold](../forskrifter/forskrift-2011-12-07-1206.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-07-1206) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-07-1206.md) |
| [Forskrift om behandling av dødsbo når avdøde ikke har arvinger og departementets](../forskrifter/forskrift-2022-09-15-1583.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-15-1583) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-15-1583.md) |
| [Forskrift om datasenter](../forskrifter/forskrift-2024-12-18-3313.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-18-3313) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-18-3313.md) |
| [Forskrift om de ansattes rett til representasjon i styret i statsforetak mv.](../forskrifter/forskrift-2026-03-20-449.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-20-449) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-20-449.md) |
| [Forskrift om delegering av myndighet etter lov om elektronisk kommunikasjon (eko](../forskrifter/forskrift-2024-12-20-3413.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3413) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3413.md) |
| [Forskrift om domenenavn under norske landkodetoppdomener (domeneforskriften)](../forskrifter/forskrift-2003-08-01-990.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-01-990) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-01-990.md) |
| [Forskrift om elektronisk faktura i offentlige anskaffelser](../forskrifter/forskrift-2019-04-01-444.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-04-01-444) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-04-01-444.md) |
| [Forskrift om elektronisk kommunikasjon med og i forvaltningen (eForvaltningsfors](../forskrifter/forskrift-2004-06-25-988.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-25-988) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-25-988.md) |
| [Forskrift om elektroniske kommunikasjonsnett og elektroniske kommunikasjonstjene](../forskrifter/forskrift-2024-12-20-3410.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3410) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3410.md) |
| [Forskrift om elsikkerhet i elektronisk kommunikasjonsnett](../forskrifter/forskrift-2005-09-27-1094.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-09-27-1094) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-09-27-1094.md) |
| [Forskrift om endring i forskrift om delegering av myndighet etter lov om elektro](../forskrifter/forskrift-2025-12-23-2896.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-23-2896) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-23-2896.md) |
| [Forskrift om etablering, drift og bruk av jordstasjon for satellitt i Antarktis](../forskrifter/forskrift-2017-04-21-492.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-21-492) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-21-492.md) |
| [Forskrift om etablering, drift og bruk av jordstasjon for satellitt på Svalbard](../forskrifter/forskrift-2017-04-21-493.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-21-493) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-21-493.md) |
| [Forskrift om generelle tillatelser til bruk av frekvenser (fribruksforskriften)](../forskrifter/forskrift-2012-01-19-77.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-19-77) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-19-77.md) |
| [Forskrift om innkjøpsordning for funksjonell internettilgang](../forskrifter/forskrift-2025-09-25-1997.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-25-1997) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-25-1997.md) |
| [Forskrift om klassifisering og sikring av anlegg i elektroniske kommunikasjonsne](../forskrifter/forskrift-2012-09-10-866.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-09-10-866) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-09-10-866.md) |
| [Forskrift om koordinering og bruk av satellittinnmelding (satellittinnmeldingsfo](../forskrifter/forskrift-2017-12-12-1989.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-12-1989) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-12-1989.md) |
| [Forskrift om nummerressurser for elektroniske kommunikasjonsnett og -tjenester (](../forskrifter/forskrift-2004-02-16-426.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-02-16-426) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-02-16-426.md) |
| [Forskrift om overføring av fullmakter til Forbruker- og administrasjonsdeparteme](../forskrifter/forskrift-1975-03-07-8625.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1975-03-07-8625) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1975-03-07-8625.md) |
| [Forskrift om prioritet i mobilnett](../forskrifter/forskrift-2013-10-21-1241.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-10-21-1241) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-10-21-1241.md) |
| [Forskrift om radioamatørvirksomhet](../forskrifter/forskrift-2026-03-23-465.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-23-465) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-23-465.md) |
| [Forskrift om registrering og krav til innførsel og omsetning av radio-, teleterm](../forskrifter/forskrift-2002-03-15-276.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-03-15-276) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-03-15-276.md) |
| [Forskrift om sektoravgift og gebyr til Nasjonal kommunikasjonsmyndigheit](../forskrifter/forskrift-2024-01-17-79.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-17-79) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-17-79.md) |
| [Forskrift om selvdeklarasjon av ordninger for elektronisk identifikasjon (selvde](../forskrifter/forskrift-2019-11-21-1578.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-21-1578) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-21-1578.md) |
| [Forskrift om stedlig virkeområde for lov om elektronisk kommunikasjon vedrørende](../forskrifter/forskrift-2024-12-13-3094.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-13-3094) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-13-3094.md) |
| [Forskrift om tillitstjenester for elektroniske transaksjoner](../forskrifter/forskrift-2019-11-21-1577.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-21-1577) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-21-1577.md) |
| [Forskrift om universell utforming av informasjons- og kommunikasjonsteknologiske](../forskrifter/forskrift-2013-06-21-732.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-21-732) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-21-732.md) |
| [Forskrift til ehandelsloven (ehandelsforskriften).](../forskrifter/forskrift-2003-06-12-744.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-12-744) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-12-744.md) |
| [Forskrift til lov av 18. juli 1958 nr. 2 om offentlige tjenestetvister.](../forskrifter/forskrift-2002-05-15-451.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-05-15-451) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-05-15-451.md) |
| [Forskrift til lov om informasjonsplikt, karantene og saksforbud for politikere, ](../forskrifter/forskrift-2015-12-02-1380.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-02-1380) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-02-1380.md) |
| [Forskrift til lov om statens ansatte mv.](../forskrifter/forskrift-2017-06-21-838.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-21-838) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-21-838.md) |
| [Forskrifter for Norsk Lysingsblad](../forskrifter/forskrift-1975-03-07-8626.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1975-03-07-8626) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1975-03-07-8626.md) |
| [Funksjonsfordeling innen myndigheten etter ekomloven av 4. juli 2003 nr. 83](../forskrifter/forskrift-2021-06-18-2024.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-18-2024) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-18-2024.md) |
| [Instruks for arbeidet med forebyggende objekt- og infrastruktursikkerhet for dep](../forskrifter/forskrift-2021-02-05-328.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-05-328) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-05-328.md) |
| [Instruks for utrangering, kassasjon og avhending av materiell og fast eiendom so](../forskrifter/forskrift-1978-03-17-9.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-03-17-9) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-03-17-9.md) |
| [Instruks om avhending av fast eiendom som tilhører staten og overføring av fast ](../forskrifter/forskrift-1997-12-19-1530.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-19-1530) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-19-1530.md) |
| [Instruks om håndtering av bygge- og leiesaker i statlig sivil sektor](../forskrifter/forskrift-2012-01-20-39.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-20-39) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-20-39.md) |
| [Resolution om Kongens Titel.](../forskrifter/forskrift-1905-11-15-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1905-11-15-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1905-11-15-1.md) |
| [Vedtak om at tjenestetvistloven gjøres gjeldende for undervisningspersonale ved ](../forskrifter/forskrift-1983-10-28-1588.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-10-28-1588) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-10-28-1588.md) |
| [Vedtak om dispensasjon for nøkkelpersonell med kritiske samfunnsfunksjoner for N](../forskrifter/forskrift-2020-03-13-362.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-13-362) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-13-362.md) |
