# Barne- og familiedepartementet

*148 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Behandling av klager på avslag på innsyn i saker/dokumenter knyttet til tilsyn p](../forskrifter/forskrift-2013-12-16-1796.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-16-1796) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-16-1796.md) |
| [Delegering av Kongens myndighet etter barnevernloven § 2-5 første ledd annet pun](../forskrifter/forskrift-2013-01-25-73.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-01-25-73) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-01-25-73.md) |
| [Delegering av Kongens myndighet etter finansavtaleloven § 3-55 fjerde ledd andre](../forskrifter/forskrift-2023-06-16-933.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-16-933) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-16-933.md) |
| [Delegering av Kongens myndighet etter forsikringsavtaleloven § 20-1 og finansavt](../forskrifter/forskrift-2016-06-17-704.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-17-704) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-17-704.md) |
| [Delegering av Kongens myndighet etter forvaltningsloven § 13g til Barne- og fami](../forskrifter/forskrift-2024-12-20-3304.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3304) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3304.md) |
| [Delegering av Kongens myndighet etter gjeldsordningsloven § 2-1 første ledd anne](../forskrifter/forskrift-2014-05-14-641.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-05-14-641) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-05-14-641.md) |
| [Delegering av Kongens myndighet etter lov 10. juni 2005 nr. 40 om Likestillings-](../forskrifter/forskrift-2013-11-15-1317.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-15-1317) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-15-1317.md) |
| [Delegering av Kongens myndighet etter lov 18. juni 2021 nr. 97 om barnevern (bar](../forskrifter/forskrift-2022-11-25-2023.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-25-2023) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-25-2023.md) |
| [Delegering av Kongens myndighet etter lov 18. juni 2021 nr. 98 om Opplysningsves](../forskrifter/forskrift-2021-06-18-1971.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-18-1971) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-18-1971.md) |
| [Delegering av Kongens myndighet etter lov 20. juni 2008 nr. 42 om forbud mot dis](../forskrifter/forskrift-2013-06-21-717.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-21-717) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-21-717.md) |
| [Delegering av Kongens myndighet etter lov 24. april 2020 nr. 31 om tros- og livs](../forskrifter/forskrift-2020-12-18-2828.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2828) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2828.md) |
| [Delegering av Kongens myndighet etter lov 25. juni 2024 nr. 58 om omdanning av O](../forskrifter/forskrift-2024-06-25-1220.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-25-1220) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-25-1220.md) |
| [Delegering av Kongens myndighet etter lov 4. desember 1992 nr. 126 om arkiv § 12](../forskrifter/forskrift-2020-12-18-2829.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2829) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2829.md) |
| [Delegering av Kongens myndighet etter lov om behandling av opplysninger i kredit](../forskrifter/forskrift-2022-05-20-884.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-20-884) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-20-884.md) |
| [Delegering av Kongens myndighet til å gi forskrifter etter § 7-1 fjerde ledd i l](../forskrifter/forskrift-1992-12-18-1075.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-18-1075) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-18-1075.md) |
| [Delegering av Kongens myndighet til å utpeke namsmann som skal behandle søknader](../forskrifter/forskrift-2019-06-21-810.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-21-810) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-21-810.md) |
| [Delegering av Kongens myndighet til å utpeke namsmann som skal behandle søknader](../forskrifter/forskrift-2017-09-22-1441.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-22-1441) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-22-1441.md) |
| [Delegering av myndighet etter barnevernsloven og forskrift om barnevernslovens a](../forskrifter/forskrift-2022-12-22-2510.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-22-2510) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-22-2510.md) |
| [Delegering av myndighet etter barnevernsloven til Barne-, ungdoms- og familiedir](../forskrifter/forskrift-2022-12-22-2497.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-22-2497) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-22-2497.md) |
| [Delegering av myndighet etter barnevernsloven til Sentralenheten for barneverns-](../forskrifter/forskrift-2022-12-22-2499.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-22-2499) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-22-2499.md) |
| [Delegering av myndighet etter barnevernsloven til Statens helsetilsyn](../forskrifter/forskrift-2022-12-22-2498.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-22-2498) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-22-2498.md) |
| [Delegering av myndighet etter lov av 13. desember 1991 nr. 81 om sosiale tjenest](../forskrifter/forskrift-1992-10-02-690.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-10-02-690) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-10-02-690.md) |
| [Delegering av myndighet etter lov om produktkontroll.](../forskrifter/forskrift-1990-09-07-730.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-09-07-730) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-09-07-730.md) |
| [Delegering av myndighet i enkelte bestemmelser på familierettsområdet.](../forskrifter/forskrift-2002-10-11-1097.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-10-11-1097) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-10-11-1097.md) |
| [Delegering av myndighet til Arbeids- og velferdsdirektoratet etter barnelova § 8](../forskrifter/forskrift-2006-05-31-615.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-05-31-615) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-05-31-615.md) |
| [Delegering av myndighet til Arbeids- og velferdsdirektoratet etter straffeloven ](../forskrifter/forskrift-2006-05-31-616.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-05-31-616) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-05-31-616.md) |
| [Delegering av myndighet til Arbeids- og velferdsdirektoratet etter straffeproses](../forskrifter/forskrift-2018-01-30-118.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-01-30-118) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-01-30-118.md) |
| [Delegering av myndighet til Barne- og familiedepartementet etter barnelova § 85 ](../forskrifter/forskrift-2004-11-26-1525.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-11-26-1525) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-11-26-1525.md) |
| [Delegering av myndighet til Barne- og familiedepartementet etter likestillingslo](../forskrifter/forskrift-1998-07-17-738.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-07-17-738) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-07-17-738.md) |
| [Delegering av myndighet til Barne- og familiedepartementet etter lov om ekteskap](../forskrifter/forskrift-2004-09-10-1254.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-09-10-1254) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-09-10-1254.md) |
| [Delegering av myndighet til Barne- og familiedepartementet etter lov om merking ](../forskrifter/forskrift-1995-12-22-1036.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-12-22-1036) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-12-22-1036.md) |
| [Delegering av myndighet til Barne-, ungdoms- og familiedirektoratet etter ektesk](../forskrifter/forskrift-2015-12-11-1667.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-11-1667) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-11-1667.md) |
| [Delegering av myndighet til Barne-, ungdoms- og familiedirektoratet etter forval](../forskrifter/forskrift-2013-05-02-973.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-02-973) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-02-973.md) |
| [Delegering av myndighet til Barne-, ungdoms- og familiedirektoratet etter lov om](../forskrifter/forskrift-2004-09-30-1313.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-09-30-1313) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-09-30-1313.md) |
| [Delegering av myndighet til Energidepartementet etter lov om merking av forbruks](../forskrifter/forskrift-2011-01-28-100.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-01-28-100) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-01-28-100.md) |
| [Delegering av myndighet til Helsedepartementet etter produktkontrolloven § 4.](../forskrifter/forskrift-2002-08-16-902.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-08-16-902) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-08-16-902.md) |
| [Delegering av myndighet til Nærings- og handelsdepartementet etter produktkontro](../forskrifter/forskrift-2003-05-09-567.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-05-09-567) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-05-09-567.md) |
| [Delegering av myndighet til Samferdselsdepartementet etter lov om merking av for](../forskrifter/forskrift-2011-01-28-101.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-01-28-101) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-01-28-101.md) |
| [Delegering av myndighet til Samferdselsdepartementet etter lov om merking av for](../forskrifter/forskrift-2012-12-07-1185.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-07-1185) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-07-1185.md) |
| [Delegering av myndighet til Samferdselsdepartementet etter lov om merking av for](../forskrifter/forskrift-2013-06-21-715.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-21-715) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-21-715.md) |
| [Delegering av myndighet til Statens ungdoms- og adopsjonskontor etter lov om ekt](../forskrifter/forskrift-2002-04-01-1090.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-04-01-1090) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-04-01-1090.md) |
| [Delegering av myndighet til landets statsforvaltere om fritak fra barnevernslove](../forskrifter/forskrift-2012-10-05-955.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-05-955) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-05-955.md) |
| [Delegering av myndighet til å anerkjenne utenlandske skilsmisser og separasjoner](../forskrifter/forskrift-1992-03-27-292.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-03-27-292) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-03-27-292.md) |
| [Delegering av myndighet til å frita fra lovbestemt taushetsplikt etter barnehage](../forskrifter/forskrift-1994-01-14-25.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-01-14-25) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-01-14-25.md) |
| [Delegering av myndighet til å overføre saker fra kommunal barneverntjeneste til ](../forskrifter/forskrift-2011-02-16-152.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-16-152) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-16-152.md) |
| [Endringer i fylkesnemndenes struktur, stedlige virkeområde og navn](../forskrifter/forskrift-2019-11-22-1547.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-22-1547) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-22-1547.md) |
| [Forskrift om Barne-, ungdoms- og familieetatens rett til å kreve egenbetaling fr](../forskrifter/forskrift-2003-11-26-1397.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-11-26-1397) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-11-26-1397.md) |
| [Forskrift om Barnesakkyndig kommisjon](../forskrifter/forskrift-2022-08-12-1430.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-12-1430) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-12-1430.md) |
| [Forskrift om Den norske kirkes medlemsregister](../forskrifter/forskrift-2021-11-14-3326.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-14-3326) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-14-3326.md) |
| [Forskrift om Digital gravferdsmelding](../forskrifter/forskrift-2024-06-05-940.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-05-940) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-05-940.md) |
| [Forskrift om Forbrukertilsynets og Markedsrådets saksbehandling mv.](../forskrifter/forskrift-2017-11-21-1817.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-11-21-1817) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-11-21-1817.md) |
| [Forskrift om Reservasjonsregisteret](../forskrifter/forskrift-2009-06-05-598.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-05-598) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-05-598.md) |
| [Forskrift om adopsjon](../forskrifter/forskrift-2018-06-22-959.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-959) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-959.md) |
| [Forskrift om anvendelse av familievernkontorloven på Svalbard](../forskrifter/forskrift-2008-05-23-479.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-23-479) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-23-479.md) |
| [Forskrift om barnevernslovens anvendelse på Svalbard](../forskrifter/forskrift-1995-09-01-772.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-09-01-772) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-09-01-772.md) |
| [Forskrift om barnevernstjenestens oppfølging av barn på barnevernsinstitusjon (o](../forskrifter/forskrift-2022-12-15-2240.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-15-2240) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-15-2240.md) |
| [Forskrift om barns medvirkning i barnevernet](../forskrifter/forskrift-2023-10-12-1631.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-12-1631) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-12-1631.md) |
| [Forskrift om barns rettigheter i barnevernsinstitusjon](../forskrifter/forskrift-2022-12-20-2358.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2358) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2358.md) |
| [Forskrift om behandling av begjæringer om anerkjennelse av ekteskap etter ektesk](../forskrifter/forskrift-2024-12-20-3300.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3300) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3300.md) |
| [Forskrift om behandling av forbrukerklager i Forbrukertilsynet og Forbrukerklage](../forskrifter/forskrift-2020-12-21-3084.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-21-3084) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-21-3084.md) |
| [Forskrift om behandling av opplysninger i kredittopplysningsvirksomhet (kreditto](../forskrifter/forskrift-2022-05-20-883.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-20-883) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-20-883.md) |
| [Forskrift om behandling av personopplysninger i programmet Sammen på vei](../forskrifter/forskrift-2024-06-13-1053.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-13-1053) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-13-1053.md) |
| [Forskrift om delegering av myndighet etter lov av 8. april 1981 nr. 7 om barn og](../forskrifter/forskrift-1985-04-12-842.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-04-12-842) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-04-12-842.md) |
| [Forskrift om ettergjeving.](../forskrifter/forskrift-1992-10-13-762.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-10-13-762) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-10-13-762.md) |
| [Forskrift om fastsetjing av medmorskap](../forskrifter/forskrift-2008-12-15-1362.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-15-1362) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-15-1362.md) |
| [Forskrift om fastsetjing og endring av fostringstilskot](../forskrifter/forskrift-2003-01-15-123.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-15-123) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-15-123.md) |
| [Forskrift om fastsetting og endring av oppfostringsbidrag etter lov om barnevern](../forskrifter/forskrift-2006-06-23-723.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-23-723) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-23-723.md) |
| [Forskrift om forvaltning av kulturhistorisk verdifulle kirker (kirkebyggforskrif](../forskrifter/forskrift-2020-12-18-2827.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2827) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2827.md) |
| [Forskrift om fosterhjem](../forskrifter/forskrift-2023-10-13-1632.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-13-1632) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-13-1632.md) |
| [Forskrift om frivillig merking av lydnivå ved husholdningsapparater](../forskrifter/forskrift-1996-05-29-566.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-05-29-566) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-05-29-566.md) |
| [Forskrift om fysisk sikkerheit i krisesentertilbodet](../forskrifter/forskrift-2017-03-07-282.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-03-07-282) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-03-07-282.md) |
| [Forskrift om føring av klientjournal og meklingsprotokoll ved familievernkontore](../forskrifter/forskrift-2007-12-20-1763.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-20-1763) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-20-1763.md) |
| [Forskrift om gebyr for offentlig fastsettelse av barnebidrag](../forskrifter/forskrift-2001-11-04-1250.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-11-04-1250) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-11-04-1250.md) |
| [Forskrift om gjennomføringen av bestemmelsene om inntektsprøving av forskott](../forskrifter/forskrift-2003-02-06-125.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-06-125) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-06-125.md) |
| [Forskrift om godtgjering til andre som gjer teneste etter barnelova § 61 første ](../forskrifter/forskrift-2004-03-10-516.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-03-10-516) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-03-10-516.md) |
| [Forskrift om i hvilke tilfelle bidragsfogden skal fastsette eller endre bidrag a](../forskrifter/forskrift-1994-08-09-797.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-08-09-797) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-08-09-797.md) |
| [Forskrift om i hvilke tilfelle det kan ytes bidragsforskott til barn som har del](../forskrifter/forskrift-2003-09-25-1181.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-25-1181) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-25-1181.md) |
| [Forskrift om i hvilke tilfelle vilkåret i forskotteringsloven om bosted og oppho](../forskrifter/forskrift-1989-06-21-518.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-06-21-518) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-06-21-518.md) |
| [Forskrift om individuell plan ved ytelse av velferdstjenester](../forskrifter/forskrift-2022-06-22-1110.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-22-1110) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-22-1110.md) |
| [Forskrift om innlemmelse av forordning (EU) nr. 1007/2011 om tekstilfibernavn og](../forskrifter/forskrift-2012-10-25-990.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-25-990) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-25-990.md) |
| [Forskrift om klageorganer for forbrukersaker](../forskrifter/forskrift-2016-06-20-733.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-20-733) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-20-733.md) |
| [Forskrift om kommunale vigsler](../forskrifter/forskrift-2017-09-18-1421.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-18-1421) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-18-1421.md) |
| [Forskrift om krav til kvalitet og godkjenning av barnevernsinstitusjoner (kvalit](../forskrifter/forskrift-2022-12-22-2474.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-22-2474) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-22-2474.md) |
| [Forskrift om krystallglass](../forskrifter/forskrift-1997-07-03-773.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-07-03-773) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-07-03-773.md) |
| [Forskrift om livsoppholdssatser ved utleggstrekk og gjeldsordning](../forskrifter/forskrift-2014-06-13-724.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-13-724) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-13-724.md) |
| [Forskrift om mekling etter ekteskapsloven og barneloven.](../forskrifter/forskrift-2006-12-18-1478.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-18-1478) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-18-1478.md) |
| [Forskrift om merking av fottøy](../forskrifter/forskrift-1996-01-08-13.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-01-08-13) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-01-08-13.md) |
| [Forskrift om merking av retusjert reklame](../forskrifter/forskrift-2022-06-17-1114.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-17-1114) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-17-1114.md) |
| [Forskrift om når en utenlandsk statsborger skal anses å være fast bosatt i Norge](../forskrifter/forskrift-1992-11-05-979.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-11-05-979) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-11-05-979.md) |
| [Forskrift om opplysningsplikt og angrerett mv.](../forskrifter/forskrift-2014-06-20-777.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-20-777) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-20-777.md) |
| [Forskrift om oppnevnelse av og godtgjørelse til medhjelper under gjeldsforhandli](../forskrifter/forskrift-1992-12-04-885.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-885) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-885.md) |
| [Forskrift om overgangsbestemmelser til lov av 10. januar 2003 nr. 1 om endringer](../forskrifter/forskrift-2003-04-04-432.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-04-04-432) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-04-04-432.md) |
| [Forskrift om overgangsreglar i samband med nye reglar om fastsetjing av fostring](../forskrifter/forskrift-2003-01-15-119.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-15-119) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-15-119.md) |
| [Forskrift om overgangsreglar til lov 20. juni 2003 nr. 40 om endringer i barnelo](../forskrifter/forskrift-2004-02-24-471.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-02-24-471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-02-24-471.md) |
| [Forskrift om overgangsregler for det økonomiske ansvaret for hjelpetiltak i sent](../forskrifter/forskrift-2021-12-07-3419.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-07-3419) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-07-3419.md) |
| [Forskrift om overgangsregler til endringer i lov 8. mars 2002 nr. 4 om barnetryg](../forskrifter/forskrift-2024-06-26-1360.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-26-1360) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-26-1360.md) |
| [Forskrift om overgangsregler til lov 18. juni 2021 nr. 97 om barnevern (barnever](../forskrifter/forskrift-2022-12-15-2264.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-15-2264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-15-2264.md) |
| [Forskrift om pakkereiselovens anvendelse for Svalbard](../forskrifter/forskrift-2022-11-25-2021.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-25-2021) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-25-2021.md) |
| [Forskrift om pakkereiser og reisegaranti mv. (pakkereiseforskriften)](../forskrifter/forskrift-2018-06-22-954.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-954) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-954.md) |
| [Forskrift om politiattest etter barnevernsloven](../forskrifter/forskrift-2022-12-20-2359.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2359) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2359.md) |
| [Forskrift om prisopplysninger mv. for varer og tjenester](../forskrifter/forskrift-2012-11-14-1066.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-14-1066) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-14-1066.md) |
| [Forskrift om registrering av og tilskudd til tros- og livssynssamfunn (trossamfu](../forskrifter/forskrift-2020-12-18-2825.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2825) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2825.md) |
| [Forskrift om registrering og melding av vigsel](../forskrifter/forskrift-1992-11-20-854.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-11-20-854) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-11-20-854.md) |
| [Forskrift om rekneskapsføring av pensjonsutgifter for Den norske kyrkja (rettssu](../forskrifter/forskrift-2021-01-19-193.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-19-193) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-19-193.md) |
| [Forskrift om saksbehandlingen for statsforvalteren ved separasjon og skilsmisse ](../forskrifter/forskrift-1992-11-18-981.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-11-18-981) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-11-18-981.md) |
| [Forskrift om samla fastsetjing av tilskot i visse tilfelle.](../forskrifter/forskrift-2003-01-15-122.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-15-122) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-15-122.md) |
| [Forskrift om sammenlignende reklame](../forskrifter/forskrift-2000-12-19-1653.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-19-1653) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-19-1653.md) |
| [Forskrift om samtaleprosess i barneverns- og helsenemnda (samtaleprosessforskrif](../forskrifter/forskrift-2023-01-27-106.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-27-106) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-27-106.md) |
| [Forskrift om samvær med tilsyn etter barnelova](../forskrifter/forskrift-2013-12-19-1636.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-19-1636) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-19-1636.md) |
| [Forskrift om sentre for foreldre og barn](../forskrifter/forskrift-2022-12-22-2509.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-22-2509) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-22-2509.md) |
| [Forskrift om standard opplysningsskjemaer etter lov om avtaler om deltidsbruksre](../forskrifter/forskrift-2012-07-03-766.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-07-03-766) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-07-03-766.md) |
| [Forskrift om stans i utbetalinga av offentlege ytingar og barnebidrag når ein av](../forskrifter/forskrift-2015-07-01-847.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-07-01-847) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-07-01-847.md) |
| [Forskrift om statlig refusjon av utgifter til kommunale presteboliger.](../forskrifter/forskrift-2007-06-01-570.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-01-570) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-01-570.md) |
| [Forskrift om statsforvalterens adgang til å ilegge kommuner mulkt ved oversittel](../forskrifter/forskrift-1992-12-16-1243.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-16-1243) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-16-1243.md) |
| [Forskrift om særtilskot](../forskrifter/forskrift-2003-01-15-121.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-15-121) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-15-121.md) |
| [Forskrift om tildeling og tilbaketrekning av vigselsrett i tros- og livssynssamf](../forskrifter/forskrift-2020-12-18-2826.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2826) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2826.md) |
| [Forskrift om tilskudd til barnevernsfaglig videreutdanning](../forskrifter/forskrift-2022-12-20-2541.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2541) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2541.md) |
| [Forskrift om tilskudd til dialog, debatt, samarbeid og kunnskapsutvikling på tro](../forskrifter/forskrift-2022-03-16-435.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-16-435) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-16-435.md) |
| [Forskrift om tilskudd til frivillige barne- og ungdomsorganisasjoner](../forskrifter/forskrift-2022-01-18-90.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-18-90) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-18-90.md) |
| [Forskrift om tilskudd til inkludering av barn og unge](../forskrifter/forskrift-2021-11-23-3261.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-23-3261) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-23-3261.md) |
| [Forskrift om tilskudd til kulturhistorisk verdifulle kirkebygg](../forskrifter/forskrift-2024-06-23-1309.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-23-1309) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-23-1309.md) |
| [Forskrift om tilskudd til organisasjoner i barnevernet](../forskrifter/forskrift-2022-11-24-2046.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-24-2046) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-24-2046.md) |
| [Forskrift om tilskudd til tiltak mot vold og overgrep](../forskrifter/forskrift-2021-11-24-3297.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-24-3297) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-24-3297.md) |
| [Forskrift om tilskudd til utviklings- og samhandlingsprosjekter i barnevernet](../forskrifter/forskrift-2022-11-22-2034.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-22-2034) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-22-2034.md) |
| [Forskrift om tilsyn med tjenester og tiltak til barn i barnevernsinstitusjoner m](../forskrifter/forskrift-2022-12-16-2272.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-16-2272) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-16-2272.md) |
| [Forskrift om urimelig handelspraksis](../forskrifter/forskrift-2009-06-01-565.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-01-565) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-01-565.md) |
| [Forskrift om utmåling av tvangsmulkt og overtredelsesgebyr](../forskrifter/forskrift-2023-02-14-193.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-02-14-193) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-02-14-193.md) |
| [Forskrift om vedlikeholdsmerking av tekstilprodukter mv.](../forskrifter/forskrift-2004-10-01-1340.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-10-01-1340) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-10-01-1340.md) |
| [Forskrift om vilkår for rett til kontantstøtte til småbarnsforeldre – forholdet ](../forskrifter/forskrift-2000-10-03-984.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-10-03-984) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-10-03-984.md) |
| [Forskrift om virksomhet etter gjeldsinformasjonsloven (gjeldsinformasjonsforskri](../forskrifter/forskrift-2017-10-31-1691.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-31-1691) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-31-1691.md) |
| [Forskrift om å klargjere morskap](../forskrifter/forskrift-2013-12-17-1592.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-17-1592) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-17-1592.md) |
| [Forskrift om økonomiforvaltningen i sokn i Den norske kirke](../forskrifter/forskrift-2020-12-08-2646.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-08-2646) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-08-2646.md) |
| [Forskrift til lov om Haagkonvensjonen 1996 om sentralmyndigheten mv.](../forskrifter/forskrift-2016-06-07-604.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-07-604) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-07-604.md) |
| [Forskrift til lov om gravplasser, kremasjon og gravferd (gravplassforskriften)](../forskrifter/forskrift-1997-01-10-16.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-01-10-16) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-01-10-16.md) |
| [Forskrifter om adgangen til kirkelig vigsel for medlemmer av The Evangelical Lut](../forskrifter/forskrift-1952-05-08-6.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1952-05-08-6) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1952-05-08-6.md) |
| [Forskrifter om anerkjennelse av nordiske farskapsavgjørelser.](../forskrifter/forskrift-1981-11-20-8950.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-11-20-8950) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-11-20-8950.md) |
| [Forskrifter om indeksregulering av underholdsbidrag til barn.](../forskrifter/forskrift-1981-11-20-8986.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-11-20-8986) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-11-20-8986.md) |
| [Ikraftsetting av lov 4. september 2015 nr. 85 om gjennomføring av konvensjon 19.](../forskrifter/forskrift-2016-03-04-217.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-03-04-217) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-03-04-217.md) |
| [Ikrafttredelse av lov av 9. juni 1978 nr. 45 om likestilling mellom kjønnene. Un](../forskrifter/forskrift-1979-03-09-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1979-03-09-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1979-03-09-1.md) |
| [Instruks for barneombudet](../forskrifter/forskrift-1981-09-11-4877.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-09-11-4877) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-09-11-4877.md) |
| [Kirkeordning for Den norske kirke](../forskrifter/forskrift-2019-03-30-2307.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-30-2307) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-30-2307.md) |
| [Midlertidig forskrift om endring i forskrifter etter barnevernloven for å håndte](../forskrifter/forskrift-2022-06-20-1116.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-20-1116) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-20-1116.md) |
| [Overføring av ansvaret for markedsføringsloven kapittel 6 om beskyttelse av næri](../forskrifter/forskrift-2014-11-21-1472.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-21-1472) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-21-1472.md) |
| [Overføring av forvaltningsansvaret for lov om ekteskap del II, IV og V fra Barne](../forskrifter/forskrift-2007-08-10-957.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-08-10-957) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-08-10-957.md) |
| [Overgangsregler til lov om klageorganer for forbrukersaker (gjennomføring av dir](../forskrifter/forskrift-2016-06-20-735.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-20-735) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-20-735.md) |
| [Samtykke etter barnevernloven § 2-4 om å forlenge og utvide forsøk om tverretatl](../forskrifter/forskrift-2016-05-20-508.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-05-20-508) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-05-20-508.md) |
| [Vedtak om borgerlig vigselsformular](../forskrifter/forskrift-1996-01-19-4263.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-01-19-4263) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-01-19-4263.md) |
| [Vedtak om delegering av myndighet etter adopsjonsloven](../forskrifter/forskrift-2018-06-22-960.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-960) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-960.md) |
