# Energidepartementet

*105 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Delegering av Energidepartementets myndighet etter vassdragsreguleringsloven, va](../forskrifter/forskrift-2025-08-29-1756.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-29-1756) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-29-1756.md) |
| [Delegering av Kongens myndighet etter forskrift 12. desember 2008 nr. 1357 til l](../forskrifter/forskrift-2013-02-15-202.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-02-15-202) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-02-15-202.md) |
| [Delegering av Kongens myndighet etter havenergilova til Energidepartementet](../forskrifter/forskrift-2020-02-28-198.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-28-198) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-28-198.md) |
| [Delegering av Kongens myndighet etter vassdragsreguleringsloven, vannfallrettigh](../forskrifter/forskrift-2025-08-29-1739.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-29-1739) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-29-1739.md) |
| [Delegering av myndighet etter energiloven til Norges vassdrags- og energidirekto](../forskrifter/forskrift-2025-06-26-1340.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-26-1340) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-26-1340.md) |
| [Delegering av myndighet etter forvaltningsloven § 13d første ledd til Norges vas](../forskrifter/forskrift-2016-02-16-156.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-16-156) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-16-156.md) |
| [Delegering av myndighet etter forvaltningsloven § 13d første ledd til Regulering](../forskrifter/forskrift-2024-10-18-2522.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-18-2522) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-18-2522.md) |
| [Delegering av myndighet etter lov om elsertifikater § 18 annet ledd annet punktu](../forskrifter/forskrift-2011-12-16-1245.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-16-1245) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-16-1245.md) |
| [Delegering av myndighet etter lov om elsertifikater § 26](../forskrifter/forskrift-2012-09-03-930.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-09-03-930) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-09-03-930.md) |
| [Delegering av myndighet etter lov om kontroll med produkter og forbrukertjeneste](../forskrifter/forskrift-2010-10-12-1894.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-10-12-1894) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-10-12-1894.md) |
| [Delegering av myndighet til Energidepartementet etter lov av 18. mai 2001 nr. 23](../forskrifter/forskrift-2001-05-18-516.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-05-18-516) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-05-18-516.md) |
| [Delegering av myndighet til Norges vassdrags- og energidirektorat (NVE)](../forskrifter/forskrift-2011-02-17-1554.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-17-1554) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-17-1554.md) |
| [Delegering av myndighet til Norges vassdrags- og energidirektorat (NVE) etter lo](../forskrifter/forskrift-2020-09-29-1917.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-09-29-1917) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-09-29-1917.md) |
| [Delegering av myndighet til Oljedirektoratet etter lov om avgift på utslipp av C](../forskrifter/forskrift-1990-12-27-1229.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-12-27-1229) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-12-27-1229.md) |
| [Delegering av myndighet til Oljedirektoratet etter lov om petroleumsvirksomhet §](../forskrifter/forskrift-1991-10-04-1016.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-10-04-1016) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-10-04-1016.md) |
| [Delegering av myndighet til Oljedirektoratet etter petroleumsloven § 31 og forsk](../forskrifter/forskrift-1996-12-09-1097.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-12-09-1097) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-12-09-1097.md) |
| [Delegering av myndighet til Oljedirektoratet om vitenskapelige undersøkelser på ](../forskrifter/forskrift-1973-03-30-4702.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1973-03-30-4702) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1973-03-30-4702.md) |
| [Delegering av myndighet til Oljedirektoratet til å innhente data for bruk i forb](../forskrifter/forskrift-1998-10-15-4808.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-10-15-4808) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-10-15-4808.md) |
| [Delegering av myndighet til statsforvalteren for oppfølging av saker etter vannr](../forskrifter/forskrift-2025-12-05-2429.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-05-2429) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-05-2429.md) |
| [Fastsettelse av prinsipper for Petoro AS sin forvaltning av statens eierskap i s](../forskrifter/forskrift-2024-12-20-3328.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3328) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3328.md) |
| [Forskrift om Energiklagenemnda](../forskrifter/forskrift-2019-10-24-1420.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-24-1420) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-24-1420.md) |
| [Forskrift om Havbunnsmineralregisteret](../forskrifter/forskrift-2025-08-29-1747.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-29-1747) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-29-1747.md) |
| [Forskrift om Norgespris](../forskrifter/forskrift-2025-09-08-1790.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-08-1790) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-08-1790.md) |
| [Forskrift om Norgespris og strømstønad til husholdninger som bruker fjernvarme](../forskrifter/forskrift-2025-09-08-1792.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-08-1792) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-08-1792.md) |
| [Forskrift om Petroleumsregisteret.](../forskrifter/forskrift-1997-06-19-618.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-06-19-618) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-06-19-618.md) |
| [Forskrift om adgang til å kreve gebyr og sektoravgift for tilsyn og annen oppføl](../forskrifter/forskrift-2013-01-08-16.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-01-08-16) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-01-08-16.md) |
| [Forskrift om andres bruk av innretninger.](../forskrifter/forskrift-2005-12-20-1625.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-20-1625) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-20-1625.md) |
| [Forskrift om angivelse av husholdningsapparaters energi- og ressursforbruk ved h](../forskrifter/forskrift-1996-01-10-16.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-01-10-16) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-01-10-16.md) |
| [Forskrift om datainnsamling og dokumentasjon i mineralvirksomhet på kontinentals](../forskrifter/forskrift-2025-09-01-1767.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-01-1767) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-01-1767.md) |
| [Forskrift om deklarering av kjemikalier til produktregisteret (deklareringsforsk](../forskrifter/forskrift-2015-05-19-541.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-19-541) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-19-541.md) |
| [Forskrift om elektromagnetisk kompatibilitet](../forskrifter/forskrift-2017-10-10-1597.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-10-1597) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-10-1597.md) |
| [Forskrift om elsertifikater](../forskrifter/forskrift-2011-12-16-1398.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-16-1398) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-16-1398.md) |
| [Forskrift om endring i forskrift om utføring av aktiviteter i petroleumsvirksomh](../forskrifter/forskrift-2024-12-18-3263.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-18-3263) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-18-3263.md) |
| [Forskrift om endring i forskrift til lov om petroleumsvirksomhet.](../forskrifter/forskrift-1999-06-04-571.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-06-04-571) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-06-04-571.md) |
| [Forskrift om energikartlegging (energikartleggingsforskriften)](../forskrifter/forskrift-2024-09-25-2262.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-25-2262) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-25-2262.md) |
| [Forskrift om energimerking av bygninger og energivurdering av varme- og klimaanl](../forskrifter/forskrift-2009-12-18-1665.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-18-1665) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-18-1665.md) |
| [Forskrift om energimerking av energirelaterte produkter (energimerkeforskriften ](../forskrifter/forskrift-2013-05-27-534.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-27-534) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-27-534.md) |
| [Forskrift om energiutredninger](../forskrifter/forskrift-2024-01-25-106.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-25-106) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-25-106.md) |
| [Forskrift om fastsettelse av tariffer mv. for bestemte innretninger](../forskrifter/forskrift-2002-12-20-1724.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-12-20-1724) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-12-20-1724.md) |
| [Forskrift om fastsetting av normpriser](../forskrifter/forskrift-1976-06-25-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-06-25-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-06-25-5.md) |
| [Forskrift om fiskal måling i petroleumsvirksomheten (måleforskriften)](../forskrifter/forskrift-2023-04-21-532.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-04-21-532) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-04-21-532.md) |
| [Forskrift om forbud mot bruk av mineralolje til oppvarming av bygninger og fossi](../forskrifter/forskrift-2018-06-28-1060.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-28-1060) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-28-1060.md) |
| [Forskrift om gjennomføring av forordning (EU) 2020/2155 og forordning (EU) 2020/](../forskrifter/forskrift-2026-06-09-1032.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-06-09-1032) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-06-09-1032.md) |
| [Forskrift om gjennomføring i norsk rett av EØS-avtalen vedlegg IV nr. 47 (forord](../forskrifter/forskrift-2019-10-24-1434.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-24-1434) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-24-1434.md) |
| [Forskrift om gjennomføring i norsk rett av EØS-avtalens vedlegg IV som retter se](../forskrifter/forskrift-1992-12-11-1064.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-11-1064) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-11-1064.md) |
| [Forskrift om gjennomføring i norsk rett av vedlegg IV nr. 30 til EØS-avtala (for](../forskrifter/forskrift-2010-06-25-940.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-25-940) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-25-940.md) |
| [Forskrift om gjennomføringsreglar for rådsdirektiv 92/75/EØF med omsyn til energ](../forskrifter/forskrift-1998-05-04-463.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-05-04-463) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-05-04-463.md) |
| [Forskrift om helse, miljø og sikkerhet i petroleumsvirksomheten og på enkelte la](../forskrifter/forskrift-2010-02-12-158.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-02-12-158) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-02-12-158.md) |
| [Forskrift om håndtering av energiknapphet og kraftrasjonering](../forskrifter/forskrift-2023-12-19-2161.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-19-2161) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-19-2161.md) |
| [Forskrift om innbetaling av påslag på nettariffen til Energifondet (forskrift om](../forskrifter/forskrift-2001-12-10-1377.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-10-1377) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-10-1377.md) |
| [Forskrift om internkontroll etter vassdragslovgivningen (IK-vassdrag)](../forskrifter/forskrift-2011-10-28-1058.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-10-28-1058) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-10-28-1058.md) |
| [Forskrift om justering av konsesjonsavgifter, årlige erstatninger og fond m.v. i](../forskrifter/forskrift-1987-12-04-945.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-12-04-945) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-12-04-945.md) |
| [Forskrift om kommunalt tilsyn med anlegg for sikring mot flom, erosjon og skred ](../forskrifter/forskrift-2005-06-17-655.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-17-655) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-17-655.md) |
| [Forskrift om kommunens myndighet i mindre vannkraftsaker](../forskrifter/forskrift-2017-12-15-2037.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-15-2037) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-15-2037.md) |
| [Forskrift om kompensasjon til fiskere for tapt fangsttid ved lokalisering, oppta](../forskrifter/forskrift-2009-06-19-700.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-19-700) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-19-700.md) |
| [Forskrift om kost-nytteanalyse av mulighetene for å utnytte overskuddsvarme](../forskrifter/forskrift-2024-09-25-2263.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-25-2263) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-25-2263.md) |
| [Forskrift om leveringskvalitet i kraftsystemet](../forskrifter/forskrift-2004-11-30-1557.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-11-30-1557) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-11-30-1557.md) |
| [Forskrift om materiale og dokumentasjon ved undersøkelse etter og utnyttelse av ](../forskrifter/forskrift-2017-12-13-2003.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-13-2003) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-13-2003.md) |
| [Forskrift om måling, avregning, fakturering av nettjenester og elektrisk energi,](../forskrifter/forskrift-1999-03-11-301.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-03-11-301) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-03-11-301.md) |
| [Forskrift om nettregulering og energimarkedet (NEM)](../forskrifter/forskrift-2019-10-24-1413.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-24-1413) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-24-1413.md) |
| [Forskrift om oppgaveplikt ved brønnboring og grunnvannsundersøkelser.](../forskrifter/forskrift-1996-11-19-1066.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-11-19-1066) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-11-19-1066.md) |
| [Forskrift om opprinnelsesgarantier for produksjon av elektrisk energi](../forskrifter/forskrift-2007-12-14-1652.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-14-1652) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-14-1652.md) |
| [Forskrift om pliktig innmelding av grunnundersøkelser og naturfareutredninger](../forskrifter/forskrift-2024-12-17-3181.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-17-3181) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-17-3181.md) |
| [Forskrift om produksjon, omforming, overføring, omsetning, fordeling og bruk av ](../forskrifter/forskrift-1990-12-07-959.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-12-07-959) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-12-07-959.md) |
| [Forskrift om rammer for vannforvaltningen](../forskrifter/forskrift-2006-12-15-1446.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-15-1446) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-15-1446.md) |
| [Forskrift om rapporteringsplikt for kraftleveringsavtaler](../forskrifter/forskrift-2015-03-09-194.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-03-09-194) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-03-09-194.md) |
| [Forskrift om ressursforvaltning i petroleumsvirksomheten (ressursforskriften)](../forskrifter/forskrift-2017-12-13-2004.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-13-2004) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-13-2004.md) |
| [Forskrift om sektoravgift for dekning av kostnader til Norges vassdrags- og ener](../forskrifter/forskrift-2023-09-27-1518.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-27-1518) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-27-1518.md) |
| [Forskrift om sektoravgift og refusjon av utgifter for tilsyn med ressursforvaltn](../forskrifter/forskrift-1997-06-27-652.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-06-27-652) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-06-27-652.md) |
| [Forskrift om sikkerhet for undersøkelse og leteboring etter petroleumsforekomste](../forskrifter/forskrift-1988-03-25-250.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-03-25-250) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-03-25-250.md) |
| [Forskrift om sikkerhet og arbeidsmiljø ved mineralvirksomhet til havs (havbunnsm](../forskrifter/forskrift-2025-10-15-2050.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-15-2050) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-15-2050.md) |
| [Forskrift om sikkerhet og arbeidsmiljø ved transport og injeksjon av CO2på konti](../forskrifter/forskrift-2020-02-25-186.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-25-186) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-25-186.md) |
| [Forskrift om sikkerhet og beredskap i kraftforsyningen (kraftberedskapsforskrift](../forskrifter/forskrift-2012-12-07-1157.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-07-1157) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-07-1157.md) |
| [Forskrift om sikkerhet ved vassdragsanlegg (damsikkerhetsforskriften)](../forskrifter/forskrift-2009-12-18-1600.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-18-1600) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-18-1600.md) |
| [Forskrift om strømnettselskapenes inntekter (nettinntektsforskriften)](../forskrifter/forskrift-2025-01-14-50.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-14-50) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-14-50.md) |
| [Forskrift om strømstønad](../forskrifter/forskrift-2025-09-08-1791.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-08-1791) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-08-1791.md) |
| [Forskrift om systemansvaret i kraftsystemet](../forskrifter/forskrift-2002-05-07-448.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-05-07-448) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-05-07-448.md) |
| [Forskrift om tariffer og rapporteringsplikt for omsetningskonsesjonærer (forskri](../forskrifter/forskrift-1999-03-11-302.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-03-11-302) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-03-11-302.md) |
| [Forskrift om tilskudd til energitiltak i kommunalt eide utleieboliger, omsorgsbo](../forskrifter/forskrift-2022-12-28-2525.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-28-2525) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-28-2525.md) |
| [Forskrift om tilskudd til flom- og skredforebygging (forskrift om naturfaretilsk](../forskrifter/forskrift-2022-06-29-1237.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-29-1237) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-29-1237.md) |
| [Forskrift om trykkpåkjent utstyr](../forskrifter/forskrift-2017-10-10-1631.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-10-1631) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-10-1631.md) |
| [Forskrift om undersøkelse og utvinning av skjellsand, sand og grus i kystnære om](../forskrifter/forskrift-2023-12-20-2167.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-20-2167) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-20-2167.md) |
| [Forskrift om utleie av vannkraftanlegg](../forskrifter/forskrift-2010-06-25-939.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-25-939) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-25-939.md) |
| [Forskrift om utnyttelse av undersjøiske reservoarer på kontinentalsokkelen til l](../forskrifter/forskrift-2014-12-05-1517.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-05-1517) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-05-1517.md) |
| [Forskrift om vedtaksmyndighet etter energiloven](../forskrifter/forskrift-2013-06-21-681.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-21-681) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-21-681.md) |
| [Forskrift om vilkår for tilgang til nett for utveksling av elektrisk kraft over ](../forskrifter/forskrift-2006-12-20-1563.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-20-1563) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-20-1563.md) |
| [Forskrift til havbunnsmineralloven (havbunnsmineralforskriften)](../forskrifter/forskrift-2025-08-29-1740.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-29-1740) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-29-1740.md) |
| [Forskrift til havbunnsmineralloven kapittel 8 om erstatning til norske fiskere](../forskrifter/forskrift-2025-08-29-1741.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-29-1741) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-29-1741.md) |
| [Forskrift til havenergilova (havenergilovforskrifta)](../forskrifter/forskrift-2020-06-12-1192.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-12-1192) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-12-1192.md) |
| [Forskrift til lov 29. november 1996 nr. 72 om petroleumsvirksomhet kapittel 8 om](../forskrifter/forskrift-2008-12-12-1357.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-12-1357) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-12-1357.md) |
| [Forskrift til lov om felles regler for det indre marked for naturgass (naturgass](../forskrifter/forskrift-2003-11-14-1342.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-11-14-1342) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-11-14-1342.md) |
| [Forskrift til lov om petroleumsvirksomhet](../forskrifter/forskrift-1997-06-27-653.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-06-27-653) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-06-27-653.md) |
| [Instruks om energieffektive innkjøp av varer og tjenester i sentralforvaltningen](../forskrifter/forskrift-2025-06-20-1257.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1257) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1257.md) |
| [Midlertidig forskrift om bruk av flaskehalsinntekter](../forskrifter/forskrift-2022-10-27-1806.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-10-27-1806) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-10-27-1806.md) |
| [Midlertidig forskrift om stønad til kunder av nærvarmeleverandører](../forskrifter/forskrift-2023-10-30-1734.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-30-1734) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-30-1734.md) |
| [Midlertidig forskrift om støtte som følge av ekstraordinære utgifter til elektri](../forskrifter/forskrift-2022-06-30-1273.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-30-1273) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-30-1273.md) |
| [Omorganisering av departementsstrukturen fra 1. januar 1997 – overføring av fors](../forskrifter/forskrift-1996-12-20-1158.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-12-20-1158) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-12-20-1158.md) |
| [Opprettholdelse av vedtak om delegering av myndighet til Oljedirektoratet etter ](../forskrifter/forskrift-2007-12-20-1791.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-20-1791) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-20-1791.md) |
| [Overføring av myndighet til Energidepartementet etter lov av 1. juli 1927 nr. 1 ](../forskrifter/forskrift-2001-01-12-25.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-01-12-25) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-01-12-25.md) |
| [Overføring av myndighet til Energidepartementet etter plan- og bygningsloven § 1](../forskrifter/forskrift-1990-07-27-625.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-07-27-625) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-07-27-625.md) |
| [Overføring av myndighet til Samferdselsdepartementet etter § 5-2 i lov om fornyb](../forskrifter/forskrift-2014-06-20-791.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-20-791) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-20-791.md) |
| [Resolusjon om norsk statshøyhet over visse undersjøiske områder.](../forskrifter/forskrift-1963-05-31-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-05-31-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-05-31-1.md) |
| [Resolusjon om opprettelse av Olje- og energidepartementet.](../forskrifter/forskrift-1978-01-11-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-01-11-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-01-11-1.md) |
| [Resolusjon om vitenskapelige undersøkelser etter naturforekomster på den norske ](../forskrifter/forskrift-1969-01-31-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1969-01-31-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1969-01-31-2.md) |
| [Vedtak om supplering av Verneplan for vassdrag.](../forskrifter/forskrift-2005-02-18-888.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-02-18-888) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-02-18-888.md) |
