# Stortinget

*61 forskrifter*

Logglenkene viser eldre, uverifiserte rekonstruksjoner, ikke bekreftet forskriftstekst på en bestemt dato.

| Forskrift | Lovdata | Uverifisert rekonstruksjon |
|-----------|---------|-----------|
| [Bestemmelser om sikkerhetslovens anvendelse for Stortingets administrasjon](../forskrifter/forskrift-2018-12-19-2151.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-19-2151) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-19-2151.md) |
| [Bevilgningsreglementet](../forskrifter/forskrift-2005-05-26-876.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-05-26-876) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-05-26-876.md) |
| [Endringer i Stortingets forretningsorden](../forskrifter/forskrift-2021-06-17-2109.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-17-2109) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-17-2109.md) |
| [Fullmakt til Kongen til å ettergi skadebøter og inndragning til statskassen i st](../forskrifter/forskrift-1988-02-10-4875.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-02-10-4875) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-02-10-4875.md) |
| [Reglement for avgradering av dokumenter utstedt i Stortinget](../forskrifter/forskrift-2019-06-20-2325.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-20-2325) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-20-2325.md) |
| [Reglement for kontrollhøringer](../forskrifter/forskrift-2001-06-11-4957.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-06-11-4957) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-06-11-4957.md) |
| [Reglement om register for stortingsrepresentantenes verv og økonomiske interesse](../forskrifter/forskrift-2008-12-18-1617.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-18-1617) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-18-1617.md) |
| [Retningslinjer for bruk av tilskudd til stortingsgruppene og uavhengige represen](../forskrifter/forskrift-2020-11-24-3379.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-24-3379) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-24-3379.md) |
| [Stortingets forretningsorden](../forskrifter/forskrift-2012-06-07-518.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-07-518) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-07-518.md) |
| [Stortingets regler om dokumentinnsyn](../forskrifter/forskrift-2025-06-19-1640.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-19-1640) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-19-1640.md) |
| [Stortingsvedtak om CO2-avgift i petroleumsvirksomheten på kontinentalsokkelen fo](../forskrifter/forskrift-2025-12-18-2750.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2750) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2750.md) |
| [Stortingsvedtak om CO2-avgift på mineralske produkter for 2026](../forskrifter/forskrift-2025-12-18-2763.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2763) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2763.md) |
| [Stortingsvedtak om avgift av kol som blir utført frå Svalbard, for budsjettermin](../forskrifter/forskrift-2025-12-19-2781.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2781) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2781.md) |
| [Stortingsvedtak om avgift på HFK og PFK for 2026](../forskrifter/forskrift-2025-12-18-2765.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2765) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2765.md) |
| [Stortingsvedtak om avgift på NOXfor 2026](../forskrifter/forskrift-2025-12-18-2768.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2768) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2768.md) |
| [Stortingsvedtak om avgift på SF6for 2026](../forskrifter/forskrift-2025-12-18-2766.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2766) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2766.md) |
| [Stortingsvedtak om avgift på alkohol for 2026](../forskrifter/forskrift-2025-12-18-2753.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2753) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2753.md) |
| [Stortingsvedtak om avgift på avfallsforbrenning for 2026](../forskrifter/forskrift-2025-12-18-2764.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2764) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2764.md) |
| [Stortingsvedtak om avgift på elektrisk kraft for 2026](../forskrifter/forskrift-2025-12-18-2760.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2760) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2760.md) |
| [Stortingsvedtak om avgift på oppdrettsfisk for 2026](../forskrifter/forskrift-2025-12-18-2772.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2772) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2772.md) |
| [Stortingsvedtak om avgift på smøreolje mv. for 2026](../forskrifter/forskrift-2025-12-18-2762.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2762) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2762.md) |
| [Stortingsvedtak om avgift på sukker mv. for 2026](../forskrifter/forskrift-2025-12-18-2774.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2774) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2774.md) |
| [Stortingsvedtak om avgift på tobakksvarer mv. for 2026](../forskrifter/forskrift-2025-12-18-2754.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2754) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2754.md) |
| [Stortingsvedtak om avgift på trafikkforsikringer for 2026](../forskrifter/forskrift-2025-12-18-2756.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2756) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2756.md) |
| [Stortingsvedtak om avgift på undersjøisk utnyttelse mv. av kalkstein for 2026](../forskrifter/forskrift-2025-12-18-2771.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2771) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2771.md) |
| [Stortingsvedtak om avgift på viltlevende marine ressurser for 2026](../forskrifter/forskrift-2025-12-18-2773.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2773) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2773.md) |
| [Stortingsvedtak om avgift på vindkraft for 2026](../forskrifter/forskrift-2025-12-18-2761.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2761) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2761.md) |
| [Stortingsvedtak om avgifter på drikkevareemballasje for 2026](../forskrifter/forskrift-2025-12-18-2775.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2775) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2775.md) |
| [Stortingsvedtak om dokumentavgift for 2026](../forskrifter/forskrift-2025-12-18-2777.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2777) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2777.md) |
| [Stortingsvedtak om engangsavgift på motorvogner mv. for 2026](../forskrifter/forskrift-2025-12-18-2755.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2755) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2755.md) |
| [Stortingsvedtak om fastsetting av avgifter mv. til folketrygden for 2026](../forskrifter/forskrift-2025-12-18-2748.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2748) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2748.md) |
| [Stortingsvedtak om fastsetting av finansskatt på lønn for 2022](../forskrifter/forskrift-2021-12-14-3573.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-14-3573) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-14-3573.md) |
| [Stortingsvedtak om fastsetting av finansskatt på lønn for 2023](../forskrifter/forskrift-2022-12-13-2201.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-13-2201) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-13-2201.md) |
| [Stortingsvedtak om fastsetting av finansskatt på lønn for 2024](../forskrifter/forskrift-2023-12-14-2068.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-14-2068) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-14-2068.md) |
| [Stortingsvedtak om fastsetting av finansskatt på lønn for 2025](../forskrifter/forskrift-2024-12-13-3205.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-13-3205) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-13-3205.md) |
| [Stortingsvedtak om fastsetting av finansskatt på lønn for 2026](../forskrifter/forskrift-2025-12-18-2749.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2749) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2749.md) |
| [Stortingsvedtak om flypassasjeravgift for 2026](../forskrifter/forskrift-2025-12-18-2776.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2776) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2776.md) |
| [Stortingsvedtak om formues- og inntektsskatt til Svalbard for inntektsåret 2022](../forskrifter/forskrift-2021-12-15-3580.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-15-3580) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-15-3580.md) |
| [Stortingsvedtak om formues- og inntektsskatt til Svalbard for inntektsåret 2023](../forskrifter/forskrift-2022-12-13-2207.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-13-2207) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-13-2207.md) |
| [Stortingsvedtak om formues- og inntektsskatt til Svalbard for inntektsåret 2024](../forskrifter/forskrift-2023-12-18-2121.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-18-2121) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-18-2121.md) |
| [Stortingsvedtak om formues- og inntektsskatt til Svalbard for inntektsåret 2025](../forskrifter/forskrift-2024-12-18-3358.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-18-3358) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-18-3358.md) |
| [Stortingsvedtak om formues- og inntektsskatt til Svalbard for inntektsåret 2026](../forskrifter/forskrift-2025-12-19-2780.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2780) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2780.md) |
| [Stortingsvedtak om frekvens- og nummeravgift for 2026](../forskrifter/forskrift-2025-12-18-2778.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2778) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2778.md) |
| [Stortingsvedtak om inntekter ved tildeling av tillatelser](../forskrifter/forskrift-2023-12-20-2442.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-20-2442) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-20-2442.md) |
| [Stortingsvedtak om inntekter ved tildeling av tillatelser for 2026](../forskrifter/forskrift-2025-12-22-2790.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-22-2790) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-22-2790.md) |
| [Stortingsvedtak om merverdiavgift for 2026](../forskrifter/forskrift-2025-12-18-2752.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2752) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2752.md) |
| [Stortingsvedtak om miljøavgift på plantevernmidler for 2026](../forskrifter/forskrift-2025-12-18-2769.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2769) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2769.md) |
| [Stortingsvedtak om omregistreringsavgift for 2026](../forskrifter/forskrift-2025-12-18-2758.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2758) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2758.md) |
| [Stortingsvedtak om produktavgift til folketrygden for fiskeri-, hval- og selfang](../forskrifter/forskrift-2025-12-18-2751.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2751) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2751.md) |
| [Stortingsvedtak om skatt av inntekt og formue mv. for inntektsåret 2022 (Stortin](../forskrifter/forskrift-2021-12-14-3571.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-14-3571) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-14-3571.md) |
| [Stortingsvedtak om skatt av inntekt og formue mv. for inntektsåret 2023 (Stortin](../forskrifter/forskrift-2022-12-13-2199.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-13-2199) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-13-2199.md) |
| [Stortingsvedtak om skatt av inntekt og formue mv. for inntektsåret 2024 (Stortin](../forskrifter/forskrift-2023-12-14-2071.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-14-2071) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-14-2071.md) |
| [Stortingsvedtak om skatt av inntekt og formue mv. for inntektsåret 2025 (Stortin](../forskrifter/forskrift-2024-12-13-3203.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-13-3203) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-13-3203.md) |
| [Stortingsvedtak om skatt av inntekt og formue mv. for inntektsåret 2026 (Stortin](../forskrifter/forskrift-2025-12-18-2747.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2747) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2747.md) |
| [Stortingsvedtak om svovelavgift for 2026](../forskrifter/forskrift-2025-12-18-2767.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2767) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2767.md) |
| [Stortingsvedtak om tillegg i skatt på grunnrenteinntekt i kraftforetak for innte](../forskrifter/forskrift-2022-12-13-2197.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-13-2197) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-13-2197.md) |
| [Stortingsvedtak om tollavgift for 2024](../forskrifter/forskrift-2023-12-14-2076.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-14-2076) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-14-2076.md) |
| [Stortingsvedtak om tollavgift for 2026](../forskrifter/forskrift-2025-12-18-2779.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2779) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2779.md) |
| [Stortingsvedtak om veibruksavgift på drivstoff for 2026](../forskrifter/forskrift-2025-12-18-2759.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2759) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2759.md) |
| [Stortingsvedtak om vektårsavgift for 2026](../forskrifter/forskrift-2025-12-18-2757.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2757) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2757.md) |
| [Stortingsvedtak om årsavgift knyttet til mineraler for 2026](../forskrifter/forskrift-2025-12-18-2770.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2770) | [rekonstruksjonslogg](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2770.md) |
